### ISSUE TITLE
Should work/1502 have Brock, Martyrs of Mount Berʾain listed as an edition/trans?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#100]
@jsaintlauren So when I was typing up the text for the "not found" page, I noticed that Brock's edition/translation of Martyrs of Mount Berʾain is not listed in http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1502. Should we add it (is it the same version of the work)?

**Comment by jsaintlauren** [comment]
Yes. That is why we need the bibliography stuff from Kiger entered. Nothing
done in the last 18 years is on the bibliography:(.

**Comment by nathangibson** [comment]
OK. I'll go ahead and enter this one manually since I have it.

**Comment by jsaintlauren** [comment]
thanks
