### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#101]
There's a 404 error page in TEI here that can be implemented: https://github.com/srophe/srophe-app-data/blob/dev/404.xml

Feel free to modify or move the TEI record as you see appropriate. 

Possibly related issue:
https://github.com/srophe/srophe-eXist-app/issues/280

**Comment by wsalesky** [comment]
Thanks @nathangibson I will try to get it hooked up today!

**Comment by wsalesky** [comment]
404 page. 

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/404

Working on getting the redirects correct for incorrect record ids.

**Comment by nathangibson** [comment]
:+1:

**Comment by wsalesky** [comment]
Okay, if you put in a URI that does not exist you should get redirected. Please let me know if you get redirected for a record you think exists. 

Also resolves: https://github.com/srophe/srophe-eXist-app/issues/528

**Comment by nathangibson** [comment]
Awesome!
