### ISSUE TITLE
Bibl idno standardization needed. 

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-app-data#102]
Some bibl records record the idno in publicationStmt as: 
http://syriaca.org/bibl/11/tei

And some use 'source'
http://syriaca.org/bibl/1/source

In order to pull records by a unique ID we will need to standardize this one way or another. I found that using just http://syriaca.org/bibl/1 will return more then a single match, particularly for http://syriaca.org/bibl/1, which returns over 600 matches (I am guessing articles in a book). 

Or we could change how the monograph is encoded when for article bibl records? Should we be using the idno, or should we be using a ptr or ref? Just thinking aloud here. 

RE: srophe-eXist-app#544

**Comment by wsalesky** [comment]
Change /source to /tei

**Comment by davidamichelson** [comment]
Yes please change all to http://syriaca.org/bibl/11/tei instead of /source
