### ISSUE TITLE
Mystery "-h" in @xml:id

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#1022]
There is a "-h" in the @xml:id on tei:persName in 335 records. [Example](https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/10.xml#L227). I'm assuming this just needs manual cleaning.

**Comment by dlschwartz** [comment]
Mystery partly solved: https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/321.xml#L236

**Comment by wlpotter** [comment]
Cf. #883

**Comment by wlpotter** [comment]
Also cf. #592 which has the context for why the "-h" was used

**Comment by dlschwartz** [comment]
I will manually remove the "-h" and add an appropriate number.
