### ISSUE TITLE
Pseudonymous Authors

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#1031]
We currently have four person/author records that include "Pseudo" in the persName. Only one of these "George of Arbela, Pseudo" (person/503) contains a `@type="pseudonymous-author"` on the tei:person element for his record. The others make no indication in the data.

Should we include this in all records or delete it from the one. It might be nice to filter RDF by this designation.

**Comment by wlpotter** [comment]
Relevant Google docs: https://docs.google.com/document/d/1NhwuazMJqOg8WVYyY8FYtBU2DzmLy2isGQhBlL00fXA/edit

https://docs.google.com/drawings/d/18EJGIpkhit037qX6JcHeMibYx3SnP-wHiz4fS173CiM/edit

**Comment by dlschwartz** [comment]
Move from @type to @ana with the value: "syriaca-pseudonymous".
