### ISSUE TITLE
Template for record redirect

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#104]
@wsalesky @davidamichelson @dlschwartz @jsaintlauren 

What do you think of the following as an example of a deprecated record that should be redirected? https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/saints/tei/1561.xml

You can see the changes I made to it in this commit: https://github.com/srophe/srophe-app-data/commit/4bb40dc24e5e0574e266d336719d915e7128b52e#diff-52aa337f3c0eeca0a6806eb44cf86fa4L7

Essentially, I am doing the following:
1. Adding " [deprecated]" to the record title
2. Keeping the original idnos but adding an idno with type "redirect" to point to where the user should be redirected.
3. Changing the revisionDesc status and adding a change element.
4. Adding some text to the body to notify the user of the deprecation and redirect. (head + desc + notes + bibl)
5. Adding a "change" attribute to several of the elements which points to the change element in revisionDesc.

Should we keep the original content of the record? The advantage would be that it would be easier to identify our own or others' references to the old record. The disadvantage would be that we would have to make sure we handle the redirect in a way that partner systems can follow -- otherwise they will pick up the deprecated data. But we want to do the latter anyway. 

related: https://github.com/srophe/srophe-eXist-app/issues/528

**Comment by davidamichelson** [comment]
Additional aspects:
Deprecated records should not be indexed for search or browse
The full record at the date of deprecation should be moved to a separate repository, not handled by our exist app?
The redirect recipient record should include a note about the redirect
deprecated records should include links to the full copy of the deprecated record.

**Comment by nathangibson** [comment]
@davidamichelson Can you review the following documentation for record deprecation please: https://github.com/srophe/srophe-deprecated-data/blob/master/README.md

**Comment by nathangibson** [comment]
@wsalesky I would like to write a single file that has the generic text shown to a user on the redirect page for any deprecated record. Should I include this in the TEI of the deprecated record using `<xi:include>` or `@copyOf`, or should this just be an HTML page?

**Comment by nathangibson** [comment]
Nathan will create an html page (301.html) that will be displayed until the redirect kicks in.

**Comment by nathangibson** [comment]
Update: we will just move the full file into a deprecated folder within srophe-app-data with the tagging to generate the redirect.

**Comment by nathangibson** [comment]
OK, @wsalesky, the HTML page that should display for a redirect is here: https://github.com/srophe/srophe-eXist-app/blob/dev/srophe-app/301.html

**Comment by nathangibson** [comment]
I've moved deprecated records to the https://github.com/srophe/srophe-app-data/tree/dev/data/deprecated folder. Records in that folder should not be indexed or searchable. 

I'm now handing this off to @wsalesky  to finish the implementation in the eXist-db settings. 

Deprecated records have the following features:
- `revisionDesc/@status="deprecated"`
- `idno/@type="redirect"` (in addition to original idno) for both "/tei" idno in header and entity idno in body
- " [deprecated]" appended to record `title[level="a"]`
- `change` element with `@xml:id`
- `desc` as first child of `body` describing the deprecation in human-readable prose
- `@change` pointing to the deprecation `change` on the above `idno` and `desc` elements

**Comment by wsalesky** [comment]
@nathangibson @davidamichelson Do we want the 301 page to display? It is actually easier to just redirect to the correct record, without a 'stop' in the middle. However I can display the 301 page if you think it is really useful.

**Comment by nathangibson** [comment]
Hmm, I'm torn, because if people are using a deprecated URI, we might want to alert them to that fact.  1. Would it be just as hard to put a little message at the top of the target page saying something like, "The record you queried has a new URI. Please update your links."  
 2. Will machine queries also be redirected automatically? If so, this may not be as important. 
Thoughts, @davidamichelson ?

**Comment by wsalesky** [comment]
@davidamichelson Any thoughts on this?

**Comment by wsalesky** [comment]
Done. See: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1234
