### ISSUE TITLE
Bibls 742 and 2254 might be the same

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#1045]
https://syriaca.org/bibl/search.html?keyword=liste+martyrologique

**Comment by wlpotter** [comment]
Bibl 742 is linked to CBSC URI http://zotero.org/groups/4861694/items/JXJTN7FL
Bibl 2254 did not have a crosswalk identified by the students, but this does look to be the same as 742. So I will add the crosswalk to the same CBSC URI

**Comment by davidamichelson** [comment]
Thanks Will, I think we can close this.
