### ISSUE TITLE
Disambiguation of places

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#1047]
We currently use `<note type="disambiguation">` in places. Data edits and schema work on persons have raised this issue there. A tei:relation element seems a better place to capture this data. I have made these edits in the 2023_SchemaWork branch.

Winona needs to make changes in the HTML display.

We need to update the places wiki documentation

**Comment by dlschwartz** [comment]
A `<note type="disambiguation">` occurs 35 times in place records. In six of these, the entity from which that place is distinguished is not another Syriaca.org URI but a Pleiades URI. Sorting out these relationships will require some effort. See #1048

**Comment by davidamichelson** [comment]
We will move these to relation element as well as in persons.

**Comment by dlschwartz** [comment]
This issue duplicates https://github.com/srophe/srophe-app-data/issues/1030. I will close this issue and proceed with the other.
