### ISSUE TITLE
Saints Records Needing Cleaning

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#1060]
Below is a list of saints records that need cleaning and some documentation about the error messages you will find in those records. In some cases there are additional notes/questions marked out as comments in the XML. You can ignore the error message "This @ref attribute is not a person URI in use in Syriaca.org data..." but otherwise you should have a green box in oXygen when you've resolved the necessary issues.

For this work, please use the branch [2023-06-26_Data_Cleaning](https://github.com/srophe/srophe-app-data/tree/2023-06-26_Data_Cleaning)!

- Saints Records Needing Cleaning: 

- [x] #1092
- [x] #1093
- [x] #1094
- [x] #1095
- [x] #1096
- [x] #1099
- [x] #1100
- [x] #1107
- [x] #1118
- [x] #1119
- [x] #1121
- [x] 1135 attestation number is repeated and also citedRange needs cleaning by adding units
- [x] 1255 URI needs checking
- [x] 1257 Cited ranges need checking
- [ ] #1136
- [x] #1135
- [x] #1134
- [x] 1353 bib1353-4 need citation cleaning and checking
- [x] 1376 Bibl -5 needs identification and a URI
- [x] 1391 Bibl -7 needs citation cleaning.
- [x] 1393 Bibl -8 needs citation cleaning.
- [x] 1397 Item bib1397-3 is the greek edition of the text. Should we delete it or point to the Syriac edition? I don't think we lose anything be deleting it.
- [x] 1417 Citation needs checking against original of http://syriaca.org/bibl/1425
- [x] 1432 The cited range is not right, maybe two records are combined. Please check Fiey's Saints Syriaques. 
- [x] 1473 Bibl needs checking
- [x] 1482 Bibl needs checking and changed to @unit
- [x] 1484 Bibls need checking
- [x] 1486 Bibls need checking
- [x] 1487 Bibl -4 needs checking
- [x] #1130
- [x] 1519 Bibliography item is missing ptr URI
- [x] 1613 Needs source for floruit date.
- [x] 1997 Is a source missing here? Did Zanetti's database have dates?
- [x] 3026 A bibliographic item needs clarification, Sauget, BS?
- [x] 3027 A bibliographic item needs clarification, Sauget, BS?

----

- [x] #1080
- [x] 1097
- [x] 1098 citedRange needs cleaning/splitting into multiple parts
- [x] #1114
- [x] #1113
- [x] 1123 citedRange needs conversion to Arabic script numerals (٢٥)?
- [x] 1124 citedRange needs cleaning/splitting into multiple parts
- [x] 1135 attestation number is repeated and also citedRange needs cleaning by adding units
- [x] 1143 note could be deleted?
- [x] #1087
- [x] 1156 note could be deleted?
- [x] 1160 same problem as #1087 or is this an entry number?
- [x] 1165 note needs conversion to bibl item (cf. Fiey's abbreviations)
- [x] 1167 note needs conversion to bibl item (cf. Fiey's abbreviations) = Šuhadā'
- [x] #1088
- [x] #1089
- [x] #1090
- [x] 1175
- [x] 1178
- [x] 1180
- [x] 1192
- [x] 1202
- [x] #1111
- [x] #1110
- [x] 1217
- [x] 1221
- [x] 1222
- [x] 1238
- [x] 1239
- [x] 1242
- [x] 1243
- [x] 1244
- [x] 1246
- [x] #1108
- [x] 1253
- [x] 1254
- [x] 1255 URI needs checking
- [x] 1257 Cited ranges need checking
- [x] 1258
- [x] 1260
- [x] 1270 We have a note "Problem Entry". Why did we leave that note? Does this need revision?
- [x] 1273
- [x] 1278 Citation needs review
- [x] 1281
- [x] 1289
- [x] 1295
- [x] #1107
- [x] 1309
- [x] 1311
- [x] 1315
- [x] 1318
- [x] 1321
- [x] 1334
- [x] 1340
- [x] 1343 bib1343-3 citation needs cleaning and checking
- [x] 1350
- [x] 1353 bib1353-4 need citation cleaning and checking
- [x] 1376 Bibl -5 needs identification and a URI
- [x] 1391 Bibl -7 needs citation cleaning.
- [x] 1393 Bibl -8 needs citation cleaning.
- [x] 1397 Item bib1397-3 is the greek edition of the text. Should we delete it or point to the Syriac edition? I don't think we lose anything be deleting it.
- [x] 1409
- [x] #1106
- [x] 1417 Citation needs checking against original of http://syriaca.org/bibl/1425
- [x] #1105
- [x] 1419
- [x] 1420 
- [x] 1432 The cited range is not right, maybe two records are combined. Please check Fiey's Saints Syriaques. 
- [x] 1443
- [x] 1450
- [x] 1460
- [x] #1104
- [x] 1473 Bibl needs checking
- [x] 1474
- [x] 1475
- [x] 1476
- [x] 1477
- [x] 1482 Bibl needs checking and changed to @unit
- [x] 1484 Bibls need checking
- [X] #1102
- [x] 1486 Bibls need checking
- [x] 1487 Bibl -4 needs checking
- [x] 1489
- [x] 1502 Bibl 1502-3 needs checking
- [x] 1505
- [x] 1507
- [x] 1509
- [x] 1513
- [x] 1519 Bibliography item is missing ptr URI
- [x] #1101
- [x] 1544
- [x] #1100
- [x] #1099
- [x] 1613 Needs source for floruit date.
- [x] 1641
- [x] 1655
- [x] 1711
- [x] #1098
- [x] #1097
- [x] #1096
- [x] 1919
- [x] #1095
- [x] 1983
- [x] 1997 Is a source missing here? Did Zanetti's database have dates?
- [x] #1094
- [x] #1093
- [x] #1092
- [x] 2063
- [x] 2065
- [x] 2114
- [x] #1121
- [x] #1118
- [x] #1119
- [x] 3026 A bibliographic item needs clarification, Sauget, BS?
- [x] 3027 A bibliographic item needs clarification, Sauget, BS?
- [x] 3031 xml:ids for the @source were wrong, changed #bib8-7 to #bib3031-1

- Citation Cleaning
     - Error Msg: "A @source attribute must point to an @xml:id attribute on a <bibl> element or a <listBibl> element. Multiple values are allowed and must be separated by a blank space." 
          - This is mainly a matter of @source atts pointing to bibl entries that aren't there. It's very common. I'm guessing it's a data transform error. Rather than just delete the points that don't have a target, I want you to see if you can't find bigger data issues. If not, just delete the pointers that lack a referent.
          - In 8 author records, there are no bibl elements at all. Sometimes there is a @source pointer to a bibl element but there are no bibl elements at all. Every record must have at least one bibl.
     - Error Msg: "element "citedRange" missing required attribute "unit""
          - There was a lot of noise in the bibls. I cleaned a lot but many of the citedRange elements need some specific knowledge to sort out. Technically, all we need in a tei:bibl in a person record are two things. 1) A tei:ptr with a @target pointing to a bibl URI. 2) A tei:citedRange when that differs from what is in the bible record itself. If the bibl points to an entire article and the page ranges for that article are in the bibl record, we don't technically need a tei:citedRange here. The caveat to these minimal requirements is that without some info here (title, author) these tei:bibl elements aren't very human readable. That is the main reason for including additional information here.
          - When fixing errors that appear on tei:citedRange, each piece of the citation needs it's own tei:citedRange. So, a page range takes one; a volume number takes another; a section takes another. Also, as discussed above, this data may duplicate what is in the bibl record. If that is the case and you are looking at a mess to sort out, you can delete citedRange data that duplicates what's in the bibl record.
     - Error Msg: "value of attribute "target" is invalid; missing token; must be a URI matching the regular expression "\S+""
          - This is a bibl entry that lacks a URI pointing to our bibl record
     - Error Msg: "A <title> element in a <bibl> element within the text body must have an @xml:lang attribute unless the content of the text node is a URL"
          - In a couple of cases I wasn't sure what to put here.
     - Error Msg: "value of attribute "source" is invalid; missing token; must be a URI matching the regular expression "\S+""
          - This element needs a pointer to a bibl entry
     - Error Msg: "value of attribute "unit" is invalid; must be equal to "URL", "col", "entry", "fol", "line", "map", "p", "part", "section" or "vol""
          - In a couple of cases I wasn't sure what to put here.

- Note Cleaning
     - Error Msg: "element "note" missing required attribute "type"." Two things are going on here. 
          - We find notes inside a bibl element. We want to move these up with the other notes. They will likely take a @type="discursive". In some cases these just need to be rewritten as discursive notes ABOUT THE PERSON, not about the bibliographic item. If they are about the bibliographic item, the probably don't belong in the person record. To make this about the person, try something like 'A hagiography about Fred was edited by Smith' and then source it to the @xml:id on the appropriate bibl element.
          - The other thing captured with this error message is a tei:note child of tei:person (or tei:personGrp) that appears among the bibl elements. In this case, it looks like a transform error because the content of the note is bibliographic information. What you will need to do is figure out whether this should be turned into a bibl element or if it is simply noise that should be deleted.

**Comment by davidamichelson** [comment]
On record https://syriaca.org/person/1097, the bibl entry: https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/saints/tei/1097.xml#L265 should have both 6 and 7 as the cited range for entry

**Comment by davidamichelson** [comment]
This issue is done, some sub issues remain open but all the records validate.
