### ISSUE TITLE
Person merge script

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#107]
@davidamichelson @dlschwartz 

So I've written a script to merge duplicate persons. It will definitely need supervision, but I think correcting its output will save a lot of time over manually copying and pasting elements and attributes. 

It works by choosing a "master" record and a "secondary" record. The "master" is kept and is authoritative for things we can only have one of, like URIs, headwords, abstracts, etc. The "secondary" is deprecated after its data is merged into the master. 

See what you think of this trial run, which is supposed to merge http://wwwb.library.vanderbilt.edu/person/1729 into http://wwwb.library.vanderbilt.edu/person/483. You can see the changes at this commit: 
https://github.com/srophe/srophe-app-data/commit/a1d88d063fd044c77863e81ceb21b3bde4d6c760.

The only problems I notice are 
1. There are 2 syriaca-headwords. 
2. The attestation elements need to be renumbered.

Do you see any other problems?

**Comment by davidamichelson** [comment]
GReat, let's discuss tomorrow

**Comment by nathangibson** [comment]
1. Add `<idno type="deprecated">` after main idno in master record.
2. Try it on the srophe/persons/new-saints-data/overlap records, but note that idno for master and secondary records will be the same!

**Comment by nathangibson** [comment]
Testing on the saints overlap, and one thing I should mention is that whenever the records to be merged both have abstracts, the new abstract should be reconstructed manually, as the script will only keep the one in the master record. (I don't think it makes sense to try to combine the abstracts automatically, as this is not likely to produce good human-readable prose.)

Some fixes that I'll be doing: 
 1. Script is duplicating the SBD seriesStmt.
 2. Script is removing text that occurs as a direct child of note.
 3. Script is keeping only the record editors from master (should add the ones from secondary record).

**Comment by nathangibson** [comment]
3. is fixed.

**Comment by nathangibson** [comment]
2 is fixed.

**Comment by nathangibson** [comment]
OK, @davidamichelson , I'm trying the merge script on the overlap persons. I'll put the links here for you to take a look at. 

First one is https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/9.xml. This was merged from 9, 9a, and 9b in the "overlap" folder. 

A couple of questions:
 1. Should I do anything different with the changelog? It's rather nondescript. I could include the filename or the record title for the changes merged from other records if that would help. 
 2. The editors and respStmts for the record itself (not the seriesStmts) are rather messy. Do you have any suggestions? Should we clean them up later as they'll be fairly standard? Or sort them by person?

**Comment by nathangibson** [comment]
@davidamichelson Next is https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/25.xml.

A couple practical questions came up on this one:
 1. When manually combining GEDSH-derived abstracts with @jsaintlauren 's, it would make sense to have a way to source certain parts of the abstract rather than the whole thing. Could we use `<seg>` with `@source` for this as I have done in this abstract? (See https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/25.xml#L269)
 2. When there are different dates for the same event with different sources, how should we record this? **Option A** is to do as I've done here by recording multiple (conflicting) elements: https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/25.xml#L278. The XSLT would have to be tweaked to display this in a friendly way, such as "Death: 420 (1)/421 (2)", where the parentheses are footnotes. **Option B** is to put 2 date elements inside a death element, like so: 
                    `<death><date when="0420" syriaca-computed-start="0420-01-01" source="#bib25-8">420</date> or <date when="0421" syriaca-computed-start="0421-01-01" source="#bib25-2">421</date></death>`.
Of course, this would also require XSLT tweaks.

What do you think?

**Comment by nathangibson** [comment]
Next: https://github.com/srophe/srophe-app-data/blob/b46b64877a6e3a663e77ce961e7b5190248be50a/data/persons/tei/10.xml. Abstract manually merged (rewritten).

**Comment by nathangibson** [comment]
@davidamichelson @jsaintlauren In the saints overlap folder (https://github.com/srophe/persons/tree/master/new-saints-data/overlap) which I'm using to merge in saints data into author records, many/all of the records have `<idno type="BHS">`. However, BHS ids should be only for works, right? So they should only be cited in the bibliography as entry numbers?

**Comment by nathangibson** [comment]
The overlap records often have unsourced English names (see e.g., person/25, person/10). These may be J.N.'s translations of Zanetti. Should I add a `resp="http://syriaca.org/documentation/editors.xml#jnmsaintlaurent"` to these?

**Comment by nathangibson** [comment]
Next: https://github.com/srophe/srophe-app-data/blob/nathangibson-2016-05-17-merging-overlapping-saints/data/persons/tei/13.xml

**Comment by nathangibson** [comment]
Note to self: We will need to add the commemorated relationships.

**Comment by nathangibson** [comment]
Next to review: 
https://github.com/srophe/srophe-app-data/blob/nathangibson-2016-05-17-merging-overlapping-saints/data/persons/tei/26.xml
and 
https://github.com/srophe/srophe-app-data/blob/nathangibson-2016-05-17-merging-overlapping-saints/data/persons/tei/42.xml

**Comment by nathangibson** [comment]
Next to review: https://github.com/srophe/srophe-app-data/blob/nathangibson-2016-05-17-merging-overlapping-saints/data/persons/tei/44.xml

@davidamichelson Here's your chance to edit the Philoxenos abstract. Also, isn't there a recent book missing from the bibliography? :-)

**Comment by nathangibson** [comment]
Next: https://github.com/srophe/srophe-app-data/blob/nathangibson-2016-05-17-merging-overlapping-saints/data/persons/tei/50.xml

**Comment by nathangibson** [comment]
I'm editing the above notes and putting all the merged records to review here and continue to update it. 
https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/9.xml
https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/25.xml
https://github.com/srophe/srophe-app-data/blob/b46b64877a6e3a663e77ce961e7b5190248be50a/data/persons/tei/10.xml
https://github.com/srophe/srophe-app-data/blob/nathangibson-2016-05-17-merging-overlapping-saints/data/persons/tei/13.xml
https://github.com/srophe/srophe-app-data/blob/nathangibson-2016-05-17-merging-overlapping-saints/data/persons/tei/26.xml
https://github.com/srophe/srophe-app-data/blob/nathangibson-2016-05-17-merging-overlapping-saints/data/persons/tei/42.xml
https://github.com/srophe/srophe-app-data/blob/nathangibson-2016-05-17-merging-overlapping-saints/data/persons/tei/44.xml
https://github.com/srophe/srophe-app-data/blob/nathangibson-2016-05-17-merging-overlapping-saints/data/persons/tei/50.xml

**Comment by nathangibson** [comment]
@davidamichelson @wsalesky At least two of the person records in https://github.com/srophe/persons/tree/master/new-saints-data/overlap (51 and 52) have source attributes on the first name pointing to a non-existing source (#10). Can anyone illuminate me what might have happened here?

**Comment by nathangibson** [comment]
For multiple deaths, etc. from conflicting sources (see https://github.com/srophe/srophe-app-data/issues/107#issuecomment-219481800), use Option B.

**Comment by nathangibson** [comment]
Re. https://github.com/srophe/srophe-app-data/issues/107#issuecomment-219665108, no need to add a resp.
