### ISSUE TITLE
Person/825 -> Liber castitatis and Liber Superiorum are conflated in some bibl records, need to be separated.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#1085]
See this example: https://syriaca.org/person/825
```
 <bibl xml:id="bib825-7">
                        <title xml:lang="la">Liber castitatis</title>
                        <ptr target="http://syriaca.org/bibl/1310"/>
                        <title xml:lang="la">Liber superiorum</title>
                        <citedRange unit="entry">n° 105 et 117</citedRange>
                        <citedRange>II. 23</citedRange>
                    </bibl>
```

**Comment by davidamichelson** [comment]
This change appears to have come in here: https://github.com/srophe/srophe-app-data/commit/69c01d280968144e6c9dd88b671c7968c68fcd60

**Comment by davidamichelson** [comment]
We can write as script to look for these everywhere (with multiple titles).

**Comment by dlschwartz** [comment]
I only find one instance, here in 825. I searched at path: bibl/title for "Liber superiorum". I got four hits only 825 has this problem. No script is necessary. Please let me know if I'm missing something.

If not, can you sort these out manually? Do we have data sourced to each work? If so, great. If not, I suppose we should delete the one that no source attribute points to.
