### ISSUE TITLE
Conflict with candida records 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#109]
We need two records for Candida.  
The one commemorated in this work: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1143 who is Persian martyr 

And the commemorated in this work: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/449 who is the daughter of a soldier, and in the Paradise of the fathers.

The Q record for Candida incorrectly conflates them. -  http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1637  - 

I will give 1637 to work 449 - so please create another q record for hte Candida of work 1143

**Comment by wlpotter** [comment]
https://syriaca.org/work/1143 commemorates https://syriaca.org/person/3003

https://syriaca.org/work/449 commemorates https://syriaca.org/person/1637

I believe this can be closed? @jsaintlauren
