### ISSUE TITLE
845 Update relation and multi @source

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#1091]
@dlschwartz I found something else wrong in this record, I think. The relation element was using an xml:id rather than a URI. I changed it here: https://github.com/srophe/srophe-app-data/commit/42b47ed44e37afad1849e606372a4790491adcd8#diff-eb591a42952f9ae5812a9f5dff0db6f2addd605ad2c018b887446ab7f061a21aL151

Did I do the right thing or mess things up? Should the schema check for this?

**Comment by davidamichelson** [comment]
This one is a similar case (1087): https://github.com/srophe/srophe-app-data/compare/77b80f979dd7c014e91223b4abc0eead01b8d3a0...2e9e778a936ba6feb67cc51295183c2070668803#diff-ea529f7b72275e0cac6e05d58db1aa6b5bfc138a905ea42f68c379cd26c1c2afL181

**Comment by dlschwartz** [comment]
Your changes look correct to me. I will build this into the persons schema but I wanted to get mostly clean records before I started developing that schema.

**Comment by dlschwartz** [comment]
This issue duplicates https://github.com/srophe/srophe-app-data/issues/1043. I will close this one.
