### ISSUE TITLE
1901 Needs a source for the floruit dates. Also this is a collective person: 40 martyrs, how should we handle?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#1096]
This is record http://syriaca.org/person/1901

**Comment by jsaintlauren** [comment]
Cite - Van Dam, Becoming Christian: The Conversion of Roman Cappadocia, Philadelphia 2003, p. 134

**Comment by davidamichelson** [comment]
Cite Forty Martyrs of Sebaste   Quick reference
The Oxford Dictionary of Saints (5 ed.)
