### ISSUE TITLE
Duplicate Saint's Records in Wrong Directory

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#120]
Hi W,

Just a quick FYI, it looks like when you ran the script on the headwords for Saints, you may have duplicated all the records for the saints?

We have been keeping them here: https://github.com/srophe/srophe-app-data/commits/dev/data/persons/tei/saints/tei

But I now see that as of your commit last week they are also at https://github.com/srophe/srophe-app-data/commits/dev/data/persons/tei

See the history for https://github.com/srophe/srophe-app-data/commits/dev/data/persons/tei/1109.xml

Can you fix this please?

Thanks,
Dave

**Comment by wsalesky** [comment]
Sorry, I have moved them back.

**Comment by davidamichelson** [comment]
No problem, but did we lose any changes that happened to the ones in the subdirectory in the mean time? I can't remember when I last merged changes there.

**Comment by wsalesky** [comment]
I don't think so, but I will double check the history after the kids are in bed.

**Comment by nathangibson** [comment]
I see at least that this commit (https://github.com/srophe/srophe-app-data/commit/7b4fd343a0d17957a05d24f75377f83565b7e5bb#diff-da10c8de8b0d8c09fcdf82a0c47f918a) seems to have overwritten some changes I had made to person/1729 (compare current version with https://github.com/srophe/srophe-app-data/blob/ff8368c5daf11e2104a32457466d2cd7ef7dd66b/data/persons/tei/saints/tei/1729.xml). Not sure if other files are affected.

**Comment by wsalesky** [comment]
I will check.

**Comment by wsalesky** [comment]
Hi Nathan, the only difference in the file I see is the title/@type='a' was overwritten, so it no longer include '[deprecated]', this was actually an issue with my script, not with the merge. I rewrote the title based on the new English headword, and replaced the whole title element, rather then trying to extract just the Gedesh headword.  

Do you see anything else that was overwritten? If not I will fix the header and then I think we are fine re: merge.
