### ISSUE TITLE
Simeon bar Sabbae (person/9)

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#124]
@davidamichelson @jsaintlauren Do either of you know of any basis for the Syriac name "ܫܡܥܘܢ ܒܪ ܫܒ̈ܥܐ" (#name9-17), which comes from Zanetti? The standard form (and our headword) seems to be "ܫܡܥܘܢ ܒܪ ܨܒܥ̈ܐ". I didn't spot the version with ܫ in the BHS PDFs. 

So I'll plan to delete that name variant unless you know of a reason I shouldn't.

See https://github.com/srophe/srophe-app-data/blob/f6d26ef565ce2ac2d902c9e350a9ddb408be24a8/data/persons/tei/9.xml#L266.

**Comment by jsaintlauren** [comment]
Yes, please delete it.

Thanks!

**Comment by nathangibson** [comment]
OK!
