### ISSUE TITLE
Severus of Antioch (http://syriaca.org/person/51)

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#129]
@jsaintlauren  Severus has a `@from` date of "0521" on his saint `<state>`. Not sure what that would mean -- I think it is accidentally the date he took office. OK if I delete it?

**Comment by jsaintlauren** [comment]
Yes, please delete it.
It is probably a floruit date.

**Comment by nathangibson** [comment]
Deleted.
