### ISSUE TITLE
Pethions

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#133]
There are two different Pethions conflated into one Q record.

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1409 is the patriarch,
and we need a different URI for the Pethion of the Anahid cycle. - word 292

**Comment by nathangibson** [comment]
Yes, my colleague Miriam Lindgren Hjälm is actually writing an article about the identity of the Pethions, so I’m hoping to get her help on this. But I may need to do something with it before that.

**Comment by nathangibson** [comment]
I am working on this. Turns out we do have a Pethion for the Anahid cycle -- http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1410. I will correct this once I get the other Pethions sorted (hopefully today).
Cf. #78

**Comment by nathangibson** [comment]
OK, persons http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1409 and http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1410 and work http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/292 should now be correct (once I merge my branch into dev). I am working on getting the other Pethions included and disambiguated.

**Comment by jsaintlauren** [comment]
Thanks!!

On Wednesday, June 29, 2016, nathangibson <notifications@github.com> wrote:

> OK, persons
> http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1409 and
> http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1410 and work
> http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/292 should now
> be correct (once I merge my branch into dev). I am working on getting the
> other Pethions included and disambiguated.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/srophe/srophe-app-data/issues/133#issuecomment-229366983>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEY0lJ_K4ph1OGBHQu8UXRnIAC7uiH19ks5qQnxbgaJpZM4Ih3Mb>
> .
>


-- 
Sent by my large poodle - please excuse typos

**Comment by wlpotter** [comment]
I believe the remaining work on Pethions was moved to #324
