### ISSUE TITLE
Rendering of Titles for Anonymous/Anonymi

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#135]
I edited the title by hand for this record, it views fine on its own but it shows up a bit odd in a search result (URI number is used twice). Is this because it's anonymous?

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=+Anonymi+1745

Jamey may start editing these today, so please let me know.

Also, one question, in the title, how many white spaces are between the dash and the text on either side?

**Comment by wsalesky** [comment]
Should be one space on either side of the dash. 

The search results is just an xslt bug. I will fix it tonight. It should not change how you enter data.

**Comment by wsalesky** [comment]
Moving this to app. RE: https://github.com/srophe/srophe-eXist-app/issues/616
