### ISSUE TITLE
Add relations & attestations for saints-overlap

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#136]
Once Nathan is done merging saints with authors (see https://github.com/srophe/srophe-app-data/issues/107), do the following (using the script that already exists?):
 1. Look up the BHSE record corresponding to the idno type="BHS" in the person record.
 2. Add a relation to person URI into the BHSE record.
 3. Add attestation into the person record using the URI of BHSE record. 
 4. Remove idno type="BHS" from the person record.

For now, assigned to Nathan. He will hand this off to Winona once the merging is done.

**Comment by davidamichelson** [comment]
At the same time we can take care of https://github.com/srophe/srophe-app-data/issues/123 which involves updating the preferred English names use in attestations

**Comment by nathangibson** [comment]
Oops, I forgot to hand this off to @wsalesky. But this should wait until we have confirmation from @davidamichelson that person headwords are ready.

**Comment by davidamichelson** [comment]
I think this is done! Looks Great.
