### ISSUE TITLE
tei:titleStmt for merged authors and saints

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#139]
Hi All for now here is a model titleStmt for merged records: https://gist.github.com/davidamichelson/dcccaa5038ccb47805bb06458c3aa991

Some questions:
1. @wsalesky If you can please let me know your thoughts on this issue -https://github.com/srophe/srophe-eXist-app/issues/574 - we will change this accordingly.
2. @jsaintlauren Could you please read over the respStmts and see if I have accurately credited everything?
3. @nathangibson If this is good we can insert it into all the records.

**Comment by jsaintlauren** [comment]
respStmts look good to me. Thanks

**Comment by nathangibson** [comment]
OK, I will implement this for the author-saint merged records.

**Comment by nathangibson** [comment]
FYI, I've included the "Arabic name entry" respStmt after "Syriac name entry" when it exist.

**Comment by davidamichelson** [comment]
Thanks Nathan!
