### ISSUE TITLE
Changing URI for seriesStmt for Gateway to the Syriac Saints to  http://syriaca.org/saints

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#140]
Sorry to bother you again on related topic. I see now that the URI in our seriesStmt is wrong in all records.

For:

`````` <seriesStmt>
                <title level="s">Gateway to the Syriac Saints</title>
              ...
                <idno type="URI">http://syriaca.org/saints</idno>```

The URI should be http://syriaca.org/saints not http://syriaca.org/q as it currently reads. Will I break anything if I change this in all records?

FYI @nathangibson 
``````

**Comment by davidamichelson** [comment]
To clarify, I can make the change once you confirm I wont mess any xquery up that depends on this URI

**Comment by wsalesky** [comment]
It may, but I can fix it. I will be doing some work tonight, so I should be able to get to it after 8ish.

**Comment by wlpotter** [comment]
Unsure if this was fixed, but it will be resolved by @dlschwartz and my updates to all persons' seriesStmts, so closing in favor of #1012 #1013 etc.
