### ISSUE TITLE
Break up the Stephens 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#145]
This record for http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1709 includes a Stephen from Palladius and also St. Stephen the first martyr 

And Stephen the first martyr is commemorated also in this Q record - http://syriaca.org/person/1710 

So it all needs to be cleaned up -

**Comment by davidamichelson** [comment]
Hi J-N, it looks like there is also a Stephen who is person/1711, shall we merge him with 1710?

**Comment by jsaintlauren** [comment]
Yes, please merge

**Comment by wlpotter** [comment]
https://syriaca.org/person/1709 is the Stephen from Palladius. https://syriaca.org/person/1710 and https://syriaca.org/person/1711 I think are both the proto-martyr? The latter have not been merged yet.

There are a number of works listed as commemorating https://syriaca.org/person/1709 that should be for https://syriaca.org/person/1711:

- https://syriaca.org/work/708
- https://syriaca.org/work/709 (already in https://syriaca.org/person/1711)
- https://syriaca.org/work/954
- https://syriaca.org/work/1155
- https://syriaca.org/work/1191
- https://syriaca.org/work/1284
- https://syriaca.org/work/1466
- https://syriaca.org/work/1557
- https://syriaca.org/work/1706
- https://syriaca.org/work/1764

There are some that I think _most likely_ commemorate the proto-martyr but I cannot tell for sure

- https://syriaca.org/work/1105
- https://syriaca.org/work/1243
- https://syriaca.org/work/1680
- https://syriaca.org/work/1724
- https://syriaca.org/work/2039

And two others that are probably for the proto-martyr, but their records don't have much to go on...

https://syriaca.org/work/2021
https://syriaca.org/work/1527

**Comment by wlpotter** [comment]
Also cf #36 as we have a work (https://syriaca.org/person/1943) to add to Stephen the protomartyr once 1711 and 1710 have been merged.

**Comment by wlpotter** [comment]
In the above list in [this comment](https://github.com/srophe/srophe-app-data/issues/145#issuecomment-990981307), all the work URIs commemorate the proto-martyr and should be moved to 1710/1711 once they're merged. Check that each work record is commemorating the right Stephen as well.

**Comment by wlpotter** [comment]
Collecting the changes needed from #36 so I can update Stephen records in one go.

- add attestation of Stephen (1711) in work 882
- change commemorating relationship of work 882 to point to 1711
