### ISSUE TITLE
Pseudo Author/Saints

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#152]
@davidamichelson @jsaintlauren @dlschwartz 
What should we do with persons 423 (Clement, https://github.com/srophe/persons/blob/master/new-saints-data/overlap/423.xml) and 452 (Dionysius, https://github.com/srophe/persons/blob/master/new-saints-data/overlap/452.xml), whom we left out of the authors guide because they are pseudonymous? They are in the folder of saints to merge with authors, but we don't have any author records to merge them with. Perhaps we would have to get the author data from the spreadsheet? Or should we put them in just as saints and not as authors?

**Comment by jsaintlauren** [comment]
Let's just put them in as saints and not authors.Thanks

**Comment by nathangibson** [comment]
Note to self: Include overlap person 635 in this group.
