### ISSUE TITLE
overlap saint-author 886

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#154]
@jsaintlauren In our author-saint overlap folder, we have this record (https://github.com/srophe/persons/blob/master/new-saints-data/overlap/886.xml) for an "Ithalāhā". However, the author record that supposedly corresponds (http://wwwb.library.vanderbilt.edu/person/886) is for ʿEqebshma. Is this a mistake. Is the Ithalaha author instead one of the ones that shows here: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=ithal* ?

**Comment by nathangibson** [comment]
@jsaintlauren This is the last merge from the overlapping saints-authors folder. Let me know what you think.

**Comment by jsaintlauren** [comment]
Yes,it must be I think.  But I don't know from the data in 886 which one of
Itallaha it is..

**Comment by nathangibson** [comment]
Ahh, I think I know. The overlap record was wrongly labeled as person/886 which is a record for an ʿEqebshma. Ithalaha the deacon (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1291) was martyred with a  Bishop ʿAqewshma (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1135). So probably this overlap record refers to the Italaha martyred with Aqewshma. Should we merge the overlap record with person/1135?

**Comment by nathangibson** [comment]
I mean merge the overlap with person/1291

**Comment by jsaintlauren** [comment]
Yes merge 1291 please with 1135.  @nathangibson
