### ISSUE TITLE
Abi (person/1536)

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#155]
@jsaintlauren  I assume it's OK to merge this record (https://github.com/srophe/persons/blob/master/new-saints-data/overlap/1093.xml) (mistakenly in the saints-authors overlap folder?) with http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1536? Both cite BHS 596 as their source.

**Comment by jsaintlauren** [comment]
DO NOT MERGE -- they are not the same.  They are different saints.  BHS 596 refers to person 1536 alone.  I have removed the BHS ref from person 1093.  Both are saints.  Thanks!
