### ISSUE TITLE
Ahudemmeh of Balad (person/67)

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#156]
@jsaintlauren Hopefully the last identification question from the author-saint overlap folder!
This record (https://github.com/srophe/persons/blob/master/new-saints-data/overlap/67-or-325.xml) should be merged with http://wwwb.library.vanderbilt.edu/person/67, right? (Not with https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/325.xml ?)

**Comment by jsaintlauren** [comment]
Yes - his hagiography called him apostle to arabs.  But biographically he was maphrian - so 67 and 325 should be merged.  Ahudemmeh of Tagrit is someone else (it is confusing) -

**Comment by nathangibson** [comment]
I'm still confused :-)

Ahudemmeh of Tagrit (just "Ahudemmeh" in GEDSH) is http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/325 , right? 

And Ahudemmeh of Balad is http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/67 , right? 

These two are already correctly distinguished in SBD, right?

So which one should https://github.com/srophe/persons/blob/master/new-saints-data/overlap/67-or-325.xml be merged with? It sounds like you're saying it should be merged with person/67 ?

**Comment by nathangibson** [comment]
@jsaintlauren Let me know what you think when you have a chance.

**Comment by jsaintlauren** [comment]
Yes, person 67.. Ahudemmeh of Balad has a hagiographic tradition; the other
does not.  I have a chapter on Ahudemmeh of Balad in my book :).

**Comment by nathangibson** [comment]
Cool :-). So I'll merge the overlap record https://github.com/srophe/persons/blob/master/new-saints-data/overlap/67-or-325.xml with person/67

**Comment by nathangibson** [comment]
Done
