### ISSUE TITLE
move Cain out of Q into SBD alone 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#157]
PLease move Cain to the SBD but out of Qadishe.

http://syriaca.org/person/1635 
here is the csc 
Cain	http://www.csc.org.il/db/browse.aspx?db=SB&sL=C&sK=Cain&sT=keywords

**Comment by davidamichelson** [comment]
And Cain went out from the presence of the LORD, and dwelt in the land of
Nod, on the east of Eden.

**Comment by jsaintlauren** [comment]
We could house all the villains of Syriac tradition in a module called "Nod."

**Comment by davidamichelson** [comment]
Okay, I did it, see this link for a review of what might need to happen if
you wanted to remove a record from Q in the future:
https://github.com/srophe/srophe-app-data/commit/c82dfc776117851d1b80fece90032f01518c5167

**Comment by davidamichelson** [comment]
@wsalesky The Dev branch does not seem to have pushed to the dev server on this one. Did I do something wrong?
