### ISSUE TITLE
ʿEnanishoʿ?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#158]
I can't seem to find a person record for ʿEnanishoʿ (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bibl/204)

See:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=%CA%BFEnanisho%CA%BF

Any ideas?

**Comment by nathangibson** [comment]
You mean http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/474 <http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/474>, right? Clicking your search link turns him up for me. Maybe it was a caching problem?

**Comment by davidamichelson** [comment]
How odd, maybe the Exist-DB was being reindexed at that moment. These all work for me now.

**Comment by wsalesky** [comment]
I reloaded all the data, sometimes the webhooks fail, this way we are up to date.
