### ISSUE TITLE
duplicates in Q 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#171]
Please see the duplicates here:
https://docs.google.com/spreadsheets/d/1ZDHbNR812CXv2_Jbkhvb6Rn1nuuPRJbg-u3tIJrZLtk/edit#gid=0 
Delete the record with the less fulsome/less accurate record.  Thank you

**Comment by nathangibson** [comment]
I’ve been planning to do the merges in that spreadsheet soon. However, can you take a look at the ones with notes beside them and confirm whether these are actually duplicates?

**Comment by nathangibson** [comment]
Turned the 2 with notes into issues.
