### ISSUE TITLE
Display issue for Š in person/958

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#179]
In both Firefox and Safari on Mac, the Š in name958-10 (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/958) is showing up as a "?". Is this a personal font issue on my computer or an XSLT problem? The Š is showing up fine when I browse the code in Firefox.

![st__eusebius_of_samosata_](https://cloud.githubusercontent.com/assets/3083452/15575375/cd07d91c-2352-11e6-8db4-268c1c62114c.jpg)

**Comment by nathangibson** [comment]
It is also showing up correctly at http://wwwb.library.vanderbilt.edu/work/383.

**Comment by wsalesky** [comment]
@davidamichelson Do you have any problems with this? I checked Firefox, Chrome and Safari and it shows up for me. Not sure what could be causing this.

**Comment by nathangibson** [comment]
It shows up correctly for me now. Weird.
