### ISSUE TITLE
Cyriacus

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#188]
Hi @jsaintlauren, I see you prefer the anglicized Cyriacus for this person, but since it is spelled with a Q in syriac, should we use Quryaqos instead as the name to sort it by for browsing?? In this case, I am worried the English form is too different. What do you think?

http://wwwb.library.vanderbilt.edu/person/145

**Comment by jsaintlauren** [comment]
Please keep it as Cyriacus.

**Comment by jsaintlauren** [comment]
Please keep it as Cyriacus.
