### ISSUE TITLE
False match on http://wwwb.library.vanderbilt.edu/person/170

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#189]
It looks like this was a false match: http://wwwb.library.vanderbilt.edu/person/170. @nathangibson can you please track down the original files, separate, and merge instead the Q George of Antioch with http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/139?  @jsaintlauren can you confirm please that the Saint currently at 170 should be at 139 instead?

**Comment by davidamichelson** [comment]
We will need to check BHSE for any refs to 170 and update them.

**Comment by nathangibson** [comment]
OK, I've rolled back person/170.

**Comment by nathangibson** [comment]
Merged Q George of Antioch with person/139. They look like the same person to me, but if you disagree, @jsaintlauren, I can roll back.

**Comment by nathangibson** [comment]
Doesn't look like there are any BHSE refs to person/170.

**Comment by jsaintlauren** [comment]
thank you!
