### ISSUE TITLE
Inaccessible published records

### ISSUE THREAD

**Issue by tacarlson** [srophe/srophe-app-data#19]
http://syriaca.org/place/2567 was published, and the TEI record is still visible at https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/2567.xml

But when I enter the URI into my browser, it generates http://syriaca.org/place/2567.html as an empty framework of a record, and I am unable to access the Telneshe record through either search or browse (in Syriac or English).

Have I missed something?

**Comment by wsalesky** [comment]
Looks like our webhooks may be down. I will check and get that loaded for you.

**Comment by tacarlson** [comment]
The odd thing is that the record used to be accessible through the production version.  Was the eXist database reverted at some point?

**Comment by wsalesky** [comment]
Not that I know of. How long ago was it published?

**Comment by tacarlson** [comment]
The record was published 7/13/2015.

**Comment by wsalesky** [comment]
Fixed.
