### ISSUE TITLE
Gregory of Naz 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#197]
@nathangibson @davidamichelson 
Hey! Quick question.  
This record of G Naz http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1762 needs to be merged into this one: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/511 

I see all the refs to Zanetti on this record http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/511 but will the links to the BHSE also be included as attestations?  Also, he will need to be incorporated into Qadishe.  

Thanks!

**Comment by nathangibson** [comment]
@jsaintlauren Yes, we need to run a script on all the author-saint merges to link them to BHSE and vice versa. So you don't need to do anything special with this one. Thanks for noticing that.
