### ISSUE TITLE
Overwrite Zanetti authors & titles?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#207]
@davidamichelson @wsalesky @jsaintlauren 

Now that we have ptrs to bibl records in the BHSE editions, translations, and ancient versions, should we overwrite Zanetti's author and title information using our bibl record, or should we leave it as is? 

E.g., in http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/270/tei should 
```
<bibl source="#bib270-1" corresp="#bib270-7" n="2" xml:id="bib270-5">
  <author>Assemani, S. E.</author>
  <title>ASMOO 1</title>
  <ptr target="http://syriaca.org/bibl/1725"/>
  <citedRange unit="vol">1</citedRange>
  <citedRange>p. 66-79</citedRange>
</bibl>
```
become 
```
<bibl source="#bib270-1" corresp="#bib270-7" n="2" xml:id="bib270-5">
  <title level="m">Acta sanctorum martyrum Orientalium et Occidentalium in duas partes distributa, adcedunt Acta S. Simeonis Stylitae</title>
  <ptr target="http://syriaca.org/bibl/1725"/>
  <citedRange unit="vol">1</citedRange>
  <citedRange>p. 66-79</citedRange>
</bibl>
```
?
This is related to the question of how we want our stylesheet to display the HTML. If we have it ignore the author/title in the work record and pull in the info from the bibl record, then we wouldn't need to overwrite Zanetti's author/title. However, I also don't see any particular reason to keep Zanetti's info now. (Of course we will keep any citedRange and note elements regardless.)

**Comment by wsalesky** [comment]
The display only uses the citedRange info from the person record, all the other information for the bibl display is pulled from the canonical bibl record (if a ptr exists). Does that help?

**Comment by nathangibson** [comment]
That does help, because it means this issue only affects what we want the underlying data to look like, not the display. 
However, this does not seem to be currently pulling the bibl records for editions/translations/ancient versions.
In addition to citedRange, will it also display `<note>` items?

**Comment by wsalesky** [comment]
Hum. I will take a look. I'm not sure about notes, I suspect we suppressed some notes.

**Comment by nathangibson** [comment]
OK, we should maybe discuss the value of displaying notes at one of our team meetings.

**Comment by wsalesky** [comment]
Hum, I have a rule in the xslt to display just the content of the note/bibl with a link to the bibl record. I will change that.

**Comment by nathangibson** [comment]
Leave the original Zanetti data, but see if someone can clean up citedRange

**Comment by davidamichelson** [comment]
Okay, there is a related issue here on notes in bibls. We need to visualize in the HTML the notes that are inside Bibls. For example: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/bhse/search.html?q=Partielle See how the word Partielle is in a note in http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/921 but not visualized.
