### ISSUE TITLE
Possible idno mismatch?

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-app-data#209]
Noticed while working on bibl display for editions/translations/ancient. 
See: 
http://wwwb.library.vanderbilt.edu/work/270

References (in editions) http://syriaca.org/bibl/1697
There is no record with this idno. bibl/1697.xml has idno = 'http://syriaca.org/bibl/1698'

**Comment by nathangibson** [comment]
Thanks for catching this! Just fixed it.
