### ISSUE TITLE
Namespaces

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-app-data#22]
@davidamichelson @dlschwartz 
Namespaces need to be added to SPEAR XML for snap, possibly for others as well. Will list here as I find them.

**Comment by dlschwartz** [comment]
I believe I've address all the problems we discussed in our meeting. I could not, however, find the use of relation name="correspondent" which I think you mentioned Winona. Anyway, it does not appear in the data I just committed on github. Please let me know if you think I've missed something.

**Comment by wsalesky** [comment]
I wonder if I was using an old version of the data. I will update my local copies. Thanks!

**Comment by dlschwartz** [comment]
Thanks. That reminds me. What I had used a while back to push from git to the dev server no longer works. Dashboard, I think it was. Perhaps we can get that sorted next week too.

**Comment by wsalesky** [comment]
Okay. Put it in the meeting notes.

**Comment by dlschwartz** [comment]
Will do. Thanks.
