### ISSUE TITLE
Merging in Bibl URIs to Persons Records

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#228]
@wsalesky well alas I still couldn't get my script to work. Could you please try and fix it for me? I can check in with you tomorrow AM if needed. The files are:

script: https://github.com/srophe/persons/blob/master/working-files/Merging-Bibliography-Into-Q/Fiey-Bibl-Insert.xq

zoteroid: https://github.com/srophe/persons/blob/master/working-files/Merging-Bibliography-Into-Q/zoteroid.xml

you will also need to point the script at https://github.com/srophe/srophe-app-data/tree/dev/data/bibl/tei and https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/saints/tei

The end result should be to insert the bibl URIs into the bibl elements in the persons records.

Thus:

this (https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/saints/tei/1118.xml#L215-L218):
```
     <bibl xml:id="bib1118-3">
                        <title>AMS</title>
                        <citedRange>I, 51-52</citedRange>
                    </bibl>
```
Should become:
```
     <bibl xml:id="bib1118-3">
                        <title>AMS</title>
                        <ptr target="http://syriaca.org/bibl/1697"/>
                        <citedRange>I, 51-52</citedRange>
                    </bibl>
```

**Comment by davidamichelson** [comment]
@wsalesky I am not sure the script worked as I intended. see https://github.com/srophe/srophe-app-data/blob/issue229/data/persons/tei/saints/tei/1118.xml#L215-L218

**Comment by wsalesky** [comment]
List:
http://syriaca.org/person/1525/tei http://syriaca.org/person/1513/tei
    http://syriaca.org/person/1497/tei http://syriaca.org/person/1496/tei
    http://syriaca.org/person/1183/tei http://syriaca.org/person/1495/tei
    http://syriaca.org/person/1489/tei http://syriaca.org/person/1454/tei
    http://syriaca.org/person/1436/tei http://syriaca.org/person/1420/tei
    http://syriaca.org/person/1418/tei http://syriaca.org/person/1415/tei
    http://syriaca.org/person/1393/tei http://syriaca.org/person/1384/tei
    http://syriaca.org/person/1382/tei http://syriaca.org/person/1379/tei
    http://syriaca.org/person/1370/tei http://syriaca.org/person/1358/tei
    http://syriaca.org/person/1350/tei http://syriaca.org/person/1348/tei
    http://syriaca.org/person/1329/tei http://syriaca.org/person/1323/tei
    http://syriaca.org/person/1322/tei http://syriaca.org/person/1308/tei
    http://syriaca.org/person/1302/tei http://syriaca.org/person/1301/tei
    http://syriaca.org/person/1297/tei http://syriaca.org/person/1296/tei
    http://syriaca.org/person/1280/tei http://syriaca.org/person/1262/tei
    http://syriaca.org/person/1258/tei http://syriaca.org/person/1254/tei
    http://syriaca.org/person/1200/tei http://syriaca.org/person/1194/tei
    http://syriaca.org/person/1192/tei http://syriaca.org/person/1178/tei
    http://syriaca.org/person/1175/tei http://syriaca.org/person/1171/tei
    http://syriaca.org/person/1168/tei http://syriaca.org/person/1166/tei
    http://syriaca.org/person/1162/tei http://syriaca.org/person/1159/tei
    http://syriaca.org/person/1157/tei http://syriaca.org/person/1155/tei
    http://syriaca.org/person/1154/tei http://syriaca.org/person/1152/tei
    http://syriaca.org/person/1148/tei http://syriaca.org/person/1129/tei
    http://syriaca.org/person/1119/tei http://syriaca.org/person/1118/tei
    http://syriaca.org/person/1113/tei http://syriaca.org/person/1108/tei
    http://syriaca.org/person/1105/tei http://syriaca.org/person/1100/tei
    http://syriaca.org/person/1099/tei http://syriaca.org/person/1098/tei
    http://syriaca.org/person/1097/tei http://syriaca.org/person/1473/tei
    http://syriaca.org/person/1330/tei http://syriaca.org/person/1518/tei
    http://syriaca.org/person/1253/tei http://syriaca.org/person/1250/tei
    http://syriaca.org/person/1233/tei http://syriaca.org/person/1475/tei
    http://syriaca.org/person/1430/tei http://syriaca.org/person/1365/tei
    http://syriaca.org/person/1356/tei http://syriaca.org/person/1349/tei
    http://syriaca.org/person/1271/tei http://syriaca.org/person/1257/tei
    http://syriaca.org/person/1203/tei http://syriaca.org/person/1240/tei
    http://syriaca.org/person/1524/tei http://syriaca.org/person/1509/tei
    http://syriaca.org/person/1493/tei http://syriaca.org/person/1471/tei
    http://syriaca.org/person/1409/tei http://syriaca.org/person/1398/tei
    http://syriaca.org/person/1385/tei http://syriaca.org/person/1320/tei
    http://syriaca.org/person/1284/tei http://syriaca.org/person/1260/tei
    http://syriaca.org/person/1242/tei http://syriaca.org/person/1232/tei
    http://syriaca.org/person/1150/tei http://syriaca.org/person/1142/tei
    http://syriaca.org/person/1123/tei http://syriaca.org/person/1094/tei
    http://syriaca.org/person/1616/tei http://syriaca.org/person/1399/tei
    http://syriaca.org/person/1341/tei http://syriaca.org/person/1122/tei
    http://syriaca.org/person/1109/tei

**Comment by davidamichelson** [comment]
Hi Winona,

Okay, I could use your help please to write some scripts to run on the person records to clean them up.

We can go over the script details tomorrow. As a reminder for myself:
1. Split and parse the author names into persName with forename and surname based on initials
2. Create a list of distinct values of surname and titles
3. Compare that list with the Zoteroid file and let us know the ones that do not match.

Thanks,
Dave

**Comment by wsalesky** [comment]
Gist for updating author names:
https://gist.github.com/wsalesky/53bad184a00a1f97e0548224468cafbf

**Comment by wsalesky** [comment]
You can run the following xquery to get a full list of distinct titles and authors:

```
distinct-values(
for $b in collection('/db/apps/srophe-data/data/persons/tei')//tei:bibl
let $title := $b/tei:title[1]/text()
let $author := $b/tei:author[1]/text()
return concat($title,' ', $author))
```

**Comment by davidamichelson** [comment]
Okay,  the Gist for updating author names works:
https://gist.github.com/wsalesky/53bad184a00a1f97e0548224468cafbf works, but I cannot get the script for matching to work: https://github.com/srophe/persons/blob/master/working-files/Merging-Bibliography-Into-Q/Fiey-Bibl-Insert.xq

I did update the path to match on tei:surname but no luck.

Could you fix it please?

thanks,
Dave

**Comment by davidamichelson** [comment]
For my own reference here is what else will need to happen on this issue:

Could you please do the following 3 that are marked with WS?

- Run the name clean up script (WS)
- Run the ptr matching script (WS)
- Run the distinct-values script and send me the result as a GIST (WS)
- Clean up data (DM)
- Run the ptr matching script again (WS)
- Work out how to run it on Multi-volume items (DM)

**Comment by wsalesky** [comment]
Sorry @davidamichelson can you clarify which scripts you are referring to? I think I have too many update scripts running around my laptop. 

Thanks. I should have some time tomorrow early afternoon to work on these.

**Comment by davidamichelson** [comment]
:) No problem, just to be clear, ignore the note that is for my own reference. What I am asking for you run is as follow:

Please run this script for cleaning up names with initials (on the Saints records, all 1041 of them):
https://gist.github.com/wsalesky/53bad184a00a1f97e0548224468cafbf 

Then please run the script for matching URIS and inserting them into Person records: https://github.com/srophe/persons/blob/master/working-files/Merging-Bibliography-Into-Q/Fiey-Bibl-Insert.xq

Then please send me a gist of the distinctvalues for all bibls that still don't have a ptr after the script is run:

You started the script above, but it needs to run only on bibls without ptr elements in the person records:

distinct-values(
for $b in collection('/db/apps/srophe-data/data/persons/tei')//tei:bibl
let $title := $b/tei:title[1]/text()
let $author := $b/tei:author[1]/text()
return concat($title,' ', $author))

Thanks!

**Comment by wsalesky** [comment]
Here is the list of distinct titles and authors from the records without ptrs. 
La liste martyrologique des textes du Guria et Shamona 
Histoire ecclesiastique 
Sainte Sirin 
Mossoul chretienne 
Machriq 
Nisibe 
Asceticism 
Qiṣṣat Mār Ilīyā 
La lettre apologetique d'Elie a Leon 
Eliae epistula apologetica ad Leonum, Syncellum harranensem 
Saint Eliān de Ḥimṣ 
Welcoming Foreign Saints to the Church of Syrian Antioch 
AB 42 
Coptes et Syriaques, contacts et echanges 
Vies de saints 
Dioceses 
Monk and Mason 
Chretiens syriaques 
Holy Women 
AMSO 
Catalogue Voste 
Quelques observations litteraires et historiques sur la vie syriaque de Mār Aḥā 
AS 
Orient et Occident 
S. Ephraem Syri hymni et sermones 
Résumé 
Kitāb al-maǧdal 
Nisibis 
OS 11 
Šuhadā‘ 
Hist. eccl. 
Passion arménnienne 
Rehabilitation 
La diffusion orientale de la légende des saints Cosme et Damien 
A Treatise on the Unity and Trinity of God 
A Saint and his Biographer in Late Antique Iraq: The History of St George of Izla († 614) by Babai the Great 
Stephen of Ephesus ( 448) and the Legend of the Seven Sleepers 
Opera Minora of L. Massignon 
La tradition des Sept Dormants 
La legende des Sept Dormants d'Ephese selon le Codex syriaque N.S. 4 de Saint-Petersbourg 
Auszüge 
Une Note de Severe d'Antioche sur Juda Cyriaque 
Piecing Together the Fragmentary Account of the Martyrdom of Cyrus of Harran 
Eveques et eveches 
Rabban Buya de Shaqlawa et de Jericho 
PdO 2 
Ma'īn 
Die Legende von Mar Behnam 
Die Behnam-Legende 
Barsauma of Nisibis and Persian Christianity in the Fifth Century 
La légende de Mar Bassus 
Baršabba 
Bar Shabba/Mār Shabba, First Bishop of Merv 
Documents 
Les actes de Scharbil et de Barsamya 
Histoire d'Edesse 
Barsamyā, Märtyrer in Edessa 
'Die Personennamen in den Akten der edessenischen Märtyrer Šarbēl und Bar Sāmyā' 
Antioche 
Actes 
Panegyrici in Babylam martyrem 
Saint 'Azīza et son village de Zérīni 
Resume 
Saints 
Le saint comme symbole 
Revue sémitique 
Le sanctoral copte 
Histoire des coptes d'Egypte 
Devos 
La vie ancienne de S. Symeon Stylite le Jeune 
Revue patriarcale 2 
Fenqitho 
Lu'lu 2 
Vie des saints 
E. Key Fowden 
Anecdota Syriaca 
Lives 
Muséon 
Vies des saints IV 
Der Katholikos-Patriarch Sabrisho' I und das Monchtums 
JA 
Catalogue 
Lu 'lu ' 2 
Acts of S. George 
Holy Horsemen and Crusader Banners: Equestrian Saints in Wall Paintings in Lebanon and Syria 
"Legends, Places and Traditions Related to the Cult of Saint George in Lebanon" 
The Acts of St. George and the Story of his Father from the Syriac and Garshuni Versions 
Eine unbekannte Version der Georgios-Legende aus Turfan 
A Newly Discovered Wall Painting in the Church of Mar Giworgis in Qaraqosh, Iraq" 
"Khidr and the Politics of Translation in Mosul: Mar Behnam, St George and Khidr Ilyas" 
Summary of the dossier in DHGE

**Comment by wsalesky** [comment]
This is for the data here: https://github.com/srophe/srophe-app-data/tree/issue228

**Comment by davidamichelson** [comment]
Thanks, I will look at this tomorrow!

**Comment by davidamichelson** [comment]
Okay, there is a small flaw in the distinct values script. It should run on the author/surname element not tei:author since that now has no textnode. (Thus there are no author names in the list above.) Could you please rerun and post both the script and the results as gists? Thanks!

**Comment by wsalesky** [comment]
Okay, new data is up. 
https://github.com/srophe/srophe-app-data/tree/issue228

Also here is the gist with title/authors:
https://gist.github.com/wsalesky/d417069fed7ed445aaa94fc4cc13a47a

**Comment by wsalesky** [comment]
Hum, just checked the data. There seems to be an issue with the way it is matching. I will work on it tomorrow.

**Comment by davidamichelson** [comment]
Okay, when you run the script please use the updated persons data and also the updated zoteroid.xml file found here: https://github.com/srophe/persons/blob/master/working-files/Merging-Bibliography-Into-Q/zoteroid.xml

**Comment by wsalesky** [comment]
Okay updated data on branch 
https://github.com/srophe/srophe-app-data/tree/issue228

and updated gist. 

https://gist.github.com/wsalesky/d417069fed7ed445aaa94fc4cc13a47a

**Comment by davidamichelson** [comment]
Thanks, do you ever sleep?

**Comment by davidamichelson** [comment]
Hmm, it seems to be adding the revisionDesc/change statement more than once in some documents, see https://github.com/srophe/srophe-app-data/blob/a95f525f4295aeb2bffb5a43ef94f0300a500830/data/persons/tei/106.xml#L210-L215

**Comment by davidamichelson** [comment]
Great news, it looks like the ptrs went in as expected.

**Comment by davidamichelson** [comment]
Okay, so there are a few in the Zoteroid file and also in the distinct values results that should have matched and seem to have exact strings, any ideas? Does the distinct values normalize whitespace or do something else that is keeping me from seeing why they don't match?

See these examples:
https://github.com/srophe/persons/blob/master/working-files/Merging-Bibliography-Into-Q/zoteroid.xml#L823-L824 (Palmer, Monk and Mason)
should have matched on
https://github.com/srophe/srophe-app-data/blob/issue228/data/persons/tei/saints/tei/1505.xml#L207

It did match in several other places but not there.

Any ideas?

**Comment by wsalesky** [comment]
It took me a while, but I think I figured it out. The insert tries to insert the new ptr before the citedRange. If there is no citedRange it fails silently. So I will have to write a test for that. 
I can rerun it later this afternoon, or evening.

**Comment by davidamichelson** [comment]
Hmm, I didn't find that to be the case, are there records without a ptr or
a citedRange?

**Comment by wsalesky** [comment]
Do you have any other record numbers that did not match? That I can test on?

**Comment by wsalesky** [comment]
Updated data on branch https://github.com/srophe/srophe-app-data/tree/issue228

**Comment by davidamichelson** [comment]
Oops I forgot to update the Zoteroid file will do it tomorrow

**Comment by davidamichelson** [comment]
Okay the new zoterioid file is up.

**Comment by wsalesky** [comment]
Okay. Let me try rerunning it now.

**Comment by wsalesky** [comment]
Okay, new data:
https://github.com/srophe/srophe-app-data/tree/issue228

**Comment by davidamichelson** [comment]
Thanks! I will check later this afternoon.

**Comment by davidamichelson** [comment]
Hi W, I think I am ready to return to this. Sorry it sat so long, can you look through the list and tell me which of the links above are of the latest version of the two scripts?

name clean up script (WS)
ptr matching script (WS)

Would you have time to run them on a new branch off dev and I will look at them and merge if they are clean.

thanks!

**Comment by wsalesky** [comment]
I can run them tonight. I will have to double check, but I think these are the latest versions of the scripts: 

Name cleanup:
https://github.com/srophe/srophe-xQueries/blob/master/split-bibl-authors.xql

ptr matching:
https://github.com/srophe/srophe-xQueries/blob/master/match-bibl-name-to-zotero-name.xql

**Comment by wsalesky** [comment]
Okay, new version of the data is on this branch:
https://github.com/srophe/srophe-app-data/tree/issue228-july-27

**Comment by davidamichelson** [comment]
Great, do you know if the script version you ran was the one that included a fix based on the problem you described above about "The insert tries to insert the new ptr before the citedRange. If there is no citedRange it fails silently. So I will have to write a test for that. "

**Comment by wsalesky** [comment]
Yes, it does.

**Comment by davidamichelson** [comment]
Sorry, I think I may have forgotten to give you an updated version of the zoteriod.xml file. Could you send me a gist or link of the one you used?

**Comment by wsalesky** [comment]
https://github.com/srophe/persons/blob/master/working-files/Merging-Bibliography-Into-Q/zoteroid.xml

**Comment by davidamichelson** [comment]
Thanks!

**Comment by davidamichelson** [comment]
Okay, that was the latest version. I am going to merge this data and then revise the zoteroid file to fix the outliers. Let's keep this issue upon for now.

**Comment by davidamichelson** [comment]
Okay, now I am trying to run the script for distinct values you wrote: 
https://gist.github.com/wsalesky/d417069fed7ed445aaa94fc4cc13a47a#file-distinct-title-author-xql
And I cannot figure out how to get the results in a file?
I tried this:
https://gist.github.com/davidamichelson/d098847f12b837c1ad266d6e74359b82
What am I doing wrong?

**Comment by wsalesky** [comment]
Hum, are you running it in eXide?

**Comment by wsalesky** [comment]
Looks like you can not stream from eXide. You can save it to the db and
then run it though.

**Comment by davidamichelson** [comment]
@wsalesky Okay could we run a new version of the zoteroid.xml file please? I have uploaded the new file (newzoteroid.xml) here: https://github.com/srophe/persons/blob/master/working-files/newzoteroid.xml

As we discussed a while back this one has some zotero ids repeated, but that should not affect the script, correct? See lines https://github.com/srophe/persons/blob/master/working-files/newzoteroid.xml#L28-L46

Could you run it on a branch please and remind me where the script is so I can run the next round.

thanks!

**Comment by wsalesky** [comment]
Scripts: 
Name cleanup:
https://github.com/srophe/srophe-xQueries/blob/master/split-bibl-authors.xql

ptr matching:
https://github.com/srophe/srophe-xQueries/blob/master/match-bibl-name-to-zotero-name.xql

New data:
https://github.com/srophe/srophe-app-data/tree/issue228-July-31
