### ISSUE TITLE
Fiey/Zanetti bibls reversed in Qadishe

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#23]
@wsalesky @jsaintlauren @davidamichelson Looks to me like we have an issue on several/all (?) saints records where elements in Qadishe cite the wrong bibl in the source attribute. E.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1200. 

Usually/always (?) Zanetti BHS is bibl 1, and Fiey, Saints Syriaques is bibl 2. But the source attributes are reversing this, citing Zanetti instead of Fiey, and vice versa. 

One possible way to check whether this affects all records is to check the source attribute on the names that have xml:lang="fr-x-zanetti" (should cite Zanetti) and xml:lang="fr-x-fiey" (should cite Fiey).

**Comment by wsalesky** [comment]
If they are wrong in some then I think they are wrong in all, I believe the order was hardcoded into the xslt. :( My bad.

**Comment by nathangibson** [comment]
OK, there seem to be 127 occurrences of persNames that mistakenly cite Zanetti instead of Fiey (try the xpath `//persName[@xml:lang='fr-x-fiey' and replace(@source,'#','')=../bibl[ptr/@target='http://syriaca.org/bibl/649']/@xml:id]` ). Almost all of these records also have a persName marked xml:lang="fr-x-zanetti", which probably cites Fiey instead of Zanetti. In other words the values of the source attributes need to be swapped. 

However, other elements may be mis-sourced (sex, death, ...?), and we need to do more investigation to figure out if it is safe to simply replace all x with y and all y with x for these records.

This should probably happen before I merge too many of the author/saint overlaps, as the merges might make these more difficult to correct. 

I will assign this to myself, but @wsalesky if you get time before I do, your help is welcome. We can discuss tonight if that helps.

**Comment by nathangibson** [comment]
@wsalesky @davidamichelson @jsaintlauren 
I think I've fixed this now. I've run some tests and haven't found any more instances of this. Let me know if you find any.
