### ISSUE TITLE
Awida http://syriaca.org/person/1146 needs revision of abstract

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#236]
<idno xmlns="http://www.tei-c.org/ns/1.0" type="URI"
          >http://syriaca.org/person/1146/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1146-2" xml:lang="en"
          >Awida</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract"> In hagiography: Awida was a
          Persian confessor whose ears and nose were cut off; he had wanted to follow Yasdapnah to
          martyrdom.</note>

**Comment by jsaintlauren** [comment]
Not sure what the issue here is..

**Comment by davidamichelson** [comment]
Hmm, good quesiton. I think I wondered if the part: he had wanted to follow Yasdapnah to
martyrdom is too vague without any sort of link to Yasdapnah. Do we have a URI for Yasdapnah or could you explain who that is?

**Comment by jsaintlauren** [comment]
fixed
