### ISSUE TITLE
Please check names of person http://syriaca.org/person/1165

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#240]
<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1165/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1165-2" xml:lang="en">Bar
          Shewya</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract"> In hagiography: Bar Ŝewya or Bar
          Shabba was a solitary and first Bishop of <placeName ref="http://syriaca.org/place/607">Merv</placeName>; he was deported from Byzantine territory
          to <placeName ref="http://syriaca.org/place/58">Ctesiphon</placeName>. The sister or wife of Shapor, Shirawan, became Christian and built a church
          there which Bar Shabba consecrated.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
treating this in another issue already
