### ISSUE TITLE
Needs Splitting: http://syriaca.org/person/1167 Bassus and           Suzanne, with Stevin and Longinus

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#241]
<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1167/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1167-2" xml:lang="en">Bassus and
          Suzanne, with Stevin and Longinus</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract"> In hagiography: Bassus and his
          twin sister Shushān were twin children of a Zoroastrian governor. They were informed about
          Christianity by a Christian slave. They were baptized by an ascetic named Longinus. They
          were killed by their father. A monastery was built in their honor near Apamea.</note>
      </tei:div>

**Comment by davidamichelson** [comment]
A related one is here: <tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI"
          >http://syriaca.org/person/1492/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1492-2" xml:lang="en"
          >Suzanna</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Bassus and his
          twin Suzanna were twin children of a Zoroastrian governor. They were informed about
          Christianity by a Christian slave. They were baptized by an ascetic named Longinus. They
          were killed by their father. A monastery was erected in their honor near Apamea.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
added the persName refs to 1167 and 1492 - need new URIs for Stephen and Longinus
