### ISSUE TITLE
Is Damian of Alexandria commemorated as a saint?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#250]
See <tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1196/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1196-2" xml:lang="en">Damian, patriarch of Alexandria</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract"> In hagiography: Damian was
          patriarch of <placeName ref="http://syriaca.org/place/572">Alexandria</placeName>. He sent a letter to <persName ref="http://syriaca.org/person/69">Jacob Baradaeus</persName> hoping for communion between
          the churches. He visited <placeName ref="http://syriaca.org/place/10">Antioch</placeName> but broke from the Patriarch of Antioch, <persName ref="http://syriaca.org/person/75">Peter of
          Callinicus</persName>, because of the Tritheist controversy. This schism ended with the patriarchate
          of <persName ref="http://syriaca.org/person/88">Athanasius I Gamolo</persName>.</note>
      </tei:div>

Or is he just mentioned in hagiography

**Comment by jsaintlauren** [comment]
He is saint
