### ISSUE TITLE
Please merge: http://syriaca.org/person/2432 and  http://syriaca.org/person/1209/tei

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#253]
If they are the same.

**Comment by nathangibson** [comment]
@dlschwartz Is http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2263 also the same?

**Comment by jsaintlauren** [comment]
Please merge 2263 and 1209 into 2432.  Please ensure that 2432 is marked for Qadishe (please check this for all these merges!)
