### ISSUE TITLE
8 Children of Ephesus

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#257]
Lots of fun stuff in this entry!!!

Some questions too:
1. Are these the same as the 7 sleepers? Should we add that as an alternate name?
2. I think the dog should get it's own saint's entry, what do you think?

<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1227/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1227-2" xml:lang="en">Children of
          Ephesus</persName>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1227-3" xml:lang="en">Eight
          Children of Ephesus</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography these children were the protagonists of a legend set in the time of the emperor Decius. Eight children of <placeName ref="http://syriaca.org/place/623">Ephesus</placeName> were placed in a cave with their dog Qitmir for 190 years. The legend dates to the middle of the fifth century.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
Yes, Qitmir should have his own entry.

**Comment by jsaintlauren** [comment]
Yes it is the same as the seven sleepers.  
Fiey says "sept" or "huit" 

So we can add that as an alternative name.

**Comment by jsaintlauren** [comment]
8 attributions in the BHSE that should be linked

**Comment by jsaintlauren** [comment]
added 7 sleepers as an alternative name-- put Qitmir (AKA Viricarius) on list for his own URI

**Comment by davidamichelson** [comment]
@jsaintlauren Okay I created Qitmir: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/3018

Also, I changed the headword for the children to Sleepers, in my mind that is more common, but if you would prefer it remain children let me know and I will change it back: see http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1227

**Comment by jsaintlauren** [comment]
Sounds good !  Qitmir should be the mascot of syriaca.org
