### ISSUE TITLE
Possible Ghost Record?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#258]
Is this a different Ephrem?

<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1228/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1228-2" xml:lang="en">Ephrem</persName>
      </tei:div>

**Comment by jsaintlauren** [comment]
Yes a ghost indeed.  
@nathangibson  please deprecate http://wwwb.library.vanderbilt.edu/person/1228
