### ISSUE TITLE
May need to be split:Eugenius and           Macarius

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#259]
Please check first as this may already have been done.

<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1231/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1231-2" xml:lang="en">Eugenius and
          Macarius</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Eugenius and
          Macarius were priests and martyrs who were decapitated.</note>
      </tei:div>

**Comment by jedwardwalters** [comment]
Seems to have been split already, so they both need to be cleaned up:
http://syriaca.org/person/1344

**Comment by jedwardwalters** [comment]
Done.
