### ISSUE TITLE
comma before date

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#26]
@nathangibson @wsalesky 
In the SBD entries resulting from Nathan's transform of this spreadsheet [https://docs.google.com/spreadsheets/d/1SZpHjRSl2wAfa_FEpsGxYq8MMUNlBTNljitZiXJOv8s/edit#gid=0](url), we are getting a comma and space appearing before the dates.

**Comment by wsalesky** [comment]
Can you link to an example page?

**Comment by dlschwartz** [comment]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2773

**Comment by wsalesky** [comment]
Thanks! Looks like an XSLT bug. I will take care of it.

**Comment by dlschwartz** [comment]
Thanks!

**Comment by dlschwartz** [comment]
I doubt it matters but just in case it does, I just found the same problem in an SBD entry that came from a different transform Nathan did, this time on persons from the Chronicle of Edessa from this spreadsheet [https://docs.google.com/spreadsheets/d/1lS-QrCtUfFr5fTQ9utaRLTbo754RJprxKJmHTDYj8SQ/edit#gid=0](url). 

The example is here: [http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2299](url)
