### ISSUE TITLE
Another possible split: Eusebona and           Apollonius 

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#260]
Please check if it has already been done.

<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1235/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1235-2" xml:lang="en">Eusebona and
          Apollonius</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Apollonius was a
          martyr with Eusebonia mentioned by Rabban Saliba.</note>
      </tei:div>

**Comment by jedwardwalters** [comment]
I think this one has already been split, they just need to be cleaned up.
See: http://syriaca.org/person/1134

**Comment by davidamichelson** [comment]
Great, please do the clean up as necessary in all of these that are already split.

**Comment by jedwardwalters** [comment]
Done
