### ISSUE TITLE
Place needed: superior monastery

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#261]
This record would perhaps make more sense if we had a place URI for the monastery could you request one from Thomas please?

<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1241/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1241-2" xml:lang="en">Gabriel</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Gabriel of the
          superior monastery was cited with Mar Abraham as a founder of the superior monastery of
          Mosul.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
Need to check Fiey's Mossoul Chretienne

**Comment by tacarlson** [comment]
We already have a place record for that monastery:

http://syriaca.org/place/661

________________________________

**Comment by jsaintlauren** [comment]
Ah! 
Perfect.

Thanks!!

**Comment by jsaintlauren** [comment]
Wilmshurst is checked out of our library and no one will return it! 
Very popular I guess! 

They are going to bill the patron if it isn’t returned!
