### ISSUE TITLE
May need to split Gayana  and Rhipsime

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#263]
<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1247/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1247-2" xml:lang="en">Gayana
          v.Rhipsime</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Diocletian fell in
          love with a young woman, Rhipsime, when he saw her picture. She lived a convent with 17
          others, and they fled to Armenia. They were captured by the king Tiridates, who tortured
          and kills Rhipsime, her teacher Gayana, and the other virgins. The king was turned into a
          boar. Gregory cured the king, and he and Armenia converted to Christianity.</note>
      </tei:div>

**Comment by davidamichelson** [comment]
Okay, here is the other record, they need cleaning up and linking: 
<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI"
          >http://syriaca.org/person/1427/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1427-2" xml:lang="en">Rhipsime,
          Gayana</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Diocletian fell in
          love with a young woman, Rhipsime, when he saw her picture. She lived a convent with 17
          others, and they fled to Armenia. They were captured by the king Tiridates, who tortured
          and killed Rhipsime, her teacher Gayana, and the other virgins. Tiridates was turned into
          a boar. Gregory cured the king, and Armenia converted to Christianity.</note>
      </tei:div>

**Comment by jedwardwalters** [comment]
Working on this

**Comment by jedwardwalters** [comment]
Done.
