### ISSUE TITLE
May need revised abstract.

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#264]
<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1248/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1248-2" xml:lang="en">George of
          the Greeks</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: George of the
          Greeks was probably called that in order to distinguish him from his predecessor.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
That is all that Fiey gives us and it is less than Peeters.

**Comment by davidamichelson** [comment]
Who was his predecessor? This doesn't make sense to me with out that.

**Comment by jsaintlauren** [comment]
I looked at calendar of Rabban Saliba, and there is no information .

**Comment by davidamichelson** [comment]
Okay, I edited the abstract to add Saliba.
