### ISSUE TITLE
Person 1259 has two different names: Tahmazgerd and Habib

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#267]
Is this right or a mix up?

<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1259/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1259-2" xml:lang="en">Tahmazgerd</persName>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1259-3" xml:lang="en">Habib</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Habib was a
          disciple of <persName ref="http://syriaca.org/person/42">Jacob of Serugh</persName>.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
This is a mix up.
Tahmazgerd (who goes with work http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1186 ) and is person 1493 in Q.

**Comment by jsaintlauren** [comment]
I think I fixed everthing

**Comment by nathangibson** [comment]
Unfortunately this looks like it is still mixed up. Do we just delete any Tahmazgerd references in person/1259 and Tahmazgerd works linking to it or is there something else that needs to be done?

**Comment by nathangibson** [comment]
OK, I think I successfully removed any Tahmazgerd references in and to person/1259. You can reopen if something different needs doing.

**Comment by jsaintlauren** [comment]
thanks
