### ISSUE TITLE
Is this person named Isaiah or Isaac of Edessa

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#269]
<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1279/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1279-2" xml:lang="en">Isaiah</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Isaac was a Bishop
          of <placeName ref="http://syriaca.org/place/78">Edessa</placeName>. He was named with the
          approval of the Persians who occupied the city. He refused to give communion to Heraclius
          on account of the emperor's support of Chalcedon.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
isaiah . fixed
