### ISSUE TITLE
Please expand or tag this abstact for Jacob, bishop of Phesilta

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#273]
<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1295/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1295-2" xml:lang="en">Jacob, bishop of Phesilta</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Jacob was a
          disciple of Jacob Baradaeus who became Bishop of the monastery of Phesilta.</note>
      </tei:div>

Was he the abbot of the monastery or a bishop or both? Thanks!

**Comment by davidamichelson** [comment]
Please add the place tags, that may help?

**Comment by jsaintlauren** [comment]
done
