### ISSUE TITLE
Job of           Adiabene Abstract

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#277]
This abstract is a tiny bit ambiguous, do you mean doctor as in medical or doctor as in teacher?

<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1324/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1324-2" xml:lang="en">Job of
          Adiabene</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Job of Adiabene was a doctor of the Syriac church.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
done
