### ISSUE TITLE
Joseph and Narsai

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#278]
is it correct that the Narsai here is not Narsai the author but this other narsai?

<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1325/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1325-2" xml:lang="en">Joseph</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Joseph was a
          disciple of <persName ref="http://syriaca.org/person/1393">Narsai</persName>. They were martyrs of <placeName ref="http://syriaca.org/place/33">Beth Garmai</placeName>.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
different Narsai - son of hte covenant and fourth c. martyr
