### ISSUE TITLE
Joseph, partiarch of Antioch

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#279]
Could we figure out from Fiey which patriarch of Antioch this is?
<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1326/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1326-2" xml:lang="en">Joseph</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Joseph was the
          patriarch of Antioch.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
added stuff
