### ISSUE TITLE
Labbe

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#282]
Would it be possible to reword this for clarity?

<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1338/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1338-2" xml:lang="en">Labbe</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Labbe is often
          identified with the biblical Apostle Thaddeus.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
I actually want to deprecate this -- it is a really confusing tradition and not necessary.  
@nathangibson please deprecate person 1338
