### ISSUE TITLE
Malus

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#284]
This one needs clarification or should be suppressed?

<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1351/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1351-2" xml:lang="en">Malus</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Malus was a martyr
          who could be the same as Miles, Bishop of Susa.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
@nathangibson  Let's deprecate 1351 - we have enough of Miles

**Comment by nathangibson** [comment]
Let me know if you want a redirect anywhere. I've just deprecated it at this point.
