### ISSUE TITLE
broken link 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#29]
This link is broken. http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1092 
Thank you!

**Comment by jsaintlauren** [comment]
I think that there are two files for that person?  Maybe that is the issue?  Thanks, Winona!

**Comment by wsalesky** [comment]
Yes, there are two files for this person. We need to resolve them and delete one of them. (One is in /persons/tei and one is in /persons/tei/saints/tei )

**Comment by jsaintlauren** [comment]
OK!  Shall I just delete one of them, or do you need to do that from your end (sorry for the stupid question)! And thanks!

**Comment by wsalesky** [comment]
You can delete it.

**Comment by jsaintlauren** [comment]
Thanks!  I can't find it in the file saved in /persons/tei .. any hints?  Thanks! And sorry.

**Comment by wsalesky** [comment]
I will take a look tonight.

**Comment by wsalesky** [comment]
Was already deleted in on github, just had to delete on the server.
