### ISSUE TITLE
Is there a record for Thecla the sister of Mar Awgin?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#295]
I can't find it though there are several records which mention her.

**Comment by davidamichelson** [comment]
Unless it is this one who was a daughter of the covenant? http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1497

**Comment by jsaintlauren** [comment]
There is not - we need a record for her.

**Comment by jsaintlauren** [comment]
I entered her into the spreadsheet
