### ISSUE TITLE
Let's discuss if Aretas needs an individual record too

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#296]
<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI"
          >http://syriaca.org/person/1391/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1391-2" xml:lang="en">Nagran,
          martyrs of</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: The martyrs of
          <placeName http://syriaca.org/place/464>Nagran</placeName>, led by <persName>Arethas</persName>, died in <placeName ref="http://syriaca.org/place/474">Ḥimyar</placeName>, condemned by <persName>Joseph</persName>, a Jewish governor.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
Yes, Arethas should have his own record.

**Comment by jsaintlauren** [comment]
Made a note to create one for him in the new person URI
