### ISSUE TITLE
Sawrisho

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#314]
Hi J-N there are several saints that Fiey transliterates as Sawrisho such as http://syriaca.org/person/1457

Should we keep that transliteration or is it a beth instead of the W or is the underlying Syriac a waw?

**Comment by jsaintlauren** [comment]
Yes Fiey's Sawrishos are elsewhere spelt Sabrisho.

**Comment by jsaintlauren** [comment]
So some will need to be merged.

**Comment by jsaintlauren** [comment]
So http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/708 should be merged with http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1456

**Comment by davidamichelson** [comment]
Okay, please leave this issue open until I can change all of them.

**Comment by nathangibson** [comment]
OK, these are merged.
