### ISSUE TITLE
Needs more information from another record

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#316]
<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI"
          >http://syriaca.org/person/1460/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1460-2" xml:lang="en"
          >Seleucus</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Seleucus, see
          Stratonike.</note>
      </tei:div>

Needs abstract and details from <tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI"
          >http://syriaca.org/person/1490/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1490-2" xml:lang="en"
          >Stratonike</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: Stratonike was the
          sister of <persName ref="http://syriaca.org/person/356">Mar Awgin</persName> and
          <persName>Thecla</persName>. She was mentioned in the <title>Hymns on the Holy Women</title>.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
This Stratonike has nothing to do with person 1490.  

Fixed records - all set!
