### ISSUE TITLE
Needs more details

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#317]
<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI"
          >http://syriaca.org/person/1461/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1461-2" xml:lang="en">Senne see
          Abdon</persName>
      </tei:div>

Needs more details from
<tei:div xmlns:tei="http://www.tei-c.org/ns/1.0">
        <idno xmlns="http://www.tei-c.org/ns/1.0" type="URI"
          >http://syriaca.org/person/1103/tei</idno>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1103-2" xml:lang="en">ʿAbdon and
          Sennen</persName>
        <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1103-3" xml:lang="en">ʿAbdon and
          Sennen</persName>
        <note xmlns="http://www.tei-c.org/ns/1.0" type="abstract">In hagiography: ʿAbdon and Sennen
          were two Persian twins martyred in <placeName ref="http://syriaca.org/place/641"
            >Rome</placeName>. Their story was contained in the martyrology of <persName
            ref="http://syriaca.org/person/1417">Bishop Polychrone</persName>, a bishop of Babylon.
          They do not figure in Syriac hagiography, but in the Latin tradition they are called
            <foreign xml:lang="la">Ciccensis adiabenicis victis</foreign>.</note>
      </tei:div>

**Comment by jsaintlauren** [comment]
fixed
