### ISSUE TITLE
Please merge?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#319]
Seems likely to me:

Pachomius - Ascetikon - ܦܟܘܡܝܣNames: PāḵōmīsPāḵōmīs Pachôme (“Ascéticon”)Pāḵōmīs is a saint commemorated in Pachomius - Ascetikon (text) , a work surviving in at least 4 manuscripts including ms Lady Meux 6 (?)Matches:1. (persName) Pachomius - Ascetikon2. (persName) Pachôme (“Ascéticon”)URI: http://syriaca.org/person/1955
2
Pachomius - ܦܟܘܡNames: PāḵōmPāḵōm PachômePāḵōm is a saint commemorated in Pachomius (text) , a work surviving in at least 4 manuscripts including — ed (1): mss Paris, Bibliothèque nationale, syr. ...Matches:1. (persName) Pachomius2. (persName) PachômeURI: http://syriaca.org/person/1954

**Comment by davidamichelson** [comment]
Please keep the URI 1955 as I have used it in a ref

**Comment by jsaintlauren** [comment]
OK - merge 1954 into 1955 -- then when you have done that, let me know please, and I will rewrite the abstract for 1954 so that it is a better description of Pachomius

**Comment by jsaintlauren** [comment]
Please merge 1401 INTO 669, thanks!

**Comment by nathangibson** [comment]
OK, I've merged 1954 into 1955 and 1401 into 669. I'm reassigning this to you, @jsaintlauren , since you wanted to rewrite the abstract for 1955.
