### ISSUE TITLE
Creating URI for Clemons

### ISSUE THREAD

**Issue by PGAMiller** [srophe/srophe-app-data#322]
Nathan,
Can you create this bibl record and let me know the URI assigned to it?
Thanks!

```<bibl xml:id="ClemonsChecklist">
                  <author>James T. Clemons</author>
                  <title xml:lang="en" level="a">A Checklist of Syriac Manuscripts in the United
                    States and Canada.</title>
                <citedRange unit="pp">508</citedRange>
</bibl>```

**Comment by davidamichelson** [comment]
oops here is the full info needed:


                <analytic>
                  <author>James T. Clemons</author>
                  <title xml:lang="en" level="a">A Checklist of Syriac Manuscripts in the United
                    States and Canada.</title>
                </analytic>
                <monogr>
                  <title xml:lang="en" level="j">Orientalia Christiana Periodica</title>
                  <imprint>
                    <biblScope type="volume">32</biblScope>
                    <biblScope type="pages">224-251, 478-522.</biblScope>
                    <date calendar="Gregorian" when="1966">1966</date>
                  </imprint>
                </monogr>

**Comment by davidamichelson** [comment]
@nathangibson If you can do this today it would be a great help. Thanks

**Comment by nathangibson** [comment]
OK @PGAMiller it's http://syriaca.org/bibl/2202 (http://wwwb.library.vanderbilt.edu/bibl/2202)
