### ISSUE TITLE
From the new incomplete persons, something is keeping this record from rendering in HTML

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#328]
http://syriaca.org/person/1093

It shows up in search but gives a 404

**Comment by wsalesky** [comment]
Looks okay to me:

http://wwwb.library.vanderbilt.edu/person/1093

The link you posted is to the production server.

**Comment by davidamichelson** [comment]
Hmm, the link I was trying was this: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1093 which doesn't work, although this does work: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1118

**Comment by wsalesky** [comment]
Can you try a hard refresh? Both of those links work for me.

**Comment by davidamichelson** [comment]
Works now! Thanks
