### ISSUE TITLE
Links between Works and Persons for New Incomplete Saints

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#329]
This is a new version of this issue: https://github.com/srophe/persons/issues/3

For all Saint's person records where revisionDesc status="incomplete" please run a script that does the following:

Grabs all tei:idno of @type="BHS"
Uses those numbers to find work URIs in BHSE (note that each person may have more than one BHS idno)
Example, person/1093 has ```<idno type="BHS">596</idno>```
Work/806 also has ```<idno type="BHS">596</idno>```

The title and uri for work/806 should then be inserted into the person record as an attestation in the following manner:

```
<event type="attestation" xml:id="attestation[personURI\d]-1" source="[the source cannot be assumed to be "-1" it needs to be done by look up for the xml:id of the bibl element with <ptr target="http://syriaca.org/bibl/649"/>]"> 
<p xml:lang="en"><persName @ref="PERSONURI">[Name from en headword of person]</persName> is commemorated in <title @ref="WORKURI">[Title headword from work and URI as string]</title>.</p> </event>
```
There should be one attestation for each BHS idno in the person record.

At the same time, we also want to insert in to the corresponding work record a relation element about the person:

```
<listRelation>
<relation name="dcterms:subject" active="[WorkURI]" passive="[personURI]" source="#bib[workURI\d]-1"/>
<listRelation>
```
note on this one you can assume the source ref is "-1"

Finally, the script when done should delete all tei:idno of @type="BHS" from the person record.

Finally, we will likely also want to do another round of this: https://github.com/srophe/srophe-eXist-app/issues/428 but that can wait unless you think it is best to include it at this time.

**Comment by davidamichelson** [comment]
Update: Could you also please run this on the persons/tei files (i.e. the ones that are not in the saints folder). There are a small number that have BHSE numbers there.

**Comment by wsalesky** [comment]
Where does the listRelation element go in works? After the main bibl? or inside the bibl?

**Comment by davidamichelson** [comment]
Sorry just saw this now. I am free to chat if you wish.

**Comment by davidamichelson** [comment]
Path /TEI/text/body/listRelation/relation

All relations should be in the same listRelation (there should only be one listRelation per doc).

**Comment by davidamichelson** [comment]
A couple more notes on this:

First, we should run this script on two sets of data:

For all records in https://github.com/srophe/srophe-app-data/tree/dev/data/persons/tei/saints/tei where revisionDesc status="incomplete" 

And also all records that are in https://github.com/srophe/srophe-app-data/tree/dev/data/persons/tei (i.e. not in Saints but in authors).

Lastly, let's wait on changing abstracts: srophe/srophe-eXist-app#428

**Comment by nathangibson** [comment]
@wsalesky Correction to the above: the listRelation should look as follows
```
<listRelation>
     <relation name="syriaca:commemorated" active="[WorkURI]" passive="[PersonURIs]" source="#bib[workURI\d]-1"/>
</listRelation>
```
For example, http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/270/tei :
```
<listRelation>
     <relation name="syriaca:commemorated" active="http://syriaca.org/work/270" passive="http://syriaca.org/person/1544 http://syriaca.org/person/8" source="#bib270-1"/>
</listRelation>
```

**Comment by wsalesky** [comment]
Data is here to be checked. 
Still need to remove the BHSE idno and run on authors. If it looks good I will do that tomorrow.

**Comment by wsalesky** [comment]
New data is here:
https://github.com/srophe/srophe-app-data/tree/issue329

**Comment by wsalesky** [comment]
@davidamichelson I plan on running this on authors. Should I just run it on all persons records? Or do some saints already have the attestation already? I can split them out, but it would be faster to just run on the whole directory, if it won't cause duplicates.

**Comment by wsalesky** [comment]
Okay, I ran it on the whole persons directory. 
This branch:
https://github.com/srophe/srophe-app-data/tree/issue329-all-data

**Comment by davidamichelson** [comment]
Thanks, I'm sorry today got away from me, can I check in with you tommorrow
on this and the insert BIBL URI issues

**Comment by davidamichelson** [comment]
So some saints already had attestations, I will see if this produced duplicates or not. Please e-mail me a time and we can meet tomorrow to check in.
Thanks!

**Comment by davidamichelson** [comment]
It didn't seem to cause duplicates, though I am not sure I wrote the code correctly to check. But, for reference, there were 1285 attestation tei:events already in the data (in saints records where revisionDesc @status="draft"). Examples are records 1092 and 1097.

**Comment by davidamichelson** [comment]
One way to find out would be to test if there are any saints records where revisionDesc @status="draft") that have a idno @type="BHS" before the script was run.

**Comment by wsalesky** [comment]
Running the following script returns 0 records, so I think we are okay. 

```
for $r in collection('/db/apps/srophe-data/data/persons/tei/saints/tei')//tei:revisionDesc[@status="draft"][descendant::tei:idno[@type='BHSE']]
return $r
```

**Comment by davidamichelson** [comment]
Great

**Comment by davidamichelson** [comment]
Okay, on tweak to this script. It is inserting the attestation after the persNames, but instead it should come before the first bibl (or after the abstract, but not all records have abstracts yet).

**Comment by davidamichelson** [comment]
Otherwise this script is running fine and ready to be run on dev, after #356

**Comment by davidamichelson** [comment]
@wsalesky I'd like to check in on this today please.

**Comment by davidamichelson** [comment]
@wsalesky I think that this and #136 are the same. Please run this script on any saints where revisionDesc status="incomplete" 

I will add more on this later this pm

**Comment by davidamichelson** [comment]
Okay, just checking back in on this.

To summarize here is what needs to happen:

This script (which you wrote a while back, see above and also https://github.com/srophe/srophe-app-data/issues/136 and srophe/persons issue #3

The script should be run on all records that have tei:idno of @type="BHS"

Look up the BHSE record URI corresponding to the idno type="BHS" in the person record.

Add a relation to person URI into the BHSE record (please add a new test for this, because Nathan's script already did this)

Add attestation into the person record using the URI of BHSE record.
    
Remove idno type="BHS" from the person record.

**Comment by davidamichelson** [comment]
That's a wrap for me. I hope to get up early and get you the about page copy

**Comment by wsalesky** [comment]
Okay:
Branch here:
https://github.com/srophe/srophe-app-data/tree/issue123

**Comment by wsalesky** [comment]
XQuery:
https://github.com/srophe/srophe-xQueries/blob/master/329-bhse-relations.xql

**Comment by davidamichelson** [comment]
Okay, so this script did not work. It only appears to have run on a few persons. For example, person/13 still has a number of idnos of @type=BHS

https://github.com/srophe/srophe-app-data/blob/issue123/data/persons/tei/13.xml#L290-L298

**Comment by davidamichelson** [comment]
Okay, I am guessing the issue is the test to run  on tei:revisionDesc[@status="incomplete"]

instead, just run on if the document has any tei:idno[@type='BHS']]

**Comment by davidamichelson** [comment]
Okay, one more request since we will need to rerun. Could the insert of the new attestations in the person records be done before the first bibl rather than after the last persName please?

**Comment by wsalesky** [comment]
New data: https://github.com/srophe/srophe-app-data/tree/issue123-August-17

**Comment by davidamichelson** [comment]
I think this is done! Looks Great.
