### ISSUE TITLE
Split: Barbara 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#33]
This file is messed up.  http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1624 Barbara got conflated with Barsamya.

**Comment by jedwardwalters** [comment]
@jsaintlauren 
I am going through the split issues, and I just came across this one. I just looked at the Barbara link above, and it looks okay except for one of the attestations, which still mentions Barsamya. Barsamya has a separate page (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1162), and that one seems fine.

Am I missing something else? Or can we just remove that one attestation?

**Comment by jsaintlauren** [comment]
That's it, thanks! Please just remove the attestation.

**Comment by jedwardwalters** [comment]
Done.
