### ISSUE TITLE
Are these saints or places?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#332]
Hi J-N 

These are ones David K caught:

http://syriaca.org/person/1616	http://wwwb.library.vanderbilt.edu/person/1616	Asia
http://syriaca.org/person/1641	http://wwwb.library.vanderbilt.edu/person/1641	Caesarea

Should they be removed from persons? Perhaps we could just link those BHSE entries to the places? Or should these called "The Maryrs of Asia" etc?

**Comment by nathangibson** [comment]
For what it's worth, I think "Asia" is a personal name.

**Comment by jsaintlauren** [comment]
They are both people - personal names.
