### ISSUE TITLE
Person 1201 has a Zanetti Name but no Zanetti links, is that correct?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#333]
<persName xml:id="name1201-4" xml:lang="fr-x-zanetti" source="#bib1201-">Dānīʾēl ʾāsyā</persName>

If this is correct, just let me know by assigning this back to me please. If it is not, please add links.

**Comment by jsaintlauren** [comment]
I don't think that Daniel the doctor has a zanetti link.

**Comment by davidamichelson** [comment]
The confusing question is how did we get a Syriac name and a transliterated name for him if there is nothing on him in BHSE? Those names did not come from Fiey. That makes me wonder if we lost a link to BHSE for him somehow.

**Comment by davidamichelson** [comment]
We imported it from another persons names in Syriac
