### ISSUE TITLE
Three records to deprecate? There are two records for Joseph and one for Mary here: Persons 1832, 1834  Person 1879

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#334]
There are two ghost records for Joseph and one for Mary here:
Persons 1832, 1834 
Person 1879
These all are empty without notes or bibliography and we have the biblical Mary and Joseph already.

Should we deprecate these? If so please assign this to Nathan.

**Comment by jsaintlauren** [comment]
Yes @nathangibson please deprecate persons 1832, 1834 and 1879
