### ISSUE TITLE
J-N are these the same or different? Shoudl we merge?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#338]
1
Martyrs of Karka d'Beth Slokh - ܣܗ̈ܕܐ ܕܟܪܟܐ ܕܒܝܬ ܣܠܘܟNames: Sāhdē d-Karkhā d- Bēth Slōkh Sāhdē d-Karḵā d-Bēṯ SlōḵMartyrs de Karka de Bet-Selok Sāhdē d- Bēth Slōkh Sāhdē d-Bēṯ SlōḵMartyrs de Karka de Beth-SelokMartyrs of Karka d'Beth Slokh commemorates a group of Persian martyrs, men and women. Their deaths were set in the time of the ...Matches:1. (persName) Sāhdē d-Karkhā d- Bēth Slōkh2. (persName) Martyrs of Karka d'Beth Slokh3. (persName) Sāhdē d-Karḵā d-Bēṯ Slōḵ4. (persName) Sāhdē d- Bēth Slōkh5. (persName) Sāhdē d-Bēṯ Slōḵ6. (persName) Martyrs de Karka de Beth-Selok7. (persName) Martyrs of Karka d'Beth Slokhmore ...URI: http://syriaca.org/person/1897
2
Sāhdē d- Bēth Slōkh - ܣܗ̈ܕܐ ܕܒܝܬ ܣܠܘܟ (Qadishe: A Guide to the Syriac Saintssaint) Names: Sāhdē d-Bēṯ SlōḵMartyrs de Karka de Beth-SelokSāhdē d - Bēth Slōkh is a saint commemorated in The Martyrs of Karka d - Beth Slokh (text) , a work surviving in at least 10 ...Matches:1. (persName) Sāhdē d- Bēth Slōkh2. (persName) Sāhdē d-Bēṯ Slōḵ3. (persName) Martyrs de Karka de Beth-Selok4. (persName) Sāhdē d- Bēth Slōkh5. (title) The Martyrs of Karka d- Beth Slokh (text)6. (p) Sāhdē d- Bēth Slōkh is commemorated in The Martyrs of Karka d- Beth Slokh (text).7. (title) The Martyrs of Karka d- Beth Slokh (text)URI: http://syriaca.org/person/1898

**Comment by jsaintlauren** [comment]
Yes - it looks like Nathan already merged
