### ISSUE TITLE
Non-Persons to Deprecate

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#339]
J-N with your approval, can we deprecate these (and remove the links to them in BHSE?)

http://wwwb.library.vanderbilt.edu/person/1943	Nativity and Stephen

http://wwwb.library.vanderbilt.edu/person/1967	Passion

**Comment by nathangibson** [comment]
@jsaintlauren What do you think?

**Comment by davidamichelson** [comment]
I agree, please do.

**Comment by jsaintlauren** [comment]
Yes

On Friday, July 8, 2016, David Michelson <notifications@github.com> wrote:

> I agree, please do.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/srophe/srophe-app-data/issues/339#issuecomment-231426362>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEY0lGG45nz337Cj8XfAj7hgauywH91gks5qTo18gaJpZM4I-S5V>
> .
>


-- 
Sent by my large poodle - please excuse typos
