### ISSUE TITLE
Are these duplicates? 2069 and 2070

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#341]
If yes, just let us know which one to get rid of or we can merge them:

        ```<note type="abstract" xml:id="abstract-en-2069" source="#bib2069-1" subtype="auto-formatted">
          <persName ref="http://syriaca.org/person/2069">Sargīs</persName>features in<persName
            ref="http://syriaca.org/person/74">John of Ephesus'</persName>Lives of the Eastern
          Saints. </note>
        <note type="abstract" xml:id="abstract-en-2070" source="#bib2070-1" subtype="auto-formatted">
          <persName ref="http://syriaca.org/person/2070">Sargīs</persName>features in<persName
            ref="http://syriaca.org/person/74">John of Ephesus'</persName>Lives of the Eastern
          Saints. </note>```

**Comment by jsaintlauren** [comment]
They are different guys with the same name.

**Comment by nathangibson** [comment]
@jsaintlauren FYI, if our readers may potentially confuse these, we try to include a disambiguation relationship, like so:

```
<relation type="disambiguation" name="different-from" mutual="http://syriaca.org/person/2069 http://syriaca.org/person/2070"/>
```
You could copy this and paste it in after the end of the person tag (`</person>`) for both records.
Note: The format of this will be changing to come into line with http://syriaca.org/documentation/relations.html and https://github.com/srophe/srophe-app-data/issues/214 , but it hasn't yet, so you can use the old format above.

**Comment by davidamichelson** [comment]
Thanks, Nathan would you mind adding it in this case please? Thnks

**Comment by nathangibson** [comment]
Sure. Done.
