### ISSUE TITLE
Please merge these abstracts back into Saints

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#342]
Hi Winona,
If you could do this first thing next week that would be great please

If there is a new abstracts in this file it should replace the existing one for the corresponding URI, but if there is not one in here, please leave the existing abstract as is.

The new abstracts are here: https://github.com/srophe/persons/blob/master/working-files/Cleaning-Abstracts-for-Saints/saints-abstracts.xml please merge them with all saint's files regardless of revisionDesc status.

Please note, not all of the existing abstracts have XML IDs so you can't match on that, you will have to calculate the URI. But after this merge they all should!

Thanks
Dave

**Comment by wsalesky** [comment]
@davidamichelson I don't see any without xml:id's? If they do not have an xml:id how should I match? Do they all have source attributes.

**Comment by wsalesky** [comment]
Okay, new data is here: 
https://github.com/srophe/srophe-app-data/tree/issue342

**Comment by davidamichelson** [comment]
Hi Winona,

Sorry for the confusion, all of the new abstracts have xml:ids based on the URI of the record they belong to. The abstracts they are replacing did not all have xml:ids, but of course were in the record with the URI.

But it looks like you figured that out. It looks like it worked!

One quesition, these four records were also changed but I was not expecting that: 239, 325,326, 366

It looks like it was just whitespace that changed in them, is that right?

Dave

**Comment by davidamichelson** [comment]
Okay, one more on this issue. I think the data looks good, with one exception which is my fault not due to your script. It looks like the white space around the persNames, placeNames, and title elements inside the note element got removed (perhaps when I exported them?).

Can you normalize this somehow or will I need to write some rules for find and replace? In other words, these elements need spaces before and after them, unless they are at the beginning of the note or before punctuation.

Should I just write a regex to fix them?

Either way, I think we can merge these back into the dev branch so J-N can edit.

Thank you!

**Comment by wsalesky** [comment]
Yes, it appears to just be white space difference.
-Winona

**Comment by wsalesky** [comment]
Yes, a regex should be fine. Do you want me to merge this, or wait until
you have run the regex?
-Winona

**Comment by davidamichelson** [comment]
Thanks! I merged it in and I will fix the regex and then close this issue. And FYI, the webhooks worked!

**Comment by davidamichelson** [comment]
Actually, nevermind, I think the webhooks didn't work :(

**Comment by wsalesky** [comment]
The webhooks should be working for small updates. I have a timeout error
that happens on large updates, and while I know what the problem is, I
still don't have a good solution. :(

I have done the update manually.

**Comment by davidamichelson** [comment]
Thanks!
