### ISSUE TITLE
For existing attestations in persons (to be run before we run or merge #329) change initial name to a headword

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#356]
Should be run before #329 
For all person records that already have attestations (these could be in either persons directory), we need to change the initial name to the whatever each person record has for its @xml:lang="en" @syriaca-tags="#syriaca-headword" form of the name.

For example in person/44

This:
```
<event type="attestation" xml:id="attestation44-1" source="#bib44-6">
<p xml:lang="en">Pīlōksīnōs d-Mabōgh is commemorated in <title ref="http://syriaca.org/work/564">Philoxenus of Mabbug (text)</title>.</p>
</event>
```
Should be changed to this:
```
<event type="attestation" xml:id="attestation44-1" source="#bib44-6">
<p xml:lang="en"><persName ref="http://syriaca.org/person/44">Philoxenus of Mabbug</persName> is commemorated in <title ref="http://syriaca.org/work/564">Philoxenus of Mabbug (text)</title>.</p>
</event>
```
Note the following changes needed:
First the name is not tagged, but it should be regular in this form ```<p xml:lang="en">[GEDSH NAME] is commemorated...```

The GEDSH name should be available in the record, but it would be best just to grab it by regex instead, note it may have multiple whitespaces.

Then in the capture group, please insert a fully tagged and @ref linked form of the "en" persName.

This should be run on all attestations before creating the new ones with #329

**Comment by davidamichelson** [comment]
Note some of these the attestations to be replaced may have a an empty person node:

see: 
```
<event type="attestation" xml:id="attestation2007-1" source="bib2007-1">
                        <p xml:lang="en">
                            <persName ref="http://syriaca.org/person/2007"/> is commemorated in <title ref="http://syriaca.org/work/1887">Peter of Africa (text)</title>.</p>
                    </event>
```

**Comment by wsalesky** [comment]
For the empty persName I assume I should add the headword text?

**Comment by davidamichelson** [comment]
Actually, correction this example was generated by the script in #329 it is not part of the old data. Sorry!

**Comment by davidamichelson** [comment]
Looks like I need to make sure all records have  headword still

**Comment by wsalesky** [comment]
Okay.

**Comment by wsalesky** [comment]
I have a gist for this, once we have all the headwords in place. 
https://gist.github.com/wsalesky/a60b12eaea9846c50b8a168319947b85

**Comment by nathangibson** [comment]
We also want to update names of authors in works with the headwords. These should match the path `//TEI/text/body/bibl/(author|editor)/persName[matches(@syriaca-tags,'#syriaca-headword) and starts-with(@xml:lang,'en-')]`
cf. https://github.com/srophe/srophe-app-data/issues/385

**Comment by davidamichelson** [comment]
I think this is done! Looks Great.
