### ISSUE TITLE
A whole bunch of person records have disappeared from dev branch!

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#360]
@wsalesky @davidamichelson 
As far as I can tell, commit https://github.com/srophe/srophe-app-data/commit/85b6424e083e95a7a1c0eccba8633f2e3cdcf9ef seems to have deleted about half of our person records. Or am I missing something?

**Comment by nathangibson** [comment]
I'll wait to merge my latest branch until this is resolved.

**Comment by wsalesky** [comment]
@nathangibson @davidamichelson I rolled back the last two commits. Sorry for the sloppy merge, those should not even have been on the dev branch. Let me know if everything looks okay now.

**Comment by nathangibson** [comment]
Thanks! I think this has happened in one form or another to most of us now :-) I’ll take a look.

**Comment by wsalesky** [comment]
@nathangibson @davidamichelson  Just tried to upload a new version of the dev branch data. Looks like when I rolled back the commit this morning there was a merge conflict. Which is interesting, as I had no warnings in the logs. Trying to untangle it now.

**Comment by nathangibson** [comment]
My recent changes are now all safely isolated in my branch, so do what you need to do. Thanks!

**Comment by wsalesky** [comment]
Okay I think we are back on track. @nathangibson I spot checked a few of your changes as well as some of @jsaintlauren's changes from this afternoon. Looks like everything is still there. Let me know if you find anything that was over written.

**Comment by wsalesky** [comment]
@nathangibson if your changes look good to you I think we can close this.

**Comment by davidamichelson** [comment]
You are a saint!
