### ISSUE TITLE
Matching incompletes with New Person URIs

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#361]
@jsaintlauren @davidamichelson 
Dave asked me to see which saints in the [CBSC](https://docs.google.com/spreadsheets/d/1Z4VHSVaRJGi0yKZY-j3bxcJz1mr_8MNePoTflyu2_Jc/edit#gid=782104294) / [New URIs](https://docs.google.com/spreadsheets/d/1ruAawFWhOcTeGBzjgMLv_akzGRj3-DjxljJ6eFy6qOE/edit?ts=5759d169#gid=0) spreadsheets are ones that already exist in the set of incompletes that was recently uploaded. (Cf. #324 )

Here's how I'm doing this -- let me know if you want me to do something different. 
 1. In the [CBSC](https://docs.google.com/spreadsheets/d/1Z4VHSVaRJGi0yKZY-j3bxcJz1mr_8MNePoTflyu2_Jc/edit#gid=782104294) spreadsheet I have created a new tab called "Matched incompletes" where I am moving rows from the tab "New URIs to be minted from Qadishe" and including the URI of the incomplete record. 
 2. If the person is also in the [New URIs](https://docs.google.com/spreadsheets/d/1ruAawFWhOcTeGBzjgMLv_akzGRj3-DjxljJ6eFy6qOE/edit?ts=5759d169#gid=0) spreadsheet, then I am including the URI for the "incomplete" record in Column B, "Merge into". My thought is that since J-N has collected some info for these persons in the spreadsheet, we should go ahead and create the records from this spreadsheet but then merge them with the "incomplete" records.

**Comment by jsaintlauren** [comment]
Sounds good - thanks

**Comment by nathangibson** [comment]
@davidamichelson This was the other thing I was working on for Q. Should I keep working on this or should we reassign it?

**Comment by davidamichelson** [comment]
Let's discuss shortly.

**Comment by davidamichelson** [comment]
J-N will finish up the last few
