### ISSUE TITLE
Is Candida person/1637 different from person/3003?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#364]
@jsaintlauren 
Is Candida http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1637 different from person/3003 in the [New URIs spreadsheet](https://docs.google.com/spreadsheets/d/1ruAawFWhOcTeGBzjgMLv_akzGRj3-DjxljJ6eFy6qOE/edit?ts=5759d169#gid=0) ?

If these are different persons, we should mark them with a "different-from" relation and remove the citation of BHS 980 from person/1637. (I can do that if you want.)

If they are the same, let me know.

#361

**Comment by jsaintlauren** [comment]
Yes they are different.  

Please mark with “different from.”
