### ISSUE TITLE
Merge Yazdins person/1520 and person/2152 ?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#365]
@jsaintlauren Shall I merge http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2152 and http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1520 ?

**Comment by jsaintlauren** [comment]
Yes - 1520 is the better record. Please also fix dates in 1520. Thanks!

**Comment by nathangibson** [comment]
Sure. I was trying to figure out what the dates are supposed to be. Do you know?

**Comment by jsaintlauren** [comment]
He flourished in the fifth century.

**Comment by nathangibson** [comment]
Thanks!
