### ISSUE TITLE
Remove leading zeros on Qadishe dates?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#366]
@jsaintlauren @davidamichelson 
I've noticed a lot of saints that have leading zeros in the human readable dates. E.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1162 : "d. 0105"

Would we want to do a find-replace to remove these? I think it affects readability.

**Comment by jsaintlauren** [comment]
Yes thanks

**Comment by nathangibson** [comment]
I've corrected most of these today, but still need to go through and correct by hand the ones matching the following (30 or less):
`person//(death|birth|floruit|date)[matches(.,'^\s*0+') or matches(.,'\d{5,20}')]`
These are especially ones that look something like the following:
`<date from="0412" syriaca-computed-start="0400" to="0435" syriaca-computed-end="0500" notBefore="0400" notAfter="0500" source="#bib607-6">0412-04350400-0500</date>`

**Comment by jsaintlauren** [comment]
OK, thanks

**Comment by nathangibson** [comment]
I think all of these are fixed now.
