### ISSUE TITLE
these records need to be split 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#37]
Hey Dave!  This one is bit confusing.
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1383 is for Sinai the deacon, but it is conflated with Miles of Susa who was martyred with him (and who himself has two records!  8 and 1922)  -- but the abstract for 1383 is actually the abstract for Miles.  We need to create a new record for Sinai the deacon, or move the description in 1383 to either 8 or 1922- whichever becomes the main record!)  Then I will rewrite the abstract for Sinai.  Thoughts!

**Comment by nathangibson** [comment]
Also, 2 names and the disambiguation note in 1383 belong to Miles.

**Comment by jedwardwalters** [comment]
@jsaintlauren @nathangibson @davidamichelson 
Do we still need to make a new record for Sinai the deacon? It looks like person/1383 and person/1922 are now gone...perhaps deprecated?  

When you go to the page for Miles of Susa (person/8), the names for Sinai still show up. So, what needs to happen here?

**Comment by jsaintlauren** [comment]
Yes, we need to mint a URI for Sinai the Deacon.  We can use the same
description that we use for Miles, since Sinai is mentioned -

In hagiography: Miles was a Bishop of Susa <http://syriaca.org/place/415>.
He was born near Tehran <http://syriaca.org/place/875> and converted from
Zoroastrianism. He went on a long pilgrimage and opposed the manner of
leadership of Catholicos Papa <http://syriaca.org/person/669>. He was
imprisoned with his son Narsai and beaten by the governor Hormizd. The
priest Aboursam <http://syriaca.org/person/1544> and the deacon Sinai died
with him.

**Comment by jedwardwalters** [comment]
Done.  Sinai is now http://syriaca.org/person/3131
