### ISSUE TITLE
Which of these should we merge?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#374]
I need your confirmation @jsaintlauren or @davidamichelson for these potential merges that Dave has flagged. (Listing these in one place for convenience - you can respond in the individual issues.) 
#319 
#298 
#253 

Authors (or should I disambiguate these?):
#155 
#156 
#248 
#268 
#270

**Comment by jsaintlauren** [comment]
I addressed all of these, Nathan… couldn’t resolve #270 so maybe Dave wants to weigh in.

Thanks!

**Comment by nathangibson** [comment]
Thanks! I’ll take care of these soon.

**Comment by nathangibson** [comment]
OK @jsaintlauren and @davidamichelson , I've done all these except #156 and #270 which need further clarification. Leaving those open but closing this issue.
