### ISSUE TITLE
Can we deprecate the patriarchs of Antioch please? 

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#392]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1969

If yes, please let Nathan know.

**Comment by nathangibson** [comment]
@jsaintlauren What do you think?

**Comment by jsaintlauren** [comment]
Yes

On Friday, July 8, 2016, nathangibson <notifications@github.com> wrote:

> @jsaintlauren <https://github.com/jsaintlauren> What do you think?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/srophe/srophe-app-data/issues/392#issuecomment-231403922>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEY0lGIGkHrlNjqsd8HgfRg0Upt6etyhks5qTniWgaJpZM4JHoM6>
> .
>


-- 
Sent by my large poodle - please excuse typos
