### ISSUE TITLE
JN, should we deprecate work/1883?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#394]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1883? It appears to have too little information to be worth keeping.

We should also deprecate person 2059 at the same time.

If you agree please assign this over to Nathan.

**Comment by jsaintlauren** [comment]
yes

**Comment by nathangibson** [comment]
Have deprecated person/2059 but not the work yet.

**Comment by jsaintlauren** [comment]
Let's keep it for now in BHSE -- it might be one that we can garner more
information about from one of our editors.

**Comment by davidamichelson** [comment]
Yes, perhaps it is best not to deprecate any works as long as they have an MS attached.
