### ISSUE TITLE
Script for Changing Headwords

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#399]
Hi @wsalesky 
Well I need help with a script to change the headwords.
Could you help me with a scrip that will, for each person record where //tei:person has a persName of @xml:lang="en-x-gesdh" but does not have a persName[@syriaca-tags="#syriaca-headword" and @xml:lang="en"], will take the @xml:lang="en-x-gesdh" persName and construct and insert a new persName element for the record?

In other words for http://syriaca.org/person/1018

The script should copy (but not delete from the record):

```
<persName xml:id="name1018-2" xml:lang="en-x-gedsh" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">
                        <forename sort="1">Yeshuʿ</forename>
                        <addName type="family" sort="2">bar Abraham</addName>
                    </persName>
```
and then construct the new element:
```
<persName xml:id="name1018-0" xml:lang="en" syriaca-tags="#syriaca-headword">
                        <forename sort="1">Yeshuʿ</forename>
                        <addName type="family" sort="2">bar Abraham</addName>
</persName>
```
Note the following changes:
- the xml:id should be constructed to be name[URI\D+]-0 (we can safely assume that no record has a name with an xml:id ending in -0)
- the xml:lang changes to xml:lang="en" 
Everything else about the element should be copied over, all child nodes for example. The rest attributes in the persName element can be dropped (except for xml:id xml:lang and syriaca-tags), but any child elements should keep their attributes.

I tried to write this but did not have luck.

The new persName should be inserted as the first one in the list (just after the <person> opening tag and before persName[1]

**Comment by davidamichelson** [comment]
Also, could you please send me the link to the script you used to insert all those abstracts at one shot, I will use it to insert the persNames I have edited after we run this.

**Comment by wsalesky** [comment]
Here is the script to insert the abstracts (it needs to be moved over to @nathangibson repo for xqueries):
https://gist.github.com/wsalesky/5b182d79e9af86e9d7e2cd29544d3ee8

**Comment by wsalesky** [comment]
@davidamichelson is this a typo? `'@xml:lang="en-x-gesdh'` ? I have `'@xml:lang='en-x-gedsh' `in my earlier scripts. Just checking! Thanks.

**Comment by wsalesky** [comment]
@davidamichelson Should this script change the tei title to match the new English headword?

**Comment by davidamichelson** [comment]
Oops that is a typo and let's wait on changing the title, I want to do that after I have edited them all! Thanks

**Comment by wsalesky** [comment]
@davidamichelson and I assume you want to delete the headword from the gedsh name?

**Comment by davidamichelson** [comment]
I don't think that is necessary (is it?) How does the English Browse work currently?

**Comment by wsalesky** [comment]
Matches on @xml:lang and headword. So no it would not be functionally necessary .

**Comment by wsalesky** [comment]
Here is the script:
https://github.com/srophe/srophe-xQueries/blob/master/update-headwords-en-from-gedsh.xql

**Comment by davidamichelson** [comment]
Thanks! Did you run it on the data or shall I?

**Comment by wsalesky** [comment]
I did not run it. I have to go make lunch for the kids, so if you could run
it that would be great.

**Comment by davidamichelson** [comment]
Great will do!

**Comment by davidamichelson** [comment]
Good news the script runs as expected. Bad news, I can't seem to get the files out of exist-DB. When I try to connect via WebDAV and download they truncate and when I try to connect via oxygen I get a Java error. How do you usually download the files?
