### ISSUE TITLE
Should we deprecate these

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#405]
@jsaintlauren if you agree please assign to Nathan

Nathan, no merge needed but do remove any references in BHSE

http://syriaca.org/person/1972
        <persName xml:id="name1972-2" xml:lang="en" syriaca-tags="#syriaca-headword">Patriarchs,
          Prophets, Apostles and Fathers</persName>
    </p>
http://syriaca.org/person/1971
        <persName xml:id="name1971-2" xml:lang="en" syriaca-tags="#syriaca-headword">Patriarchs
          and Prophets</persName>
    </p>
http://syriaca.org/person/1970
        <persName xml:id="name1970-2" xml:lang="en" syriaca-tags="#syriaca-headword">Patriarches
          of the Orient (catholicos)</persName>
    </p>

**Comment by jsaintlauren** [comment]
yes please deprecate
