### ISSUE TITLE
I think we should deprecate this saint but keep the BHSE record

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#419]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1758

@jsaintlauren do you agree?

**Comment by jsaintlauren** [comment]
Yes

On Saturday, July 9, 2016, David Michelson <notifications@github.com> wrote:

> Assigned #419 <https://github.com/srophe/srophe-app-data/issues/419> to
> @jsaintlauren <https://github.com/jsaintlauren>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/srophe/srophe-app-data/issues/419#event-717770225>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEY0lFcgG_MwJcj1T2DEMeY7i6zOT4R4ks5qT4JbgaJpZM4JImTc>
> .
>


-- 
Sent by my large poodle - please excuse typos

**Comment by jsaintlauren** [comment]
@nathangibson please deprecate
