### ISSUE TITLE
Should we deprecate these?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#423]
These person records do not seem to be specific enough? We would leave the BHSE records of course:

ConfessorsNames: ConfesseursMatches:1. (persName) ConfessorsURI: http://syriaca.org/person/1654
2
ConfessorsNames: ConfesseursMatches:1. (persName) ConfessorsURI: http://syriaca.org/person/1653
3
Martyrs and Confessors - ܣܗ̈ܕܐ ܘܡܘܕ̈ܝܢܐNames: Sāhdē w-MawdyaneMartyrs et ConfesseursSāhdē w-Mawdyane is commemorated in Confessors and Martyrs (text) , a work surviving in at least 13 manuscripts including ms Oxford, Bodleian Library, syr. ...Matches:1. (persName) Martyrs and Confessors2. (title) Confessors and Martyrs (text)3. (title) Confessors and Martyrs (text)4. (title) The Martyrs and Confessors (text)5. (title) Martyrs and Confessors (text)URI: http://syriaca.org/person/1906

**Comment by jsaintlauren** [comment]
@davidamichelson @nathangibson  yes deprecate all of these
