### ISSUE TITLE
This place appears to be a duplicate perhaps?  Cf http://syriaca.org/place/36  and http://syriaca.org/place/2279

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#424]
Hi @tacarlson 

Hmm the error button seems to not work for me again, so I am sending this manualy. What do you think?

This place appears to be a duplicate perhaps?

Cf http://syriaca.org/place/36  and http://syriaca.org/place/2279

**Comment by tacarlson** [comment]
place/36 is an Eastern Syriac diocese; place/2279 is a Western Syriac diocese (see last name in each record, as taken from Wilmshurst)

________________________________
