### ISSUE TITLE
Should person/1135 and person/886 be merged/possibly identical?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#433]
Whoever gets to investigating this first. It seems that our record for the author person/886 is coming from the possibility of reading the name ʿEqebshma in Abdisho, according to Assemani (http://digitale-sammlungen.ulb.uni-bonn.de/content/pageview/33570 note 5). The info on him looks sparse, so I'm not sure how far we'll get with this one. 
Cf. #271 and #154

**Comment by jsaintlauren** [comment]
I don't know.  Let's not worry about it.
