### ISSUE TITLE
I fell off qadishe citation :( 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#439]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1451 

I think my name fell off of qadishe bib information.  @wsalesky @davidamichelson

**Comment by nathangibson** [comment]
The editor links were incorrect. I've fixed these and I think that will fix the problem. E.g., see http://wwwb.library.vanderbilt.edu/person/1474. 
@wsalesky I just pushed a large commit with this fix -- could you please push it to the dev server? Thanks!

**Comment by wsalesky** [comment]
@nathangibson data has been updated on the dev server.

**Comment by nathangibson** [comment]
Thanks!
