### ISSUE TITLE
same issue with my problematic name in the editor's list on BHSE 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#442]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/1916 

Hi @nathangibson .  Can you fix this too in BHSE?  My name fell out .  Thanks!!

**Comment by davidamichelson** [comment]
@jsaintlauren Can you explain in more detail? It looks fine to me at first anyway

**Comment by jsaintlauren** [comment]
et al., “‘Abd al-‘Aleq (text) — ܥܒܕܐܠܥܠܩ” in Bibliotheca Hagiographica
Syriaca Electronica, eds. and David A. Michelson, entry published November
5, 2015, Syriaca.org: The Syriac Reference Portal, ed. David A. Michelson.
http://syriaca.org/work/1916.
Bibliography: et al., “‘Abd al-‘Aleq (text) — ܥܒܕܐܠܥܠܩ.” In Bibliotheca
Hagiographica Syriaca Electronica, edited by and David A. Michelson. Entry
published November 5, 2015. Syriaca.org: The Syriac Reference Portal,
edited by David A. Michelson. http://syriaca.org/work/1916.
About this Entry

Entry Title: ‘Abd al-‘Aleq (text) — ܥܒܕܐܠܥܠܩ

Publication Date: November 5, 2015
Authorial and Editorial Responsibility:

   - David A. Michelson, general editor, Syriaca.org: The Syriac Reference
   Portal
   - and David A. Michelson, editors, Bibliotheca Hagiographica Syriaca
   Electronica
   - Jeanne-Nicole Mellon Saint-Laurent, David A. Michelson, Ugo Zanetti,
   and Claude Detienne, entry contributors, “‘Abd al-‘Aleq (text) — ܥܒܕܐܠܥܠܩ
   ”

**Comment by jsaintlauren** [comment]
Nathan was able to fix it in Qadishe, where we had the same issue.

**Comment by jsaintlauren** [comment]
It is because I had two different editor numbers, one with "Mellon" and the
other without.

**Comment by jsaintlauren** [comment]
He was able to fix it with a find and replace I think.

**Comment by jsaintlauren** [comment]
The resp statement should look like this ..

<respStmt><resp>Edited by</resp><name type="person" ref="
http://syriaca.org/documentation/editors.xml#jnsaint-laurent">Jeanne-Nicole
Mellon Saint-Laurent</name></respStmt>

**Comment by jsaintlauren** [comment]
Looks good now  ! Thanks
