### ISSUE TITLE
Manuscript taxonomy updated code

### ISSUE THREAD

**Issue by PGAMiller** [srophe/srophe-app-data#446]
Dr. Michelson,
https://gist.github.com/PGAMiller/1cd784205a6ed3a396a2f3fbdeb206af
Above is the link to the gist with the updated code for the Wright taxonomy in the manuscript files. Please find and replace the old code in the manuscript files. (If there's an issue with the gist link, please let me know)

**Comment by wlpotter** [comment]
@davidamichelson I think this can be closed in favor of https://github.com/srophe/britishLibrary-data/issues/41 ?
