### ISSUE TITLE
extra space and period before Palladius entry 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#456]
@wsalesky @nathangibson 
Hello! 
As you can see in this record, 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/519 
there is a typo in the display of the second work listed under "editions." -- Budge's  Paradise of the Fathers.  I think it is in the bibl record?

**Comment by wsalesky** [comment]
It was a bug in the XSLT. Fixed.
