### ISSUE TITLE
new records for Q 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#460]
@nathangibson if in the process of sorting through BHSE stuff I come across records that need to be created, where shall I put those?  Do you want me to make a new spreadsheet?

**Comment by nathangibson** [comment]
Hmm, good question. How many do you think there are?

**Comment by jsaintlauren** [comment]
I don't know! Hopefully not too many! Here is an example of a text that was never split.  
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/326 
We have one for Hapsai but not Aithalaha

**Comment by nathangibson** [comment]
I see. For assigning URIs, if your srophe-app-data repo is up to date it should be safe to just check there and create a file with the next number. 

For ones that need to be split, I would suggest duplicating the current one, renaming the duplicate with the new URI, doing a find-replace to change any references to the URI or xml ids, and then making your manual changes. If it is an entirely new record, I would recommend doing the same process, but just using another record as a template for the new one. 

If you find there are a lot, we should make a spreadsheet or ask W. to build a form. But we don’t yet have a spreadsheet converter for works, so taking time to make one at this point would slow you down if it’s only a few. Make sense? We can talk about it today if you like.

**Comment by davidamichelson** [comment]
Let's discuss today.

**Comment by davidamichelson** [comment]
Please see this link for assigning new URIs from splits: https://docs.google.com/spreadsheets/d/1ruAawFWhOcTeGBzjgMLv_akzGRj3-DjxljJ6eFy6qOE/edit#gid=1921709114
