### ISSUE TITLE
Cleaning up the Anonymi from Spear

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#470]
@jedwardwalters When we check in next, Dan could use help cleaning up the anonymi from Spear and you are our current expert.

Using the URIS marked as anonymous in here:
https://docs.google.com/spreadsheets/d/1lS-QrCtUfFr5fTQ9utaRLTbo754RJprxKJmHTDYj8SQ/edit#gid=0

We need do the following edits to these persons:
(example: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2208/tei)
1. Change Anonymous number to the URI number in Title and in persName
2. Change Title to include the name from syriaca-tags="#anonymous-description"
3. Add the @ syriaca-tags="#anonymous-description" to the relevant persName

**Comment by jedwardwalters** [comment]
Done.
