### ISSUE TITLE
person citations in Zotero

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#479]
@jsaintlauren 
There was unfortunately some confusion with some person citations in the Zotero bibls I exported, and I’m trying to straighten it out now.

Is the following correct?

- Howard (ed.), The Teaching of Addai bibl should have the subject Addai (http://syriaca.org/person/1118)
- Greisiger, Šarbēl, Baḇai, Märtyrer in Edessa bibl should have the subjects Sharbel (http://syriaca.org/person/1454), Babai (http://syriaca.org/person/1151), and Barsamya (http://syriaca.org/person/1162)

**Comment by jsaintlauren** [comment]
yes
