### ISSUE TITLE
Person 1958 Needs to be split

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#48]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1958

**Comment by wlpotter** [comment]
I believe this is fixed. https://syriaca.org/person/1958 is now only Pamphilius.

 The others commemorated in syriaca.org/work/245 (Vales, Seleucus, Paul, Porphyry, Theophilus, Julianus, and One Egyptian) all have their own URIs.
