### ISSUE TITLE
Holy Women of the Syrian Orient

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#480]
@jsaintlauren @davidamichelson 
We have records in Zotero for two editions Holy Women of the Syriac Orient, one of which has not been exported yet. Can I delete the second one, or do we need information for multiple editions? Ther are actually a lot of different editions -- see http://www.worldcat.org/title/holy-women-of-the-syrian-orient/oclc/13666126/editions?editionsView=true&referer=br

**Comment by jsaintlauren** [comment]
Either edition is fine

**Comment by nathangibson** [comment]
Great, thanks!
