### ISSUE TITLE
Records without citations?

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#490]
@nathangibson person/979 Thomas: Do you know about the origin of this record? Who is this person?

**Comment by davidamichelson** [comment]
Same for http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/977 and persons 972-75

**Comment by davidamichelson** [comment]
See also person/964

**Comment by nathangibson** [comment]
I think all of the author records without source info or further description (usually in the 900s and up) are placeholders for Baumstark data. I am merging in the Baumstark data, which may happen as early as today.

**Comment by nathangibson** [comment]
So let’s return to these after that merge.

**Comment by davidamichelson** [comment]
Okay, that sounds great!

FYI, let's wait on the french from the spreadsheet unless it is too late.
