### ISSUE TITLE
extra characters appearing in @syriaca-tags

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#5]
I'm seeing this attribute: syriaca-tags="#syriaca-headword&#xA;
on the following record 
https://github.com/srophe/srophe-app-data/blob/dev/data/works/tei/1062.xml
as well as on the same record in draft-data.

I haven't checked to see how many other records have this problem, but I assume its a transformation issue and will need to be fixed with a find and replace.

**Comment by wsalesky** [comment]
Okay. I think a find and replace should do the trick. I will track down the issue in the xslt as well.

**Comment by wsalesky** [comment]
Fixed in draft data and srophe-app-data, although draft data versions are not the canonical version of the data and can/should be deleted.

**Comment by nathangibson** [comment]
Thanks!
