### ISSUE TITLE
Please decrate the test work!

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#501]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/work/221

@nathangibson did you ever write up the steps for how to deprecate, I could do this one myself if you teach me.

**Comment by nathangibson** [comment]
I've written up some URI policies now. Please see the "Redirected and Deprecated URIs" section of http://wwwb.library.vanderbilt.edu/exist/apps/srophe/documentation/uris.html
