### ISSUE TITLE
Missing Persons Report

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#502]
We seem to be missing many people in SBD. I keep getting 404 errors when I type in URIs. Also, when trying to browse by type we only seem to have 225 authors, 1 author/saint, 3 saints, and 60 unknown.

**Comment by wsalesky** [comment]
Sorry all, I ran an update and it is taking a very long time! @davidamichelson @dlschwartz @jsaintlauren @nathangibson
