### ISSUE TITLE
problem with syriaca-headword in person/2804

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#505]
No headword appears in the list resulting from a search for "Elijah"
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=elijah&start=20

**Comment by wsalesky** [comment]
Note to self: caused by syriaca-tags="#syriaca-headword #syriaca-anglicized"

fix in rec-short-view.xsl

**Comment by wsalesky** [comment]
Solved by XPath.
