### ISSUE TITLE
Some records still have temp place name refs

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#514]
See http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/621

@nathangibson Do we have this as a task to complete or did some of these miss getting done?

**Comment by nathangibson** [comment]
I'm not seeing a task. It looks like there are 17 of these placeNames and 4 persNames. These were persons/places for whom at the time (2 years ago) we had no entries. For places, the majority are dioceses for which we did not yet have one of the right confession. Should I just remove the refs, and leave the placeName/persName, or should we create new entries for them?

**Comment by davidamichelson** [comment]
Let's just remove the refs, we will scan for places without refs later.

**Comment by nathangibson** [comment]
Done.
