### ISSUE TITLE
Persons with contradictory dates

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#522]
@davidamichelson @jsaintlauren 
Anyone want to figure out (and correct) what went wrong with the dates in the following person records?
person/88
person/607

**Comment by nathangibson** [comment]
Compare the attributes to each other and to the human-readable date

**Comment by jsaintlauren** [comment]
I don't see the problem with person 88.

I will clean up person 607.  It is a big mess of conflated records.

**Comment by jsaintlauren** [comment]
I fixed 607.

**Comment by nathangibson** [comment]
OK, I cleaned up person 88. The floruit dates were all messed up.
