### ISSUE TITLE
Rabban as name

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#526]
Anybody have any thoughts on whether we should alphabetize on the title Rabban? Gedsh does not alphabetize based on it for: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/366

I have not alphabetized on it.

**Comment by jsaintlauren** [comment]
If GEDESH doesn't, then let's not either. Thanks.

**Comment by nathangibson** [comment]
I agree.

**Comment by dlschwartz** [comment]
Yeah, I'm happy to follow GEDSH here. Furthermore, if I expected to find a
person under Rabban and couldn't, it's pretty easy to think of where to
look.
Dan

On Tue, Aug 9, 2016 at 7:40 AM, nathangibson <notifications@github.com>
wrote:

> I agree.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2Dapp-2Ddata_issues_526-23issuecomment-2D238540447&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=FT6TJGSCNdW-dLptoxLvbhVGTh-TEwKK4QuH329cSn0&s=3MY_DB7GR7tsx3mwtBAdEmTSk3-s8BzRHaEJGdp518E&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzjhJoaz24-5FlP7wvzwv5lC6GGxp-2DFks5qeHVbgaJpZM4Jffqm&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=FT6TJGSCNdW-dLptoxLvbhVGTh-TEwKK4QuH329cSn0&s=0Lqg-tWOrXgB64gJR0WdxcXZcf8NrbJ84J6hD4xvzYk&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
www.syriaca.org <http://syriaca.org/>
