### ISSUE TITLE
person/307 and person/1086?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#530]
I've disambiguated Aba of Kashkar (person/1086) from Aba II of Kashkar (person/307) in favor of Baumstark (https://archive.org/stream/geschichtedersyr00baumuoft#page/123) despite the fact that Wright identifies them (https://archive.org/stream/shorthistoryofsy00wrig#page/186). But I should check the GEDSH article again to make sure.

Also CBSC now seems to have only one keyword: http://www.csc.org.il/db/browse.aspx?db=SB&sL=M&sK=Mar%20Aba%20II%20of%20Kashkar&sT=keywords

**Comment by nathangibson** [comment]
OK, I think I'm done disambiguating these. See records on dev server with disambiguation notes:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1086 and http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/307.

Comments welcome @davidamichelson @tacarlson @jsaintlauren @dlschwartz

**Comment by jsaintlauren** [comment]
looks good! 
I added a space in 1086 to the headword
