### ISSUE TITLE
Merge Denhas (person/160 and person/444)?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#531]
@davidamichelson @dlschwartz See any problem with merging http://wwwb.library.vanderbilt.edu/person/160 and http://wwwb.library.vanderbilt.edu/person/444 ? I've checked this out and person/160 cites GEDSH p. 118 + Barsoum, and person/444 cites the same GEDSH article plus Abdisho. None of the secondary lit I've checked suggests 2 Denhas. While Abdisho puts Denha a century earlier, he gives no concrete basis for doing so that would lead me to create another Denha (see note 5 on http://digitale-sammlungen.ulb.uni-bonn.de/content/pageview/33554). Wright (https://archive.org/stream/shorthistoryofsy00wrig#page/218) and Baumstark (220) have identified the Denha mentioned by Abdisho as Denha the disciple of Ishoʿ bar Nun, placing him a century later -- so they also give only 1 relevant Denha candidate.

**Comment by tacarlson** [comment]
It seems to be a little more complicated.  Wright and Baumstark identified the psalm commentary's author as a disciple of Ishobarnun, the Catholicos of the Church of the East.  GEDSH mentions their identification without comment, beyond identifying their source as Yohannan bar Zo'bi and indicating that the commentary was Eastern Syriac.  Barsoum, however, writes of a Syriac Orthodox philosopher, regarding whom Barsoum explicitly cited Wright and even Abdisho for the information about other writings including commentaries on psalms, Gregory Nazianzus, and Aristotle, although Baumstark did not repeat Wright's identification of the author with a disciple of the Catholicos of the Church of the East.  Barsoum even mentioned Yohannan bar Zo'bi's dependence on Denha.


So is this one Denha or two?  The biographical details are probably incompatible, and it's unclear to me whether Barsoum erroneously identified the psalm commentary author Denha with his philosopher-priest, or whether he erroneously claimed a Syriac Orthodox pedigree for an Eastern Syriac author.  But just looking at the citations without consulting biographical details might suggest that they all refer to one author of a psalm commentary.

________________________________

**Comment by nathangibson** [comment]
Thanks for this thorough clarification, @tacarlson ! 

In light of what you've said and after some more investigation of my own, I think we should mark them as "possibly identical." 

Here's what I found: 
1. Abdisho/Assemani, Wright, Duval, Baumstark, and GEDSH all seem to refer to the same Denha. The works they mention as being by this author are essentially the same, particularly the commentary on Psalms, though Assemani puts him a century earlier (his sources are unclear to me, at least). The identification with Denha disciple of Catholicos Isho bar Nun (a century later) hangs on a statement by Yohannan bar Zo'bi recorded in Wright's catalogue (3:1176) that this latter Denha had a commentary on Aristotle's Analytics. This seems a likely, though not watertight, identification. 

2. Barsoum was clearly reading a particular work (a treatise against heretics) of a priest Denha from a manuscript at Midyat. It sounds as if he may get his biographical details about Denha being from the Monastery of St. George from this manuscript. He then identifies this Denha with the one in Wright et al. This latter identification should certainly be questioned. The date should also be questioned.

Thus, I think we should make http://wwwb.library.vanderbilt.edu/person/160 the Denha who authored this treatise against heretics, with a note about the fact that Barsoum's identification might be wrong. We should remove the GEDSH citations from this record. http://wwwb.library.vanderbilt.edu/person/444 should be reserved for the Denha who authored a commentary on the Psalms, etc., and was likely a disciple of Isho bar Nun. Also a note about Barsoum's identification and Assemani's probably incorrect date. The two records should be marked as possibly identical. 

Any objections to this approach?

**Comment by nathangibson** [comment]
I am proceeding with what I outlined above.
