### ISSUE TITLE
no space between author and title in the last line of bibl list of q entries

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#539]
@wsalesky 
As seen here, http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1110 and 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1111 for example, 

 there is a bug pushing the words together on the final entries of bibl lists in Q records making it look like this: J. HabbiBSO: I, 18 instead of J. Habbi BSO: I, 18.

**Comment by wsalesky** [comment]
I made a new issue for this in the app repository.
