### ISSUE TITLE
Reassigning URIs

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#543]
@jedwardwalters Sorry for the URI confusion. Is it all right if I change the URIs 3032 and up in your New Person URIs for Qadishe spreadsheet? Those are the ones you haven't used yet, right?
cc: @dlschwartz

**Comment by jedwardwalters** [comment]
No worries. Yes, that's correct.

**Comment by nathangibson** [comment]
Great, thanks!
