### ISSUE TITLE
Should we merge Paul (http://wwwb.library.vanderbilt.edu/person/1974) with Paul the Apostle (http://wwwb.library.vanderbilt.edu/person/1983) ?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#555]
@jsaintlauren @davidamichelson 
Reassign to me if yes.

**Comment by jsaintlauren** [comment]
Good catch! No please don't merge them.  
But there are problems.. 

This Paul http://wwwb.library.vanderbilt.edu/work/1697 should be linked to Paul the apostle. -- 

This Paul http://wwwb.library.vanderbilt.edu/work/660 in person http://wwwb.library.vanderbilt.edu/person/1974 is a desert father from Enanisho. (It could be Paul) of thebes

**Comment by nathangibson** [comment]
OK, in that case the links in the work records are correct. However, I have added an abstract for person/1974 on the basis of what you said above and I am removing its citation of BHS entry 1626.

**Comment by nathangibson** [comment]
Note that work/660 is not showing up for some strange reason. That issue is here: https://github.com/srophe/srophe-eXist-app/issues/779
