### ISSUE TITLE
Making last batch of new bibls for Fiey

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#570]
@nathangibson Please make bibls from the folder: 2016-08-14 Export in Zotero

Please do this before Rome

Let me know when they are done as I will need to align the new URIs with these Zotero IDs and then find and replace them in the persons records:

Zotero IDs (currently at person/bibl/ptr/@target)
839
841
842
844
845
846
847
848
849
850
851
852
853
854
855
856
857
858
859
860
861
862
863
865
866

**Comment by davidamichelson** [comment]
If you could do this Monday morning your time then I could check it on Monday AM my time

**Comment by davidamichelson** [comment]
Note to self: use this script to fix: https://gist.github.com/davidamichelson/4d87c9740b638441bb120e7b21173c6d

**Comment by nathangibson** [comment]
OK, @davidamichelson , here you go: https://github.com/srophe/srophe-app-data/commit/5d94644f5f402abdbb50846753c353db3639f45b 

These are bibls 2294-2318

**Comment by davidamichelson** [comment]
Thanks!

**Comment by nathangibson** [comment]
Closing this unless you had something more @davidamichelson
