### ISSUE TITLE
Two person/3131 s

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#574]
@jedwardwalters Looks like we have two persons with URI 3131 -- one in saints (https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/saints/tei/3131.xml) and one just in persons (https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/3131.xml). I wonder, is the one in saints supposed to be "3031" instead (which is what the New Person URIs spreadsheet seems to say)? If so do you mind changing it and updating any links? If not, let me know. Thanks!

**Comment by jedwardwalters** [comment]
@nathangibson You're right. It was supposed to be 3031. I fixed it and just put it in a pull request.

**Comment by wlpotter** [comment]
I believe this if fixed; https://syriaca.org/person/3031 is Sinai the Deacon; https://syriaca.org/person/3131 is the record for "The holy fathers and orthodox persons of Palestine who persuaded Epiphanius to perform ordinations in Palestine".
