### ISSUE TITLE
Still needs split

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#580]
<p>
    <idno>http://syriaca.org/person/1115</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1115-2" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Acyndinus,
          Anempodistus, Pegasius, Aphtonius, and Elpidiphorus</persName>
    <persName>GEDSH:</persName>
</p>

**Comment by davidamichelson** [comment]
<p>
    <idno>http://syriaca.org/person/1120</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1120-2" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Adorparwa
          and Mihrnarsai</persName>
    <persName>GEDSH:</persName>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:lang="en-x-gedsh" xml:id="name1120-5">Adōrparwā</persName>
</p>

**Comment by davidamichelson** [comment]
<p>
    <idno>http://syriaca.org/person/1167</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1167-2" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Bassus and
          Suzanne, with Stevin and Longinus</persName>
    <persName>GEDSH:</persName>
</p>

**Comment by davidamichelson** [comment]
<p>
    <idno>http://syriaca.org/person/1232</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1232-3" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Eulogius and the leper</persName>
    <persName>GEDSH:</persName>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1232-2" xml:lang="en-x-gedsh">Ewlōg</persName>
</p>

**Comment by davidamichelson** [comment]
<p>
    <idno>http://syriaca.org/person/1252</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1252-2" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Gregory or
          George, Zwanarse and Yazdapnah</persName>
    <persName>GEDSH:</persName>
</p>

**Comment by davidamichelson** [comment]
<p>
    <idno>http://syriaca.org/person/1378</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1378-2" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Michael and
          his Sister Shiris</persName>
    <persName>GEDSH:</persName>
</p>

**Comment by davidamichelson** [comment]
<p>
    <idno>http://syriaca.org/person/1384</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1384-4" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Miles of Tell Hes and Daniel the Doctor</persName>
    <persName>GEDSH:</persName>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1384-2" xml:lang="en-x-gedsh">Miles</persName>
</p>

**Comment by davidamichelson** [comment]
<p>
    <idno>http://syriaca.org/person/1418</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1418-3" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Posi and his daughter Martha</persName>
    <persName>GEDSH:</persName>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1418-2" xml:lang="en-x-gedsh">Pōsi</persName>
</p>

**Comment by davidamichelson** [comment]
<p>
    <idno>http://syriaca.org/person/1483</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1483-2" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Shirin and her two children</persName>
    <persName>GEDSH:</persName>
</p>

**Comment by davidamichelson** [comment]
<p>
    <idno>http://syriaca.org/person/1705</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1705-3" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Elijah and Theodore</persName>
    <persName>GEDSH:</persName>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1705-2" xml:lang="en-x-gedsh">Ēlīyā w-Theʾōdōrā</persName>
</p>

**Comment by davidamichelson** [comment]
<p>
    <idno>http://syriaca.org/person/1956</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1956-3" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Paesius and Isaiah</persName>
    <persName>GEDSH:</persName>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1956-2" xml:lang="en-x-gedsh">Peʾsīs w-Eshaʿyā</persName>
</p>

**Comment by davidamichelson** [comment]
<p>
                <idno>http://syriaca.org/person/1958</idno>
                <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1958-3" xml:lang="en"
                    resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Pamphilus, Vales,
                    Seleucus, Paulus, Porphyrius, Theophilos, Julianus, and One Egyptian</persName>
                <persName>GEDSH:</persName>
                <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1958-2"
                    xml:lang="en-x-gedsh">Pampīlōs w-Walēs w-Selawqōs w-Pawlōs w-Parpīres
                    w-Theyōfīlōs w-Yulyānōs w-Aghēpṭāyā ḥad</persName>
            </p>

**Comment by davidamichelson** [comment]
<p>
    <idno>http://syriaca.org/person/1990</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1990-3" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Paul, Nilus, Patrimytheas, Elijah</persName>
    <persName>GEDSH:</persName>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1990-2" xml:lang="en-x-gedsh">Pawlōs w-Nīlōs w-Pāṭrīmītēʾās w-Elīyā</persName>
</p>

**Comment by davidamichelson** [comment]
<p>
    <idno>http://syriaca.org/person/2064</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name2064-3" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Heronios</persName>
    <persName>GEDSH:</persName>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name2064-2" xml:lang="en-x-gedsh">Hērōnīyōn w-ʾatthēh</persName>
</p>

**Comment by davidamichelson** [comment]
@jedwardwalters This and issue #581 are the priorities for this week. Perhaps start with the Anonymous issue #581 first.

**Comment by jedwardwalters** [comment]
JW working on http://syriaca.org/person/1115 Acyndinus, Anempodistus, Pegasius, Aphtonius, and Elpidiphorus

**Comment by jedwardwalters** [comment]
JW working on http://syriaca.org/person/1120 Adorparwa and Mihrnarsai

**Comment by jedwardwalters** [comment]
JW working on http://syriaca.org/person/1167 Bassus and Suzanne, with Stevin and Longinus

**Comment by jedwardwalters** [comment]
JW working on http://syriaca.org/person/1232 Eulogius and the leper

**Comment by jedwardwalters** [comment]
JW working on http://syriaca.org/person/1252 Gregory or George, Zwanarse and Yazdapnah

**Comment by jedwardwalters** [comment]
@davidamichelson @jsaintlauren 
Re: http://syriaca.org/person/1378 Michael and his Sister Shiris
The abstract says Michael's sister and then has (Shiris?). So do we not know for sure that this is her name? Should it be anonymous? There's also a note that says "problem entry." How to handle?

**Comment by jedwardwalters** [comment]
JW working on http://syriaca.org/person/1384 Miles of Tell Hes and Daniel the Doctor

Done now. They were already split, but needed cleaning up and ref links.
Miles = http://syriaca.org/person/1384
Daniel + http://syriaca.org/person/1201

**Comment by jedwardwalters** [comment]
JW working on http://syriaca.org/person/1418 Posi and his daughter Martha

Done now. They were already split, but needed cleaning up and ref links.

**Comment by jedwardwalters** [comment]
JW working on: http://syriaca.org/person/1483 Shirin and her two children

**Comment by jedwardwalters** [comment]
JW working on: http://syriaca.org/person/1705 Elijah and Theodore

**Comment by jedwardwalters** [comment]
JW working on: http://syriaca.org/person/1956 Paesius and Isaiah

**Comment by davidamichelson** [comment]
Great work and thank you!

**Comment by jedwardwalters** [comment]
JW working on: http://syriaca.org/person/2064 Heronios

**Comment by davidamichelson** [comment]
@jedwardwalters @nathangibson 

Jamey since we are all flying out to Rome today, could you push whatever you have as a pull request at the end of today and assign it to Nathan to merge please?

Nathan could you merge it (unless a conflict in which case it can wait for me?)

Thanks,
DM

**Comment by nathangibson** [comment]
Sure.

**Comment by jedwardwalters** [comment]
@davidamichelson @nathangibson 
 Sure, will do. I think I will have all of these records split by the end of the day.

**Comment by davidamichelson** [comment]
@jedwardwalters @nathangibson @wsalesky Great, if you do we can include these as well!

**Comment by jedwardwalters** [comment]
JW working on: http://syriaca.org/person/1990 Paul, Nilus, Patrimytheas, Elijah

**Comment by jedwardwalters** [comment]
JW working on: http://syriaca.org/person/1958 Pamphilus, Vales, Seleucus, Paulus, Porphyrius, Theophilos, Julianus, and One Egyptian

**Comment by jedwardwalters** [comment]
Closing this issue! Moved remaining questions to a new issue to make them easier to find.
