### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#582]
@jsaintlauren are there duplicates? If so please let Nathan know which one to merge and deprecate:

Christine Yazdouy - ܟܪܣܛܝܢܐ ܝܙܕܘܝNames: Kresṭīnā YazdūyChristinaKresṭīnā YazdūyChristine YazdouyCHRISTINA (YAZDOÏ)Kresṭīnā Yazdūy from Karka d-Beth Slokh was the daughter of a Zoroastrian governor who was martyred after her marriage.URI: http://syriaca.org/person/1183
2
Christine of Karka d-Beth SlokhNames: YAZDOIIn hagiography: Christine or Yazdoi from Karka d-Beth Slokh was the daughter of a Zoroastrian governor who was martyred after her marriage.URI: http://syriaca.org/person/1521

**Comment by jsaintlauren** [comment]
Yes they are. @nathangibson please merge and deprecate 1521.

**Comment by davidamichelson** [comment]
@nathangibson @wsalesky Something must be off in our redirects on merge records. Person/1521 just gives a 404 and does not redirect.

**Comment by wlpotter** [comment]
@jsaintlauren this is giving that same cardinality error, so I think these were merged. I will check to make sure the XML to see if the records were merged and deprecated.

**Comment by wlpotter** [comment]
These have been properly merged
