### ISSUE TITLE
Martyrs

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#586]
Okay, shall we just delete these?

<p>
    <idno>http://syriaca.org/person/1889</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1889-2" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Martyrs</persName>
    <persName>GEDSH:</persName>
</p>
<p>
    <idno>http://syriaca.org/person/1890</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1890-2" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Martyrs</persName>
    <persName>GEDSH:</persName>
</p>
<p>
    <idno>http://syriaca.org/person/1891</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name1891-2" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Martyrs</persName>
    <persName>GEDSH:</persName>
</p>

**Comment by jsaintlauren** [comment]
Yes  please
