### ISSUE TITLE
Possible Deprecate from Q

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#590]
@jsaintlauren Can we deprecate this:

<p>
    <idno>http://syriaca.org/person/2090</idno>
    <persName xmlns="http://www.tei-c.org/ns/1.0" xml:id="name2090-2" xml:lang="en" resp="http://syriaca.org" syriaca-tags="#syriaca-headword">Book of the
          Governors</persName>
    <persName>GEDSH:</persName>
</p>

**Comment by jsaintlauren** [comment]
Yes please deprecate

**Comment by wlpotter** [comment]
This appears to have been deprecated; I believe this can be closed @jsaintlauren ?
