### ISSUE TITLE
Update Insert for New Headwords

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#592]
@wsalesky Would you please write and run a script that will do the following:

For fn:collection(https://github.com/srophe/persons/blob/master/working-files/newheadwords-h-aug15.xml)//tei:persName[@xml:id="name\d+-h"]

Please insert that persName element into the appropriate person record (the \d+ is the URI number) as the [1] persName (so immediately after the <tei:Person> element).

I have used -h as the xml:id so we don't need to renumber or count

Then could you also write a script to test that no person record has more than one persName[@xml:lang="en"] which has a @syriaca-tags"#syriaca-headword" (using contains to get the different options). If there are still any with two "en" headwords marked I will need to edit them.

Thanks,
Dave

**Comment by davidamichelson** [comment]
If you can post the script please, I'd like to better understand how it works. thanks!

**Comment by nathangibson** [comment]
FYI, I'm currently seeing a number of persons with no English headword (e.g., http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/483/tei).

**Comment by nathangibson** [comment]
I'm supposing this will be fixed on its own when the above data is incorporated.

**Comment by davidamichelson** [comment]
Yes there are 350 records without headwords waiting on an issue script

**Comment by wsalesky** [comment]
New data on this branch:
https://github.com/srophe/srophe-app-data/tree/issue592

There were 336 names inserted.

**Comment by davidamichelson** [comment]
Thanks! Can you post the script please, I want to understand update insert better

**Comment by davidamichelson** [comment]
This is done!

**Comment by wsalesky** [comment]
It is in the srophe xquery folder: insert-new-headwords.xql I think.

**Comment by davidamichelson** [comment]
Thanks!
