### ISSUE TITLE
Pull out the Disambiguation Notes from persons/tei/saints/tei

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#597]
Save them in a gist attached to this issue (and also in the persons repo) and we will edit and reinsert them later.

**Comment by davidamichelson** [comment]
Please then check the disambiguation notes in the the persons/tei directory by hand

Lastly add this one back in.

<note type="disambiguation" source="#bib1117-1">According to Fiey this is not the same as the <persName ref="http://syriaca.org/person/1116">Addai the Chorepiscopus</persName> mentioned in <title ref="http://syriaca.org/work/800">Addai the Chorepiscopus (text)</title>.</note>

**Comment by nathangibson** [comment]
OK, it's here
https://github.com/srophe/persons/blob/master/working-files/q-deleted-disambiguations.xml
and here
https://gist.github.com/nathangibson/3c909bf284f0b0ddf8c943d320077044
