### ISSUE TITLE
URIs for SPEAR factoids

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#615]
@wsalesky As discussed in our meeting today, could you please write a script that will add a uri attribute to each div element. It should use the URI for the conceptual entity of the work from which that data is taken. For the letters, those numbers are in the file number. I'll ask Nathan to create a URI to use for the Chronicle.

**Comment by wsalesky** [comment]
@dlschwartz The files with ids/uris are on this branch:
https://github.com/srophe/srophe-app-data/tree/issue615

Take a look, if it looks good to you, we can merge it into dev and push them to the dev server.

**Comment by dlschwartz** [comment]
Winona, this looks great, thanks. The only thing left is to replace 633 in
the Chronicle of Edessa. That comes from the URI for an edition of the
Chronicle but not from the URI for the conceptual entity. I asked Nathan to
reserve that URI but haven't heard back from him yet. I'll follow up and
get back to you. Thanks!

On Thu, Sep 22, 2016 at 8:40 AM, Winona Salesky <notifications@github.com>
wrote:

> @dlschwartz
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dlschwartz&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=wq8MySGcn_uwZQ_45R3J-AH0tYyVCvajIwyc-7r7J4k&s=E8Aa6etjq6_meUnhcy6WvkD-0VlGTaVMvsPD2EEKQ7Q&e=>
> The files with ids/uris are on this branch:
> https://github.com/srophe/srophe-app-data/tree/issue615
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2Dapp-2Ddata_tree_issue615&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=wq8MySGcn_uwZQ_45R3J-AH0tYyVCvajIwyc-7r7J4k&s=SWnHUxowQKY2kbeEB7RCDkHqI8PldzGjfQpJ9Xe6Df4&e=>
>
> Take a look, if it looks good to you, we can merge it into dev and push
> them to the dev server.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2Dapp-2Ddata_issues_615-23issuecomment-2D248906125&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=wq8MySGcn_uwZQ_45R3J-AH0tYyVCvajIwyc-7r7J4k&s=VSfUgTQ9BE09WCAcwuSl20hQvp0fqAsKLWnMUg50RbY&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzqDKfdKb4-5F9mOBzq1H5L-2D9ApdGItks5qsoU0gaJpZM4KDJ-5FN&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=wq8MySGcn_uwZQ_45R3J-AH0tYyVCvajIwyc-7r7J4k&s=ZXZIA1wJvTlb1Mrc7rB2yvYIHfYAMEp75ZE1Cjayh80&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by nathangibson** [comment]
Chronicle of Edessa is http://syriaca.org/work/119 <http://syriaca.org/work/119>.

**Comment by wsalesky** [comment]
@dlschwartz @nathangibson Why is the Chronicle of Edessa a 'work' uri and the letters are a 'spear' uri? I may have built in some pattern matching on the uri (I will check).

**Comment by wsalesky** [comment]
I have made the change and pushed the data to dev. Please let me know if you encounter any problems. I put the xquery update script here:
https://github.com/srophe/srophe-xQueries/blob/master/create-factoid-uris.xql

**Comment by dlschwartz** [comment]
Good question. Short answer is that we probably need work URIs for the
letters. I assigned these numbers in consultation with Nathan. I think
these work numbers are reserved for the letters. I'm in a mtg now. I'll
have to get back to you.

**Comment by wsalesky** [comment]
Okay. We can discuss it at the next meeting if you like.

**Comment by wsalesky** [comment]
FYI I think this did break some things in SPEAR. Will be working on it today.

**Comment by dlschwartz** [comment]
@wsalesky I have changed the factoid URIs in the TEI for the Chronicle of Edessa from syriaca.org/work to syriaca.org/spear. The Chronicle and the letters are now consistent.

**Comment by wsalesky** [comment]
Opps, I think I may have messed up the URIs for the Chronicle. They currently contain '/work/' not '/spear/' this most likely happened when I renumbered them. Should I run a quick find and replace?

**Comment by dlschwartz** [comment]
Yeah, the factoid divs should have a /spear/ URI. Thanks Winona.


On Tue, Oct 11, 2016 at 9:04 AM, Winona Salesky <notifications@github.com>
wrote:

> Opps, I think I may have messed up the URIs for the Chronicle. They
> currently contain '/work/' not '/spear/' this most likely happened when I
> renumbered them. Should I run a quick find and replace?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2Dapp-2Ddata_issues_615-23issuecomment-2D252926122&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=dW2Mt8XmusY-vfeAY8zvMIx5meBFDrFVoQMMUhmM9W4&s=QKdJ0n_i3-Xhoh1XPCww0LFubqCeoCCn9LxdD5jh86I&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzqTrsWpKylJELRs1YcyCE7o7Af64ks5qy5dRgaJpZM4KDJ-5FN&d=CwMFaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=dW2Mt8XmusY-vfeAY8zvMIx5meBFDrFVoQMMUhmM9W4&s=RAwPJLqv3iRaOjlvvWxffFBYeTV0JO-EEWLCZ5srYXw&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by wsalesky** [comment]
Okay, fixed. Sorry about that.
