### ISSUE TITLE
URI for the Chronicle of Edessa

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#616]
@nathangibson Could you please create a URI for the conceptual entity that is the Chronicle of Edessa and provide that to @wsalesky? I don't want to accidentally claim a URI you're using elsewhere.

**Comment by dlschwartz** [comment]
@wsalesky Can you please make one more change to these URIs? I forgot to mention that the URI numbering should simply run sequentially spear/119-1, spear/119-2, spear/119-3, etc. The 119-2-2, etc. is unnecessary. Thanks.

**Comment by wsalesky** [comment]
Updated data: 
https://github.com/srophe/srophe-app-data/tree/issue616

If it looks good we can merge it into the dev branch.

**Comment by dlschwartz** [comment]
Perfect. Thanks @wsalesky! We're god to merge.

**Comment by wsalesky** [comment]
Done!
