### ISSUE TITLE
SPEAR Relation fix

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#625]
@wsalesky I have run into a problem with the way I've used the type attribute in encoding relationships in SPEAR. I'm hoping you can run a script on all SPEAR TEI data to get me back on track. I need the type attribute for something other than what I've used it for. It will work just fine to put that information on the ana attribute instead, freeing up the type attribute for what I need. Could you please run a script changing all of the div-listRelation-relation (at)type to (at)ana instead? Thanks so much!

**Comment by wsalesky** [comment]
Sure! Can you paste in a sample div, just so I know I have all the xpaths correct?

**Comment by davidamichelson** [comment]
Just an fyi @dlschwartz you don't need a script for this, you can do this quickly using Oxygen's advanced find and replace. Just search for the attribute name (limiting your search to attribute names in the XML options) and limit your search by path to the path that you want. Then do find and replace.

**Comment by wsalesky** [comment]
@davidamichelson is right of course. It didn't even occur to me to just use Oxygen. @dlschwartz  Let me know if you would like me to do it, or if you want to take care of it.

**Comment by dlschwartz** [comment]
@wsalesky I'll try Oxygen and get back to you. @davidamichelson am I right that I would have to do this on each of the 60 or so files? In other words, is there a way to run this on a group of files without a script?

**Comment by wsalesky** [comment]
@dlschwartz You can do a find and replace across files. Using the 'Find menu' there is an option for 'Find/Replace in Files...'

**Comment by dlschwartz** [comment]
Thanks @wsalesky!  Cool @davidamichelson. I've not really played around with the xpath feature in find and replace. Thanks for suggesting it.

**Comment by davidamichelson** [comment]
@dlschwartz you can use the "find and replace in files" to do multiple files in the same way

**Comment by dlschwartz** [comment]
Done and pushed! Everyone sing along now, "I get by with a lot of help from my friends"
