### ISSUE TITLE
Keywords in SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#627]
@wsalesky We discussed the issue of keyword tagging in SPEAR recently. I have looked more closely and I think it is preferable to put all keyword tagging onto the event element or onto the person element. Right now we have ref elements with target attributes spread throughout person and event factoids. 

Would you be able to write a script that would find the ref elements with target attributes nested inside each person element, delete the ref element and target attribute but pull the attribute values of those target attributes, and make them the attribute values of a ref attribute on the person element? As a heads up, in many cases this would produce ref attributes with multiple attribute values. We would also need to do the same for all ref elements with target attributes in event elements. 

I know this is complicated. We can discuss in our meeting tomorrow. Thanks Winona.

**Comment by dlschwartz** [comment]
@wsalesky I hope you haven't done this yet! Nathan mentioned this in our meeting but it didn't register at the time. TEI doesn't allow a ref attribute on a person element. Could you instead simply move all ptr targets from the text into a one self closing element with multiple values (if necessary) immediately after the person element or event element? Thanks!

**Comment by wsalesky** [comment]
Can we put this one on the agenda for our next meeting. I have some questions.

**Comment by dlschwartz** [comment]
Yes, that's fine.

**Comment by wsalesky** [comment]
Hi Dan, 
Can we use this one as an example?
```
<div><!-- EDUCATION -->
                <listPerson>
                    <person> <!-- No ptr target with keyword-->
                        <persName ref="http://syriaca.org/person0001"/>
                        <education ref="http://syriaca.org/keyword">
                            <note type="desc">
                                Text including the following elements only: 
                                <date/><!-- Could also be choice followed by reg&orig. -->
                                <persName ref="http://syriaca.org/keyword">
                                    Libanius
                                </persName>
                                <placeName ref="http://syriaca.org/keyword">
                                    Antioch
                                </placeName>
                                <orgName>
                                    School of Edessa
                                </orgName>
                            </note>
                        </education>
                    </person>
                </listPerson>
                <bibl type="primary"><ptr target="http://syriaca"/><citedRange unit="pp">1</citedRange></bibl>
            </div>
```
Would it look like this:

```
<div><!-- EDUCATION -->
                <listPerson>
                    <person> <!-- No ptr target with keyword-->
                        <ptr target="http://syriaca.org/person0001 http://syriaca.org/keyword"/>
                        <education>
                            <note type="desc">
                                Text including the following elements only: 
                                <date/><!-- Could also be choice followed by reg&orig. -->
                                <persName ref="http://syriaca.org/keyword">
                                    Libanius
                                </persName>
                                <placeName ref="http://syriaca.org/keyword">
                                    Antioch
                                </placeName>
                                <orgName>
                                    School of Edessa
                                </orgName>
                            </note>
                        </education>
                    </person>
                </listPerson>
                <bibl type="primary"><ptr target="http://syriaca"/><citedRange unit="pp">1</citedRange></bibl>
            </div>
```

**Comment by dlschwartz** [comment]
This: 
`<div uri="http://syriaca.org/spear/119-3">
                <listPerson>
                    <person>
                        <state type="office">
                            <desc>
                                <persName ref="http://syriaca.org/person/2302"> Severus </persName>
                                was <ref target="http://syriaca.org/keyword/emperor"> emperor </ref>
                                <placeName ref="http://syriaca.org/place/166"> Rome </placeName>.
                            </desc>
                        </state>
                    </person>
                </listPerson>
                <bibl type="primary">
                    <ptr target="http://syriaca.org/bibl/633"/><citedRange unit="pp">1</citedRange></bibl>
                <bibl type="primary">
                    <ptr target="http://syriaca.org/bibl/657"/><citedRange unit="part">8</citedRange></bibl>
            </div>`

Would become this:
`<div uri="http://syriaca.org/spear/119-3">
                <listPerson>
                    <person>
                        <ptr target="http://syriaca.org/keyword/emperor"/>    
                        <state type="office">
                            <desc>
                                <persName ref="http://syriaca.org/person/2302"> Severus </persName>
                                was emperor of
                                <placeName ref="http://syriaca.org/place/166"> Rome </placeName>.
                            </desc>
                        </state>
                    </person>
                </listPerson>
                <bibl type="primary">
                    <ptr target="http://syriaca.org/bibl/633"/><citedRange unit="pp">1</citedRange></bibl>
                <bibl type="primary">
                    <ptr target="http://syriaca.org/bibl/657"/><citedRange unit="part">8</citedRange></bibl>
            </div>`

**Comment by dlschwartz** [comment]
Oops, I thought that would come out properly nested. How did you do that?

**Comment by wsalesky** [comment]
Use the 'code' formatting option. Looks like '<>' in the menu.

**Comment by wsalesky** [comment]
Thanks!

**Comment by dlschwartz** [comment]
I clicked the button. Must have done something wrong. It take it that gets things sorted. Thanks so much Winona!

**Comment by wsalesky** [comment]
No problem, it actually comes out nicely formatted in the email! I will run the script today.

**Comment by dlschwartz** [comment]
Thanks Winona!

On Thu, Nov 10, 2016 at 10:44 AM, Winona Salesky <notifications@github.com>
wrote:

> No problem, it actually comes out nicely formatted in the email! I will
> run the script today.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2Dapp-2Ddata_issues_627-23issuecomment-2D259741544&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=6U85TouIG02OYTNR1tewtXs8Gtofi1tylATSgOlaLKY&s=MiJX_-u9NtVm-cYpcifLDUUZuY-x-PxKSD_NnIMYngE&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzm5CymgLnX0fSUbSTEfqE9s10Ip7ks5q80oBgaJpZM4KgSQI&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=6U85TouIG02OYTNR1tewtXs8Gtofi1tylATSgOlaLKY&s=wNh2sZ8Ha5C3FDRF75MNckExKNRGdKMxmSV5MqfzN08&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by wsalesky** [comment]
Dan, it is easy to run an xquery to add the ptr/@target, it is not possible to run an xquery to replace the existing ref elements with just text nodes.
i.e.
`<ref target="http://syriaca.org/keyword/emperor"> emperor </ref>`
can not be replaced with 
` emperor `

 We may have to run some manual find and replaces...

**Comment by dlschwartz** [comment]
Winona, that is just fine! As you know, I have to re-work the person factoids anyway. If you have added the ptr targets to all the files, you should just mark this issue as closed and I'll take over. Thanks so much!

**Comment by wsalesky** [comment]
Okay, still testing the script to make sure we have not unpleasant surprises! Will post the new data soon.

**Comment by wsalesky** [comment]
@dlschwartz, this branch has the updated data, if you can take a look at it and make sure it looks okay before I merge it into the dev branch that would be great. 
https://github.com/srophe/srophe-app-data/tree/issue627

**Comment by dlschwartz** [comment]
This looks great Winona! Please merge. Thanks so much.

**Comment by wsalesky** [comment]
Done.
