### ISSUE TITLE
Life of Theodosius of Jerusalem + Monk Romanus

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#632]
Trying to incorporate the following note from Zanetti: 

Work: http://syriaca.org/work/928
text published in 2008 : see https://books.google.be/books/about/The_Lives_of_Peter_the_Iberian_Theodosiu.html?id=tSq1wuai-XUC&redir_esc=y

There are several issues, most of which I can resolve. 

But I need your input @jsaintlauren and/or @davidamichelson on the following (and @dlschwartz on n. 3):
1. Should this edition/translation also be added to http://syriaca.org/work/557? The prologues seem to match. 
2. Zanetti has "ܬܐܘܣܣܝܘܣ" for Theodosius in the prologue of http://syriaca.org/work/557, but Horn and Brooks both have "ܬܐܘܕܘܣܝܘܣ". OK if I correct it?
3. I was trying to find the "Monk Romanus" in SBD, since it should also cite this item. I didn't manage to identify him in a quick search of Qadishe. Is he there? And @dlschwartz is the archimandrite Severus mentions (http://syriaca.org/person/2743) the same?  Compare https://archive.org/stream/p2selectletterss02seveuoft#page/90/mode/2up with https://books.google.be/books?id=tSq1wuai-XUC&lpg=PP1&hl=nl&pg=PA295#v=onepage&q&f=false.

**Comment by nathangibson** [comment]
These are the changes I'm asking about above: https://github.com/srophe/srophe-app-data/commit/fd546744b2b9167a43dfe2b7127de142216a6c44

Plus if Romanus is a match I would add a citation to http://syriaca.org/person/2743 and an attestation/commemoration relation from  http://syriaca.org/work/557 to him.

**Comment by jsaintlauren** [comment]
Hi Nathan!
I am sorry that I am just now responding.

1. Yes, please do add this edition to work 557.

2.  Yes please correct the spelling of Theodosius.

3.  Please create an entry for the monk Romanus.  I can write the
description if you assign it in github back to me. Thanks!

**Comment by jsaintlauren** [comment]
I meant to say that if person 2743 is the same Romanus, please cross list
in Qadishe.
You might add this quotation from Horn's introduction, p liv  as a
definition: "Under the Empress Eudocia's patronage, Romanus had founded an
Anti-Chalcedonian monastery at Eleutheropolis."

**Comment by nathangibson** [comment]
Great, thanks @jsaintlauren! 

@dlschwartz What do you think of the identity of this Romanus with http://syriaca.org/person/2743?

**Comment by dlschwartz** [comment]
Sorry for the slow reply Nathan. We are dealing with two different
Romanuses. Brock & Fitzgerald in "Two Early Lives of Severus" (p. 87, n.
215; and p. 116, section 36 and n. 80) distinguish between the Romanus who
founded the monastery in Palestine to uphold non-Chalcedonianism and
Romanus "the father of the monks." They direct the reader to Horn and
Phenix, pp. 295-301 for the father of the monks.

On Mon, Oct 31, 2016 at 10:19 AM, nathangibson <notifications@github.com>
wrote:

> Great, thanks @jsaintlauren
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jsaintlauren&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=1mkHYOjTgi43uNt8CxBe_OUBIv9V-OjpGfi4OaaUJGU&s=SLy5TapjfTQyevs9U1VicRi-WYcaIthMgz3cdGuVSvM&e=>!
>
>
> @dlschwartz
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dlschwartz&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=1mkHYOjTgi43uNt8CxBe_OUBIv9V-OjpGfi4OaaUJGU&s=Yl0ZijkQivzRZk_aHf8ulqS8fcZ5wJZ-f5RuDDPZbZo&e=>
> What do you think of the identity of this Romanus with
> http://syriaca.org/person/2743
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__syriaca.org_person_2743&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=1mkHYOjTgi43uNt8CxBe_OUBIv9V-OjpGfi4OaaUJGU&s=X9j9NGSCZIaOLhQm9spQizda_Ytt2FLqoeUEJj_F4Ao&e=>
> ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2Dapp-2Ddata_issues_632-23issuecomment-2D257322842&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=1mkHYOjTgi43uNt8CxBe_OUBIv9V-OjpGfi4OaaUJGU&s=HoahsW-bSRev1x4K_fs0m3Wk8JJRJAqfTGv21IDKxBY&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzldXtLjyaWkLg0PxmXD1xTap87Epks5q5gcPgaJpZM4KjTuG&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=1mkHYOjTgi43uNt8CxBe_OUBIv9V-OjpGfi4OaaUJGU&s=tXUx0YMcjVLYJAK-UL3KViolhHI8jQiKkxIFSFU0YjI&e=>
> .
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by dlschwartz** [comment]
Wait, I think I haven't had enough coffee yet this morning and I read this
wrong! These are indeed the same Romanus. Not sure what I was thinking.
Please confirm by looking at Brock and Fitzgerald but I believe these are
the same Romanus.

On Mon, Oct 31, 2016 at 11:27 AM, Daniel Schwartz <daniel.schwartz@tamu.edu>
wrote:

> Sorry for the slow reply Nathan. We are dealing with two different
> Romanuses. Brock & Fitzgerald in "Two Early Lives of Severus" (p. 87, n.
> 215; and p. 116, section 36 and n. 80) distinguish between the Romanus who
> founded the monastery in Palestine to uphold non-Chalcedonianism and
> Romanus "the father of the monks." They direct the reader to Horn and
> Phenix, pp. 295-301 for the father of the monks.
>
> On Mon, Oct 31, 2016 at 10:19 AM, nathangibson <notifications@github.com>
> wrote:
>
>> Great, thanks @jsaintlauren
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jsaintlauren&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=1mkHYOjTgi43uNt8CxBe_OUBIv9V-OjpGfi4OaaUJGU&s=SLy5TapjfTQyevs9U1VicRi-WYcaIthMgz3cdGuVSvM&e=>!
>>
>>
>> @dlschwartz
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_dlschwartz&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=1mkHYOjTgi43uNt8CxBe_OUBIv9V-OjpGfi4OaaUJGU&s=Yl0ZijkQivzRZk_aHf8ulqS8fcZ5wJZ-f5RuDDPZbZo&e=>
>> What do you think of the identity of this Romanus with
>> http://syriaca.org/person/2743
>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__syriaca.org_person_2743&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=1mkHYOjTgi43uNt8CxBe_OUBIv9V-OjpGfi4OaaUJGU&s=X9j9NGSCZIaOLhQm9spQizda_Ytt2FLqoeUEJj_F4Ao&e=>
>> ?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_srophe_srophe-2Dapp-2Ddata_issues_632-23issuecomment-2D257322842&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=1mkHYOjTgi43uNt8CxBe_OUBIv9V-OjpGfi4OaaUJGU&s=HoahsW-bSRev1x4K_fs0m3Wk8JJRJAqfTGv21IDKxBY&e=>,
>> or mute the thread
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEwNzldXtLjyaWkLg0PxmXD1xTap87Epks5q5gcPgaJpZM4KjTuG&d=CwMCaQ&c=ODFT-G5SujMiGrKuoJJjVg&r=QzRmQWHC9YV0c5AgrobproqvWFdcgVpw66BsP8UwAQ0&m=1mkHYOjTgi43uNt8CxBe_OUBIv9V-OjpGfi4OaaUJGU&s=tXUx0YMcjVLYJAK-UL3KViolhHI8jQiKkxIFSFU0YjI&e=>
>> .
>>
>
>
>
> --
> Dr. Daniel L. Schwartz
> Associate Professor of History
> Associate Director of the Initiative for Digital Humanities, Media, and
> Culture <http://idhmc.tamu.edu/>
>
> Texas A&M University
> 4236 TAMU
> College Station, Texas 77843-4236
>
> *Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
> Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
> Studies, 2013)
> http;//syriaca.org <http://syriaca.org/>
>



-- 
Dr. Daniel L. Schwartz
Associate Professor of History
Associate Director of the Initiative for Digital Humanities, Media, and
Culture <http://idhmc.tamu.edu/>

Texas A&M University
4236 TAMU
College Station, Texas 77843-4236

*Paideia and Cult <http://chs.harvard.edu/CHS/article/display/5813>:
Christian Initiation in Theodore of Mopsuestia* (Center for Hellenic
Studies, 2013)
http;//syriaca.org <http://syriaca.org/>

**Comment by nathangibson** [comment]
Thanks, @dlschwartz. I don't have access to [Brock and Fitzgerald] (http://online.liverpooluniversitypress.co.uk/doi/book/10.3828/978-1-84631-882-5) through Vanderbilt but I am ordering a scan. If someone else has access and wants to check it, let me know.

**Comment by nathangibson** [comment]
No problem at all @dlschwartz! And thanks for the scan.

**Comment by nathangibson** [comment]
OK, @jsaintlauren, can you take a look at the following and close this issue if it's satisfactory?
http://wwwb.library.vanderbilt.edu/work/928
http://wwwb.library.vanderbilt.edu/work/557
http://wwwb.library.vanderbilt.edu/person/2743
http://wwwb.library.vanderbilt.edu/person/39
http://wwwb.library.vanderbilt.edu/person/58

**Comment by jsaintlauren** [comment]
Looks great, thanks!
