### ISSUE TITLE
BHSE/Qadishe/Bibl records for approval

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#635]
@davidamichelson Here are some records for production release:
Peter the Iberian, Theodosius of Jerusalem, and the Monk Romanus (suggested by Zanetti, already approved by @jsaintlauren)
http://wwwb.library.vanderbilt.edu/work/928
http://wwwb.library.vanderbilt.edu/work/557
http://wwwb.library.vanderbilt.edu/person/2743
http://wwwb.library.vanderbilt.edu/person/39
http://wwwb.library.vanderbilt.edu/person/58

To which I should also add (not yet approved by @jsaintlauren):
http://wwwb.library.vanderbilt.edu/person/680
http://wwwb.library.vanderbilt.edu/bibl/1703
http://wwwb.library.vanderbilt.edu/bibl/2325

Sharbel, et al (suggested by Minov, needs to be approved by you and/or @jsaintlauren ?):
http://wwwb.library.vanderbilt.edu/work/225
http://wwwb.library.vanderbilt.edu/bibl/2324
http://wwwb.library.vanderbilt.edu/person/1454

**Comment by davidamichelson** [comment]
Approved.
