### ISSUE TITLE
Several SBD records show blank headwords

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#636]
This is due to an additional empty persName element with syriaca-headword:

http://syriaca.org/person/2804
http://syriaca.org/person/1899
http://syriaca.org/person/2802
http://syriaca.org/person/2800
http://syriaca.org/person/2806

**Comment by nathangibson** [comment]
@davidamichelson I corrected the data (except 1899 which is a different issue). Can you approve these new records? https://github.com/srophe/srophe-app-data/commit/0269aadc8fc95f0b2a8de2e4c06c5d2f9b0fb254

**Comment by nathangibson** [comment]
OK, I've corrected 1899 as well.

**Comment by davidamichelson** [comment]
I approve this, note that this is also a change in record data/manuscripts/tei/87.xml please copy that one as well.

**Comment by nathangibson** [comment]
Closing this but not copying the ms record since mss are not on master branch.
