### ISSUE TITLE
Rupil , the monk

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#638]
extra space before comma

**Comment by davidamichelson** [comment]
Same with 
Constantine , bishop of Edessa - ܩܘܣܛܢܛܝܢ ܕܐܘܪܗܝNames: Constantine , bishop of Edessa Constantine of EdessaAthanasiusCONSTANTINConstantine of EdessaConstantine, bishop ...URI: http://syriaca.org/person/126

**Comment by wlpotter** [comment]
There were only 11 instances of spaces before commas in persons records, so I deleted them by hand.
