### ISSUE TITLE
Expedited approval for Zanetti changes

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#640]
@davidamichelson Can you approve the following records in this commit and send them to master? https://github.com/srophe/srophe-app-data/commit/e681029346df5741e56faf572b7ee392de466349

http://wwwb.library.vanderbilt.edu/bibl/2326
http://wwwb.library.vanderbilt.edu/person/1661
http://wwwb.library.vanderbilt.edu/work/251
http://wwwb.library.vanderbilt.edu/work/975
http://wwwb.library.vanderbilt.edu/work/355

**Comment by davidamichelson** [comment]
These are approved. Please push to production.
