### ISSUE TITLE
Getting Syriac title from colophon

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#657]
For http://syriaca.org/manuscript/25#a1, I can construct an English title for the compilation ("Titus, and Clemens, and the Caesarean [Eusebius]") from Wright's translation of the colophon (II:633). But in the TEI, the Syriac for this is in the colophon (addition1). How should I reference the Syriac title equivalent in the msItem?

#649

**Comment by davidamichelson** [comment]
Add as final rubric of the A level item.
