### ISSUE TITLE
Person aggregation with test factoids

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#658]
@wsalesky I added the following file: https://github.com/srophe/srophe-app-data/blob/dev/data/spear/tei/Pers_Element_Testing.xml. It has test examples of all the different types of person factoids. They all refer to person/3064 (an individual) and person/3115 (an anonymous group). The resulting aggregation pages for these two URI (links below) don't work. I'm not sure what I did wrong though. Perhaps you could let me know what I need to do differently. Thanks!

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/3064

http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/3115

**Comment by wsalesky** [comment]
I suspect it is because there are no uris on the divs. They are necessary.

**Comment by dlschwartz** [comment]
Of course! I'll try again. Thanks.

**Comment by dlschwartz** [comment]
@wsalesky The pages are working now but I don't think everything is showing up. I'll make some issues later. I have to get ready for class now. Thanks.

**Comment by wsalesky** [comment]
Okay. Let me know what is missing and we will go from there.

**Comment by dlschwartz** [comment]
The following do not appear in the aggregation visualization. I've put the prefered label and, where I thought it might not be obvious, I've included enough TEI for you to locate things easily. 
Birth date:
Birth place:
Death date:
Death place:
Education:
Citizenship: (element: nationality)
Place of residence: 
Language known: (element: langKnowledge)
Social rank: (element: socecStatus)
Physical trait: (trait type="physical")
Gender: (trait type="gender")
Ethnic label: (trait type="ethnicLabel")

Also, can we change the one label from "Mental:" to "Mental state:"? 

Thanks Winona! Please let me know if questions arise.

**Comment by wsalesky** [comment]
How would you like persGroup/persName to display? See 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/3115

**Comment by dlschwartz** [comment]
For named individuals (i.e. http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/2201) things look good as they are. Am I right that the "Abgar VIII" comes from the SBD headword. Can we do the same for anonymous/i?

If you look at the aggregation pages for 2201, 3064, and 3115, you'll notice that sometimes the name variants are grouped at the top and sometimes they are dispersed throughout the person factoids. I think the types of factoids should be grouped together and ordered as follows:
Name variants
Sex
Birth date
Birth place
Death date
Death place
Social rank
Occupation
Citizenship
Place of residence
Sanctity
Education
Language known
Gender
Ethnic label
Mental state
Physical trait
(After social rank, this ordering becomes a bit arbitray and I'm not too concerned about it. Very few people will have as many of these items as the tests, 3115 and 3064. I've given an order for what I hope are all options to make things easier for you. If this presents and difficulties, please let me know.)

Finally, we have a typo. We should have "Name variants" instead of "Name varients".

This is looking great Winona! Thank you.

**Comment by wsalesky** [comment]
Okay. Updated:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/3115

**Comment by wsalesky** [comment]
Except I don't think I understand where you want the anonymous/i changed?

**Comment by wsalesky** [comment]
Okay. I will make the change.

**Comment by dlschwartz** [comment]
Can we group multiple occurences of the same tyoe of data in this way?

Name variant:
     John
     Jonathan

**Comment by wsalesky** [comment]
Grouped:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/aggregate.html?id=http://syriaca.org/person/3064

**Comment by dlschwartz** [comment]
This looks great Winona. Thanks. My last tweak would be spacing. It would be good to keep greater spacing between the different types of data, with a relatively tighter spacing between multiple instances of that type of data. Does that make sense? In other words, the name variants would be closer together as a group with a greater spacing between the name variants and sex. This is really looking great.

**Comment by dlschwartz** [comment]
Just to be clear, the "greater" and "lesser" above is relative. I don't think we necessarily need more spacing between name and sex than is currently there. 

I think I need to go home and go to sleep now. ;)

**Comment by wsalesky** [comment]
@dlschwartz  - Okay, how does it look now? If the spacing is good, you can close this issue.

**Comment by dlschwartz** [comment]
That looks great. Thank you!
