### ISSUE TITLE
en-xsrp1 tag

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#659]
@davidamichelson @wsalesky We have 471 persons with persNames that have the language tag "en-xsrp1". It seems to me this should be "en-x-srp1" if this is intended as a private use script tag, right? Should I run a find-replace on this?

**Comment by wsalesky** [comment]
It does seem like it should be changed.

**Comment by davidamichelson** [comment]
yes. agree!

**Comment by nathangibson** [comment]
This does affect Gazetteer data. What's the procedure?

**Comment by tacarlson** [comment]
I would be fine with you testing your script on a local copy of all the Gazetteer data, confirming that it only affects the desired records and only in the desired way, and then pushing the results to GitHub.

The script should not only replace xsrp1 with x-srp1 but should also add an entry in the change-log, but only on those records where a change was made.

Please let me know when the results are pushed so I can inspect them.

**Comment by nathangibson** [comment]
Results have been pushed in this commit: https://github.com/srophe/srophe-app-data/commit/9f610cc42380cd4eb382d0e1cee390f46ac2a06a

This did change the order of namespaces on the root TEI element, but I assume that doesn't matter.

**Comment by nathangibson** [comment]
@wsalesky You can close this once the production server has been updated with the records that were modified in https://github.com/srophe/srophe-app-data/commit/32279300b63078d128e81cbc9b788fe838682051. Thanks!

**Comment by wsalesky** [comment]
Updated.
