### ISSUE TITLE
Standardizing sex element

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#660]
@jsaintlauren @davidamichelson 
I'm trying to clean up some data items so that the advanced (faceted) browse can be rolled out to production. https://github.com/srophe/srophe-eXist-app/issues/891

One is the sex element. I have two questions:

1. There are a few male-female pairs that still have "M,F" as sex/@value. These seem to be records for males that just weren't adequately cleaned up. In one case, a female record still needed to be created. Do you approve of the changes I've made here? https://github.com/srophe/srophe-app-data/commit/8e05fc6816e2153b6203a2ae709790e3ab356310. If so, @davidamichelson do you want to push them to production?

The pairs are 
Mari (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1360) and his wife Martha (http://syriaca.org/person/1369)
Posi (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1418) and his daughter Martha (http://syriaca.org/person/1370)
Sharbel (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1454) and his sister Babai (http://syriaca.org/person/1151)
Michael (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1378) and his sister Sharis (?) (new record: http://wwwb.library.vanderbilt.edu/person/3153). 

2. There are also 2 groups of unnamed saints who are designated "M,F". Do we want to simply delete the sex element for these, or is it important to keep the information that these are mixed-gender groups? 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1442
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1391

**Comment by nathangibson** [comment]
Also standardized the case ("Female" > "female") on http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1877, which could be pushed to production as well.

**Comment by nathangibson** [comment]
Last one: @davidamichelson @jsaintlauren How should we handle http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1584, which is currently : 
`<sex xml:lang="en" value="F E" source="#bib1584-3">female, but thought by her associates to be a eunuch</sex>`
It's a nice description but it messes up the faceting. We could do 
`<sex xml:lang="en" value="F" source="#bib1584-3">female</sex>`
`<sex xml:lang="en" value="E" source="#bib1584-3">eunuch</sex>`
and leave it up to the hagiography description to give the explanation.

**Comment by jsaintlauren** [comment]
I approve of these changes. Thanks, Nathan.  Let's keep Anastasia as a
female, but have the eunuch in the description of her.

**Comment by nathangibson** [comment]
OK, I've changed Anastasia to just "female", but I noticed two other issues in the process. 
 1. The abstract calls her "Athanasia" instead of "Anastasia". Is Athanasia also attested or is this simply a mistake?
 2. The abstract links Athanasia to http://syriaca.org/person/3003 (Candida). Is this a mistake?

**Comment by nathangibson** [comment]
I've also deleted the sex elements for the two groups, so the only remaining things left are the two questions above about Anastasia and pushing these records to production if @davidamichelson approves.

**Comment by davidamichelson** [comment]
@nathangibson I have fixed lowercase "f" to uppercase "F" in records:
 data/persons/tei/saints/tei/1624.xml
+1 −1 data/persons/tei/saints/tei/1695.xml
+1 −1 data/persons/tei/saints/tei/1716.xml
+1 −1 data/persons/tei/saints/tei/1720.xml
+1 −1 data/persons/tei/saints/tei/1787.xml
+1 −1 data/persons/tei/saints/tei/1878.xml
+1 −1 data/persons/tei/saints/tei/1882.xml
+1 −1 data/persons/tei/saints/tei/2112.xml
+1 −1 data/persons/tei/saints/tei/2114.xml
+1 −1 data/persons/tei/saints/tei/2119.xml

**Comment by davidamichelson** [comment]
I have moved the question of Eunuchs to a new issue, see issue #682.

**Comment by davidamichelson** [comment]
I have moved the question of Anastasia to a new issue, see issue #683

**Comment by davidamichelson** [comment]
@nathangibson I approve the standardization. Please move all records to Master as is. We can sort out the Eunuchs and Anastasia later.

**Comment by nathangibson** [comment]
Great, thanks!

**Comment by nathangibson** [comment]
I have merged these to master (except person/1584), including the ones you did @davidamichelson .
