### ISSUE TITLE
Duplicate Works

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#662]
are Book of the Superiors (text)URI: http://syriaca.org/work/1842 
and The Book of Governors (text)URI: http://syriaca.org/work/1290 

The same work?

**Comment by nathangibson** [comment]
They are not the same. Work/1842 is an excerpt from work/1290. 

I have made some changes to the affected records, most notably changing the headword title of work/1842 to "Babai the Great (text)" and adding the title from Mingana's catalogue. I also added a relation showing that this is part of the larger work/1290. 

You can see all my changes at:
https://github.com/srophe/srophe-app-data/commit/cb3679431e241422bd45563eeb65f11962cd9675
https://github.com/srophe/srophe-app-data/commit/452c452fa6b568cfe412c6d091e0123e8b3dde2a
https://github.com/srophe/srophe-app-data/commit/e5a1112980627c0494b56634dfb291382fcac09e

**Comment by nathangibson** [comment]
If you approve, can you push them to production please?

cc: @jsaintlauren

**Comment by davidamichelson** [comment]
I approve this.
