### ISSUE TITLE
saints needing separate URIs

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#664]
I found another pair of saints sharing a URI: http://syriaca.org/person/1705. I thought we had caught all of these. ̈If someone could let me know when we have two URIs for these individuals I would appreciate it. Thanks!

**Comment by nathangibson** [comment]
I will split them. We don't need to preserve any info about them originally a group, right?

**Comment by nathangibson** [comment]
Actually, they have already been split, just haven't been pushed to production. 
Elijah is http://wwwb.library.vanderbilt.edu/person/1705
Theodore is http://wwwb.library.vanderbilt.edu/person/3140 

@davidamichelson Can we approve these for production?

**Comment by dlschwartz** [comment]
Sorry I didn't think to check that. I thought everything had already been pushed. Thank you!
