### ISSUE TITLE
English headword not displaying for person/2032

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#667]
We have two English names labeled "#syriaca-headword". The persName with xml:lang "en" has no text node. There is, however, an option with xml:lang "en-x-gedsh" but that does not display. I'm not sure if this is a data problem for @jsaintlauren or an app problem for @wsalesky. Thanks.

**Comment by wsalesky** [comment]
Looks like an app problem. I will look tonight.
