### ISSUE TITLE
https://syriaca.org/person/2124  empty record  

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#67]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2124

**Comment by wlpotter** [comment]
https://syriaca.org/person/2124 is missing data. There is a note on this record that reads, 

>No Zanetti file - where did data come from?

Perhaps delete it?

**Comment by wlpotter** [comment]
This record has also been properly deprecated (cf. https://github.com/srophe/srophe-app-data/wiki/Deprecated-Records).

Unlike #59, I don't think we want to redirect this record anywhere? It does not appear in search or browse, so I believe this issue is resolved.
