### ISSUE TITLE
work/835 and person/2130

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#670]
@jsaintlauren That person/2130 "Timothy" ought to be seen as the person commemorated in work/835 "Tribunus" must be a mistake in our data. J of E makes no reference to his Tribunus being a martyr (which is true of Timothy according to the identity statement given) and there is no indication of a connection to a story told by Eusebius. J of E's references to stylite saints also make it difficult to connect Tribunus to someone writing as early as Eusebius.

**Comment by nathangibson** [comment]
Agreed. The account of Tribunus mentions pro-Chalcedonians, so obviously post Eusebius and not a martyr under Dionysius. 
We simply need to split person/2130 and point work/835 to the new record, correct?
https://archive.org/stream/patrologiaorient18pariuoft#page/660/mode/2up
https://archive.org/stream/martyrspalestine00euseuoft#page/n29/mode/2up

**Comment by dlschwartz** [comment]
Sorry, I forgot I had already written this up. By split person/2130, do you mean simply remove work/835 from person/2130 and create a new record for Tribunus? If so, you might just want to remove work/835 from person/2130 and I will create a record for Tribunus when I create all the new person records for John of Ephesus. Just let me know if that sounds alright or if you would prefer to create the Tribunus record yourself. Thanks Nathan.

**Comment by nathangibson** [comment]
Yes, that's what I meant. We still need a link from work/835 to something, so unless you have a place to put that relationship in your John of Ephesus spreadsheet, I think I should go ahead and create a Tribunus record.

**Comment by dlschwartz** [comment]
I wasn't thinking about that. If you would like to create that record, please do. Could you send me the URI when you have it? Thanks Nathan.

**Comment by nathangibson** [comment]
OK Tribunus will be http://syriaca.org/person/3155. I'm working on the split now.

**Comment by nathangibson** [comment]
Done, and I've assigned person/2130 and person/3155 to you in Perseids.
