### ISSUE TITLE
Bug in rendering relationships in SPEAR

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-app-data#673]
RE: https://github.com/srophe/srophe-eXist-app/issues/895
This is a bug in the data, same relationship, coded 2 different ways. 

`<relation ana="personal" name="snap:IntimateRelationship" mutual="http://syriaca.org/person/2571 http://syriaca.org/person/2570"></relation>`

and 
`<relation ana="personal" name="syriaca:IntimateRelationshipWith" mutual="http://syriaca.org/person/2570 http://syriaca.org/person/2571 http://syriaca.org/person/2573"></relation>`

**Comment by dlschwartz** [comment]
This should be fixed now. Thanks for catching this error.
