### ISSUE TITLE
Change @name to @ref in relation elements?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#676]
@davidamichelson @dlschwartz 

This applies to persons and works but not places or SPEAR.

Currently we are classifying our relation elements using three different attributes: type, ref, and name. (Works use type + ref, persons use type + name.) In my research on creating RDF-ready TEI relations, I understood that `@ref` is the attribute most commonly used to represent an RDF property on a relation (though perhaps some people use `@name`?). 

I think we should use either name or ref but preferably not both. I think we are already in agreement that we want the relations to use RDF properties (our own if external ones are not available). @wsalesky wants to have a good way to label relations in the sidebar across all modules not including places or SPEAR. 

I suggest converting `@name` values to prefixed RDF properties and putting them in `@ref` instead. Are there any objections to this? I would coordinate with @wsalesky to make sure I don't break anything.

**Comment by nathangibson** [comment]
@wsalesky 
We discussed this again today, and we would like to move RDF properties in relations to `@ref`. This includes SPEAR, with @dlschwartz 's approval. So far as I know, the Gazetteer does not have any RDF properties in relations.

Here is what I plan to do: 
1. Move all `@name` values in person and work relations to `@ref`. 
 A. Prefix these and change them to RDF properties. Working list at https://docs.google.com/spreadsheets/d/1agm9t_UGiPQo-SuEaBjnDldQuDhFJbdwO4qnWGvY5LI/edit#gid=0
 B. Document them in ODD file with usable glosses.
2. Change relations in bibl records to notes. (See https://github.com/srophe/srophe-app-data/issues/702#issuecomment-280445240.) 
3. Move SPEAR `@name` RDF properties to `@ref` after confirming that @wsalesky is ready for this. 
4. Discuss with @tacarlson regarding place relations. Relations that have a non-RDF value in `@name` (such as those in place records) will not be moved to `@ref` until RDF properties have been approved by the relevant editors (in this case @tacarlson and @davidamichelson ). 

See also #702 , #710

**Comment by wsalesky** [comment]
Great, thanks. I hope to have something for us to look at by tomorrow.

**Comment by nathangibson** [comment]
OK @wsalesky , I think I've completed step 1 above (see the referenced commits). I'll need to double-check tomorrow. I've also updated https://github.com/srophe/srophe-eXist-app/blob/dev/srophe-app/documentation/syriaca-tei-main.odd and https://github.com/srophe/srophe-eXist-app/blob/dev/srophe-app/documentation/syriaca-tei-main.rnc.

**Comment by nathangibson** [comment]
The merge was big enough it might need to be manually pushed.

**Comment by wsalesky** [comment]
Done.

**Comment by dlschwartz** [comment]
@wsalesky, commit 0eb6a9cd8de5275e75b0ee5cf60edd44794ae071 changes all relation name attributes to relation ref attributes.

**Comment by wsalesky** [comment]
@dlschwartz Thanks! I updated the visualizations, everything should be working again, let me know if you find any bugs.

**Comment by dlschwartz** [comment]
@wsalesky Thanks, this looks great! And it's faster than it's ever been.
