### ISSUE TITLE
This record has no English name in the tei:title

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-app-data#679]
@nathangibson  Is this deliberate, or a bug? 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2821/tei

Found while debugging: https://github.com/srophe/srophe-eXist-app/issues/596

**Comment by nathangibson** [comment]
Nope, that's a mistake. Passing it off to @davidamichelson to approve/push to production.

**Comment by davidamichelson** [comment]
I approve.
