### ISSUE TITLE
Records needing approval

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#680]
#640 
#635 
#679 
#677 
#675 
#664 
#662 
#660 
#636 
#630 
#621

**Comment by davidamichelson** [comment]
I have approved:

#640
#635
#679
#677
#675
#664
#662
#660
#636
#630

**Comment by davidamichelson** [comment]
See issue #681 for one for you to approve please.

**Comment by davidamichelson** [comment]
@nathangibson Okay I have approved all of these except #621 where I cannot find the file. I also created #681 for you to approve. Please move all these files to master.

**Comment by nathangibson** [comment]
These should all be merged in now.
