### ISSUE TITLE
Getting rid of child data directories when no longer needed

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#684]
Hi Winona,

Now that we are done with active development on Q, I would like to move all records in persons/tei/saints/tei just up to persons/tei in both the Master and Dev branches. Is there a best way of doing that?

thanks,
Dave

p.s. @jsaintlauren and @nathangibson let me know if you object.

**Comment by nathangibson** [comment]
I would definitely be in favor of this, as it would make finding and managing the records easier. But I seem to vaguely remember that we ran into some kind of problem when we tried to do that before — sadly I can’t remember what it was! Does anyone else remember?

**Comment by wsalesky** [comment]
Yes, we can go ahead and do this. I will need to manually push this change as it is to large for the webhooks. Perhaps that was the issue Nathan?

**Comment by nathangibson** [comment]
I think it was some data issue regarding how we process saints records vs. other records, but hopefully that has already been taken care of through seriesStmts etc.

**Comment by wsalesky** [comment]
stale issue
