### ISSUE TITLE
User submission: bibl/2199

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#688]
Trying to decipher what the following means:

Name:  [removed for privacy]
e-mail: [removed for privacy]
Subject: Addition

Work Cited: http://syriaca.org/bibl/2197
Pages 363-375

**Comment by davidamichelson** [comment]
edited for privacy

**Comment by nathangibson** [comment]
User clarified that the submission is for http://syriaca.org/bibl/2199 instead (for which we had no page numbers). Also sent a scan of the file from which I was able to verify these page numbers. I have made the edit and am requesting approval for it to go live to master.

**Comment by davidamichelson** [comment]
I approve. Please contact the user and say that we would be interested in knowing how they are using the sight. Also please ask if the user would like credit for the addition to the record.

**Comment by nathangibson** [comment]
I've moved to master branch and contacted the user.
