### ISSUE TITLE
Some "note" elements for works are sourced to #bib221-1 instead of to bibs in their own records

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#7]
See, for example note elements on https://github.com/srophe/srophe-app-data/blob/dev/data/works/tei/235.xml and https://github.com/srophe/srophe-app-data/blob/dev/data/works/tei/270.xml

I assume these need a find & replace to insert their own bibl numbers (e.g., "#bib235-1") instead. Does that seem right @davidamichelson ?

**Comment by wsalesky** [comment]
What is 221? Is it a sample record?

https://github.com/srophe/srophe-app-data/blob/dev/data/works/tei/221.xml

**Comment by nathangibson** [comment]
Yes it is a sample record.

**Comment by wsalesky** [comment]
Okay, I am about to push the fixed data for this to the dev branch, be sure to merge or rebase your changes. (Also will post it as a gist so it can be easily rerun if needed.)

**Comment by wsalesky** [comment]
Gist for updating: 
https://gist.github.com/wsalesky/3bacc0abdda23fc578d3

**Comment by nathangibson** [comment]
OK, I just merged mine in.

**Comment by wsalesky** [comment]
Okay, thanks. Merging mine now...

**Comment by wsalesky** [comment]
Merged.
