### ISSUE TITLE
Sergius in work/797

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#705]
Did something perhaps go wrong in splitting the records for the saints commemorated in work/797. We have a record for the Simeon (person/2095) but I cannot seem to find one for the Sergius commemorated in the same work. Thanks

**Comment by jedwardwalters** [comment]
This one isn't on my list of records that I split, so I must have missed this one somehow when I was compiling a list. I'll take care of it.

**Comment by jedwardwalters** [comment]
Done. Sergius is now http://syriaca.org/person/3154

**Comment by dlschwartz** [comment]
Excellent. Thanks so much Jamey!
