### ISSUE TITLE
error message when going to advanced search from person record

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#706]
@wsalesky I consistently get an error message when I am on a person record and try to access the advance search using the gear icon at the top of the page. When I use the same icon on the browse page it works just fine. Could you please check this out Winona? Thanks.

**Comment by wsalesky** [comment]
Dev or production server?

**Comment by wsalesky** [comment]
Never mind, I see it is on both. I will fix it.

**Comment by wsalesky** [comment]
Fixed. See: 11ac675e6a5f9ef09d89674bcb9a2ffc68c70b7d
