### ISSUE TITLE
Webhooks?

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#712]
@wsalesky Just did a commit https://github.com/srophe/srophe-app-data/commit/352c98f663e038c07a76770d977d3e88596a5456 and it looks like the webhooks were successful but I'm still getting 404 on the pushed files. E.g., wwwb.library.vanderbilt.edu/bibl/2434

Can you tell what's wrong?

**Comment by wsalesky** [comment]
Yes, sorry. The webhook was mangling the upload url for new records. Works fine for updates. I will fix it. (And I added the bibl records by hand. )
