### ISSUE TITLE
English headwords for saints

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-app-data#72]
Move headword attribute from gedesh to first english name. Change title element to match.

**Comment by davidamichelson** [comment]
For all person records that are in Q (marked with series stmt), we want to move syriaca-tags="#syriaca-headword" to the first (in document order) persName where @lang=”en”
Current:
<persName xml:id="name1092-2" xml:lang="en-x-gedsh" syriaca-tags="#syriaca-headword">Ahrūn of Serugh</persName>
<persName xml:id="name1092-3" xml:lang="en">Aaron of Serugh</persName>

Revised:
<persName xml:id="name1092-2" xml:lang="en-x-gedsh">Ahrūn of Serugh</persName>
<persName xml:id="name1092-3" xml:lang="en" syriaca-tags="#syriaca-headword">Aaron of Serugh</persName>

Then we will need to revise the <title level="a" xml:lang="en">Ahrūn of Serugh — <foreign xml:lang="syr">ܐܗܪܘܢ</foreign></title> to use the text node from the new headword.

**Comment by davidamichelson** [comment]
For all person records that are in Q (marked with series stmt), we want to move syriaca-tags="#syriaca-headword" to the first (in document order) persName where @lang=”en”
Current:
<persName xml:id="name1092-2" xml:lang="en-x-gedsh" syriaca-tags="#syriaca-headword">Ahrūn of Serugh</persName>
<persName xml:id="name1092-3" xml:lang="en">Aaron of Serugh</persName>

Revised:
<persName xml:id="name1092-2" xml:lang="en-x-gedsh">Ahrūn of Serugh</persName>
<persName xml:id="name1092-3" xml:lang="en" syriaca-tags="#syriaca-headword">Aaron of Serugh</persName>

Then we will need to revise the <title level="a" xml:lang="en">Ahrūn of Serugh — <foreign xml:lang="syr">ܐܗܪܘܢ</foreign></title> to use the text node from the new headword.

**Comment by davidamichelson** [comment]
This may require a change to the XSLT that generates the HTML page title where the en-x-gedsh may be used to generate the title on the HTML page.
see http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2785

See separate issue.

**Comment by nathangibson** [comment]
XSLT issue is https://github.com/srophe/srophe-eXist-app/issues/532

**Comment by wsalesky** [comment]
@davidamichelson A few of these do not have an English name id's listed below:

<idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/680/tei</idno>

<idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1947/tei</idno>

<idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1845/tei</idno>

<idno xmlns="http://www.tei-c.org/ns/1.0" type="URI">http://syriaca.org/person/1844/tei</idno>

**Comment by wsalesky** [comment]
Also finding some with two Syriac headwords:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2158/tei

**Comment by wsalesky** [comment]
And, Authors has some Gedesh headwords as well: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2/tei

**Comment by davidamichelson** [comment]
Please write a script that when there are two Syriac headwords, delete the headword attribute tag from the second one in document order.
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2158/tei

**Comment by wsalesky** [comment]
Done. I did some spot checking. Looks okay, but let me know if you find any funky names.

**Comment by davidamichelson** [comment]
Okay, we love this and would like to use the script across all person records to  change all person headwords to the the first en tagged name instead of GEDSH, but leave on GEDSH if not EN name.

**Comment by wsalesky** [comment]
Okay, I ran this on the whole persons directory. There are 225 records remaining that still have gedesh headwords. I took a look and it looks to me like these records do not have persName with a `xml:lang='en'` attribute. 
See:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/545/tei
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/541/tei
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2158/tei

Thanks!

**Comment by wsalesky** [comment]
I think this one can be closed.

**Comment by davidamichelson** [comment]
I am going to reassign this to myself.
