### ISSUE TITLE
Keywords added

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#720]
Winona, Nathan and I just added over 1000 keyword records to dev. They appear in browse but the individual records do not show up currently. Could you please look into this when you get a chance. Thank you.

**Comment by wsalesky** [comment]
Sure. I will not get to it today, but hopefully before Monday.

**Comment by wsalesky** [comment]
Some inconsistencies in data, which cause some odd display issues: 
```
<relation ref="skos:broadMatch"
                         active="http://syriaca.org/subject/abbasids"
                         passive="http://syriaca.org/keyword/dynasties"/>
```
You can see the active attribute uses 'subject' and the passive attribute uses 'keyword'

**Comment by dlschwartz** [comment]
@wsalesky There is clearly a problem with the xslt. Funny, because I thought we took care of this. In fact, there are 3820 occurrences of "http://syriaca.org/subject/" when there should be zero. I will find and replace all of these and then push them back to Github. I hope this doesn't require too much tweaking of what you have already done.

**Comment by wsalesky** [comment]
No problem. Let me know when they are on github. 
Thanks!

**Comment by dlschwartz** [comment]
I just pushed them. There should no longer be any occurrences of /subject/. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz initial view is working. Still working on browse, and we will most likely want to discuss the page view for each term, now that we have some real data to work with.
