### ISSUE TITLE
CTS URNs for SPEAR

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#728]
@wsalesky, as we discussed in our recent meeting with Dave, I'm interested in getting CTS URNs into SPEAR so that we can display Syriac text on the factoid page along with a link to the corpus. The editors discussed CTS URNs in our meeting today and I have a couple of questions.

1. I would like to propose adding a bibl type="urn" with a ptr target="[urn]" inside the bibl. 

Example:
```
<bibl type="urn">
     <ptr target="urn:cts:syriacLit:nhsl8559.syriacCorpus57:8"/>
</bibl>
```

Does this sound right to you? Would you find something else preferable? If this sounds fine to you, I'll tweak the schema to allow it.

2. Would you be able to add this data with a script? It would need to find instances of //bibl/ptr target="http://syriaca.org/bibl/633", grab the text node of the following sibling citedRange element, and add that text node as the section number of the CTS URN as in the example above? For now we would only want to do this for the Chronicle of Edessa (https://github.com/srophe/srophe-app-data/blob/dev/data/spear/tei/Chronicle_of_Edessa.xml) but eventually we would want to modify this script for other SPEAR TEI so I think writing a script is worth it.

The goal would be to take 
```
<bibl type="primary">
     <ptr target="http://syriaca.org/bibl/633"/>
     <citedRange unit="pp">8</citedRange>
</bibl>
```

and add a sibling div
```
<bibl type="urn">
     <ptr target="urn:cts:syriacLit:nhsl8559.syriacCorpus57:8"/>
</bibl>
```

**Comment by wsalesky** [comment]
@dlschwartz Yes, I can do that programatically. Shall I go ahead? (I can save the results in a test branch.)

**Comment by dlschwartz** [comment]
@wsalesky, yes, please do and I'll make changes to the schema. Thanks.

**Comment by dlschwartz** [comment]
@wsalesky I've added this to the schema and it seems to work fine. When you've run the script on the Chronicle of Edessa I'll test to make sure. Thanks.

**Comment by wsalesky** [comment]
Okay, how do I connect the http://syriaca.org/bibl/633 to a corpus record? I don't see it linked here:
https://github.com/srophe/syriac-corpus/blob/master/data/tei/57.xml#L76

**Comment by dlschwartz** [comment]
Yes, exactly. Sorry that wasn't clear. We don't have URNs or Corpus texts for some of the works covered in SPEAR. But since we do for the Chronicle, we want to see how it goes with using them to pull text from the corpus and visualize it on the factoid page. Adding these URNs is the first step of that process. If we can get this working it should be a nice deliverable for the NEH even if it is not implemented very widely at this stage.

**Comment by dlschwartz** [comment]
Great, thanks.

**Comment by wsalesky** [comment]
Okay, changes are on this branch: https://github.com/srophe/srophe-app-data/tree/issue728

**Comment by wsalesky** [comment]
Oh, sorry, I misunderstood. I will just rerun the data on a fresh version of the Chronicle.

**Comment by wsalesky** [comment]
How does the updated file look?

**Comment by dlschwartz** [comment]
Yes, that's it. What happens if we merge that into dev? Is there anything added here that will cause problems for the app in visualizing the factoids? If you don't anticipate problems, please go ahead and merge it in. Thanks!

**Comment by wsalesky** [comment]
There should not be any problems.

**Comment by dlschwartz** [comment]
I merged the branch into dev, the TEI validates according to the updated schema, and the html still looks fine. Now to grab the relevant section of text from the Corpus and display it on the factoid page. I have no idea what that entails. Please let me know if you need anything from me. Thanks!

**Comment by wsalesky** [comment]
Okay great! I will let you know when there is something to see in the html

**Comment by wsalesky** [comment]
See it in the text here: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/119-1

**Comment by wsalesky** [comment]
@dlschwartz closing as a stale issue. Reopen if you need any edits.
