### ISSUE TITLE
Change namespace "dct" to "dcterms"

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#731]
@nathangibson It looks like in most modules we are using "dcterms" as the abbreviation for the dcterms namespace, but in NHSL you are using "dct", would you be willing to find and replace all in NHSL to make it match our practice elsewhere? Please let Winona know when it is done.

Thanks!
DM

**Comment by davidamichelson** [comment]
@nathangibson will you have time to make this change or should we do it for you?

**Comment by nathangibson** [comment]
Sorry for the delay. This should be fixed now in https://github.com/srophe/srophe-app-data/commit/07ea05f77ff4709af1d6a297a9dc625e2f30f2c2. 

The entities affected seem to works (NHSL) and subjects (taxonomy).

@wsalesky This will probably break some relations logic for NHSL and possibly taxonomy. It is also a very large commit so might need to be pushed manually to the dev server.

**Comment by wsalesky** [comment]
I will take a look. Webhooks are currently down for the Dev server as we are experiencing some issues. So I will push the change manually after checking it locally. 
Thanks for the heads up.

**Comment by wsalesky** [comment]
stale issue
