### ISSUE TITLE
Push taxonomy to dev

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#734]
@wsalesky I went ahead and moved the newly created taxonomy TEI files to dev in GitHub. They aren't appearing in html though. I'm guessing the web hooks are still turned off. Could you push those for me? Thanks Winona.

**Comment by wsalesky** [comment]
Webhooks are on, I think the commit was just to big. I added them manually. Let me know if you do not see the changes. I will try to rerun the RDF today and work on the rest of the browse. It would be nice to have that done this week!
