### ISSUE TITLE
relation in SPEAR teiHeader

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#736]
@wsalesky This is sort of a question that might turn into an issue. I've decided I need to tweak what I include in the sourceDesc of the SPEAR header. I'd like to replace the <p> element and the English prose with a more structured listBibl and then be able to validate other aspects of the document against that structured data. I'm hoping to restrict human error.

I realize though that this might mess up the rdf for SPEAR. When we generate rdf out of SPEAR records that process looks at the @ref attribute in the relation element: https://github.com/srophe/srophe-app-data/blob/dev/data/spear/tei/SPEAR_John_Ephesus_Lives_10510.xml#L39. Does it look for the listRelation inside of a p element or can I just include the listRelation anywhere inside the sourceDesc element? 

Thanks Winona.

**Comment by wsalesky** [comment]
@dlschwartz You can put it anywhere in the sourceDesc

**Comment by dlschwartz** [comment]
Excellent. It will still be in sourceDesc. Thanks!
