### ISSUE TITLE
web forms

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#738]
@wsalesky The next-up number looks good but it doesn't look like the request to save URIs is actually working. I reserved two URIs and got the following:
![places1](https://user-images.githubusercontent.com/4984270/44036313-1c1f4218-9ed7-11e8-9e53-c2db643f5145.JPG)

But then I closed that tab and reentered the forms. The URIs don't seem to have been reserved: 
![places2](https://user-images.githubusercontent.com/4984270/44036373-3f2b9a7c-9ed7-11e8-81fc-fd021a419f30.JPG)

**Comment by wsalesky** [comment]
@dlschwartz what browser are you using?

**Comment by wsalesky** [comment]
@dlschwartz Also what do you mean by "reentered the forms?" Just so I can try to reproduce the issue. I see your reserved URI's, so I suspect the form is being cached on your browser. (I may need to force the form to reload.)

**Comment by dlschwartz** [comment]
@wsalesky I just closed the tab and then went back to the forms again. The form showed me that the next available URI was 3045 (even though I had just reserved 3045-3046) and allowed me to select the reserve URI range and reserve 3045-3046 again. 

I'm in Chrome. I've tried a hard refresh at various points as well.

**Comment by dlschwartz** [comment]
@wsalesky Of course, I just did another hard refresh again after hitting "comment" and now I see that the next available URI is 3047.

**Comment by wsalesky** [comment]
Can you try  reserving another uri? And see if it works as expected now? You should not actually need to refresh the form at all, it should show up as soon as you hit the save.

**Comment by dlschwartz** [comment]
@wsalesky It seems fine now. As in the first picture above, when I hit save it showed that the numbers had been reserved. However, when I left and came back it showed that they were available. 

Have you ever heard of problems with the cache in Chrome? Sometimes I do a hard refresh and nothing happens. I'll google it. Thanks Winona.

**Comment by wsalesky** [comment]
I have had occasional problems with Chrome and caching but usually a hard refresh solves the problem.

**Comment by dlschwartz** [comment]
Thanks Winona. Next time I'm having similar problems I'll try clearing browser data first.
