### ISSUE TITLE
Indexing for ODD

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#741]
As we work on documentation for Srophe and Syriaca.org, we are hoping to make significant improvements to the ODD. One idea I would like to pursue is the production of indexes of Syriaca.org data that can be used in the ODD to validate specific types of data.

The indexing of Syriaca.org data that would allow us to point to a single xml file (rather than rifling through 1000s of separate xml files) for purposes of validation. Here is an example of what I have in mind with SPEAR and the ODD pointing to an index of the taxonomy: https://github.com/srophe/srophe-app-data/blob/dev/data/subjects/taxonomyIndex.xml. With that index in place, I can use schematron to point to pieces of that index with my ODD in specific contexts. For example, lines 1844-1865 of this link (https://github.com/srophe/srophe-eXist-app/blob/schema-4-spear-edits/srophe-app/documentation/SPEARschema/odd_SPEAR.xml#L1844) are how I allow only occupation keywords as the value of @ref attributes when they appear on <occupation> elements.

Implementing something similar more broadly in the ODD would, for example, create an error (red) or warning (yellow) message to pop up in oxygen if an encoder input a place URI that wasn't among the place URIs on dev (or production if we found that preferable); it would require that an author @ref pointed to a person URI that is encoded as an author; etc. 

This would prevent typos, help with consistent data encoding across modules, and function as a nice aid to editing new records.

_Originally posted by @dlschwartz in https://github.com/srophe/srophe-app-data/issue_comments#issuecomment-439082074_

**Comment by davidamichelson** [comment]
@dlschwartz Is this still an idea? Should we discuss this?

**Comment by dlschwartz** [comment]
@davidamichelson this is in the works. @wsalesky did the xslt. The results are here: [places](http://wwwb.library.vanderbilt.edu/exist/apps/srophe/documentation/indexes/places.xml) and [persons](http://wwwb.library.vanderbilt.edu/exist/apps/srophe/documentation/indexes/persons.xml). They aren't currently on GitHub but Winona is working on that. When they can be accessed there, I will implement this. I've already written the Schematron rules, I just need the correct link to the raw GitHub files.

**Comment by dlschwartz** [comment]
@davidamichelson @wlpotter I have updated the schema to validate against the raw versions of the index files Winona created: [persons](https://github.com/srophe/srophe-eXist-app/blob/master/documentation/indexes/persons.xml) and [places](https://github.com/srophe/srophe-eXist-app/blob/master/documentation/indexes/places.xml). These should require in-use Syriaca.org person and place URIs at the following locations in places data: 

Person URIs
`//tei:text//tei:persName/@ref`

Place URIs
`//tei:text//tei:placeName/@ref  | tei:district/@ref  | tei:settlement/@ref  | tei:region/@ref  | tei:country/@ref | tei:bloc/@ref`
`//tei:body//tei:relation/@mutual`

Will, can you please test these and let me know if anything seems off. If all looks good, you can go ahead and close this issue. Thanks.

**Comment by wlpotter** [comment]
@dlschwartz I believe this can be closed? The only thing you might want to consider is whether you want the schema to validate against the GitHub versions of the indexes or the ones that live on the server, e.g https://syriaca.org/documentation/indexes/persons.xml? Based on https://github.com/srophe/srophe-eXist-app/issues/1239 it seems that these will be the versions updated automatically but I don't think those changes will be pushed back to GitHub?

**Comment by dlschwartz** [comment]
I agree, this can be closed.
