### ISSUE TITLE
Citations on Locations in the Gazetteer

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#742]
@davidamichelson Will change the citations for coordinates from GEDSH:

`<location type="gps" source="#bib78-2"><geo>37.15 38.8</geo></location>`

These need to instead cite the process from which the coordinates were derived.

Also the footnote should go on the whole coordinates, not just the longitude

**Comment by davidamichelson** [comment]
Ignore the above comment, instead add a note in the editorialDecl on how we derived coordinates from GEDSH and Syriac World Maps

**Comment by wlpotter** [comment]
Cf. #819

**Comment by davidamichelson** [comment]
Added to #819 thus closing here.
