### ISSUE TITLE
All place records should have state/@type=”existence”

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#746]
What about the place Atlantis?
Currently, 2926 out of 2930 places in dev have a <state type=”existence”

**Comment by davidamichelson** [comment]
@wlpotter Could you check and see which records do not have state/@type=”existence”?
@dlschwartz Shoud we require this?

**Comment by wlpotter** [comment]
It appears that only these two records do not have `tei:state[@type="existence"]

http://syriaca.org/place/3048
http://syriaca.org/place/3049

**Comment by dlschwartz** [comment]
Surely there are conceptual entities for which we want URIs that do/did not actually exist. The Atlantis example mentioned above as well as various utopian ideas. If virtually all places in our data exist we could create a warning when it  is absent.

**Comment by wlpotter** [comment]
Note to self: check those records that have an otherwise empty existence tei:state element.

**Comment by davidamichelson** [comment]
Currently we do not display this information, except it is used in the timeline feature and for search. We should discuss at editors meeting.

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson one more question on this. Should `<state type="existence">` require date attributes, i.e. one or more of the following: @to, @from, @when, @notBefore, @notAfter?

Also, if we have one of the above, should we also require one or more of the following: @srophe:computed-start, @srophe:computed-end?

**Comment by davidamichelson** [comment]
Conclusion, not all records will have state/@type=”existence” and not all state/@type=”existence” will have date data.
