### ISSUE TITLE
Should we stop using “desc” and replace with <note type="description"> in Gazetteer

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#747]
Should we stop using “desc” and replace with `<note type="description">` this would allow use of `<p>` etc? But would require changing the Gazetteer. Persons uses `<note type="description">` in this way.

**Comment by davidamichelson** [comment]
I think we decided not to do this, but I can't remember why. Anyone have an opinion?

**Comment by dlschwartz** [comment]
@davidamichelson @wlpotter here's the documentation for abstracts: https://github.com/srophe/draft-data/blob/master/data/schemaPlaceDraftData/syriacaPlacesTEI.odd#L1912

**Comment by dlschwartz** [comment]
https://github.com/srophe/srophe-app-data/issues/749
