### ISSUE TITLE
Update all records that have TEI:editor@role="general-editor"

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#752]
Update all records that have TEI:editor@role="general-editor" to TEI:editor@role="general"

**Comment by davidamichelson** [comment]
We will let Nathan know that this affects NHSL records. This change is for consistency since we are already using "general" elsewhere

**Comment by dlschwartz** [comment]
@davidamichelson Also, given this issue [https://github.com/srophe/srophe-app-data/issues/750](url) we should only expect editor @role="general" within seriesStmt. General editors apply only to monographic or series titles and not to analytic titles (this from the discussion of [level attributes](https://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-title.html)).

**Comment by dlschwartz** [comment]
@davidamichelson Does this change still make it appropriate to have a principle element in the titleStmt? It very well could, we should just think through the issues.

**Comment by davidamichelson** [comment]
@wlpotter I think this is done, correct?

**Comment by wlpotter** [comment]
@davidamichelson there are still a large number of work records that have a `@role="general-editor"` in them. From what I can tell these are the "uncorrected-draft" records that came in as new records from dev (see [this pull request](https://github.com/srophe/srophe-app-data/pull/791) and issue #789
