### ISSUE TITLE
Change this note @type relation to a relation element

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#758]
https://github.com/srophe/srophe-app-data/blob/9542c0aac98d46d2977cc7c565b8dd02a56d1158/data/persons/tei/222.xml#L237

**Comment by wlpotter** [comment]
I believe this would be:

```
<relation name="child-of-sibling-of" ref="http://syriaca.org/keyword/child-of-sibling-of" active="http://syriaca.org/person/222" passive="http://syriaca.org/person/217" source="#bib222-5">neveu de Michel le Syrien</relation>
``` 

@dlschwartz can you check that I constructed the tei:relation correctly, especially that this is the correct active -> passive direction? I think I'm stating here that person-222 is the child of the sibling of (i.e. nephew of) person-217?

I'm also not sure if we've decided to use `@name` or `@ref` (or both)?

**Comment by dlschwartz** [comment]
This is now redundant.
