### ISSUE TITLE
Adding @resp for Syriac preferred names

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#759]
Prose documentation suggests that all `<placeName>` elements must have either a @source or a @resp

https://github.com/srophe/srophe-app-data/wiki/TEI-Encoding-Manual-for-The-Syriac-Gazetteer#source

However, in many instances (but not all) `<placeName>` elements with @syriaca-tags="#syriaca-headword" do not have either a @source or a @resp.

Example" https://github.com/srophe/srophe-app-data/blob/master/data/places/tei/10.xml#L103

We should batch update data by adding a @resp=”http://syriaca.org” to any without @source

end result, all `<placeName>` elements would have @resp OR @source but not both

**Comment by davidamichelson** [comment]
@wlpotter Did we make this change? Could you check the data and make the change if not please?

**Comment by wlpotter** [comment]
@davidamichelson all place records have either a `@source` or a `@resp` attribute.

**Comment by wlpotter** [comment]
I had misread this issue. Just checked to make sure that no placeName has _both_ attributes. This is the case. All placeNames have at least one of the attributes but never both of them.

I think this can be closed unless there is something I missed.
