### ISSUE TITLE
Syriaca.org editors

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#761]
@davidamichelson It seems that all of our records point to [http://syriaca.org/documentation/editors.xml](url) with ref attributes on editor elements. This page does not exist but it would be most helpful if it did.

**Comment by nathangibson** [comment]
FYI there is a page at http://wwwb.library.vanderbilt.edu/documentation/editors.xml <http://wwwb.library.vanderbilt.edu/documentation/editors.xml>. I suppose it should just be pushed to master?

**Comment by dlschwartz** [comment]
Thanks @nathangibson. I think pushing it would be fine.

**Comment by davidamichelson** [comment]
Yes that sounds great!

**Comment by dlschwartz** [comment]
@davidamichelson @wsalesky Am I right that there should be a page that displays this information: https://github.com/srophe/srophe-eXist-app/blob/master/documentation/editors.xml. At the moment, we have editor and change elements all over our data that point to a url like "http://syriaca.org/documentation/editors.xml#wsalesky" but nothing appears when you put that into a browser.

**Comment by wsalesky** [comment]
@dlschwartz @davidamichelson Technically these are URIs and do not have to resolve to anything. In practice it would be a good idea to make the XML available at that URL.

**Comment by dlschwartz** [comment]
@wsalesky I think this is desirable in terms of giving public credit for the work people have done. Can we create a page at http://syriaca.org/documentation/index.html under "Editorial Definitions"? Let's call it "Contributing Editors". It should be based on https://github.com/srophe/srophe-eXist-app/blob/master/documentation/editors.xml. It can literally be as simple as a page with a heading of "Contributing Editors" with [this text as a description](https://github.com/srophe/srophe-eXist-app/blob/master/documentation/editors.xml#L51), followed by a list of these names. We could fancy it up later but this seems a good place to start. Please let me know if you have any questions. Thanks Winona.

**Comment by wsalesky** [comment]
Okay. It is up: http://syriaca.org/documentation/editors.html

**Comment by dlschwartz** [comment]
@wsalesky Thanks Winona!

**Comment by wsalesky** [comment]
@dlschwartz FYI http://syriaca.org/documentation/editors.xml will forward to http://syriaca.org/documentation/editors.html.

**Comment by dlschwartz** [comment]
Excellent, thanks @wsalesky

**Comment by davidamichelson** [comment]
I updated this file as part of the patch changes prep.
