### ISSUE TITLE
Changes to langUsage

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#767]
```<langUsage>
Remove <language> elements and add a <p> containing the following:
Languages codes used in this record follow the Syriaca.org guidelines. Language usage documentation available at: <ref target="http://syriaca.org/documentation/isostandards.xml">http://syriaca.org/documentation/isostandards.xml</ref>```

**Comment by wlpotter** [comment]
It might be easiest to write a simple update script that replaces the `<langUsage>` element of every record with the above contents rather than trying to write a find-and-replace

**Comment by wlpotter** [comment]
This script should do it, though i have been unable to test it yet: https://github.com/wlpotter/miscellaneous-util-scripts/blob/master/Syriaca-Places-Schema-Testing-Util/update-langUsage.xql

**Comment by wlpotter** [comment]
Note to self, this is a data-wide change

**Comment by wlpotter** [comment]
@davidamichelson question on this: it looks like bibl records don't have a profileDesc. Is the desired outcome or should we add a profileDesc/langUsage for bibl records as well?

**Comment by wlpotter** [comment]
No need to add profileDesc to bibl records at this time
