### ISSUE TITLE
On listPlace/place/placeName look for <placeName> lacking a @source or a @ref attribute. Add @resp=“http://syriaca.org”

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#769]
On listPlace/place/placeName look for ```<placeName>``` lacking a @source or a @ref attribute. 
Add @resp=“http://syriaca.org”

**Comment by wlpotter** [comment]
Xpath: /TEI/text/body/listPlace/place/placeName[not(@source) and not(@ref)]

Find regex: `<placeName`
Replace regex: `<placeName resp="http://syriaca.org"`
