### ISSUE TITLE
desc

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#770]
Current: ```<desc xml:id="abstract-en-78" xml:lang="en">```
Change to: ```<desc type="abstract" xml:id="abstract78-#" xml:lang="en">```
The the schema requires # to be a unique number. 
In batch transform we’ll just want them numbered consecutively. 
```N.B. the current practice only shows an error on the <place> element [which requires at least one <desc type=”abstract”>. The current [above] does not show an error on the <desc> element. This is because we do not require an @xml:id on <desc> unless it has @type=”abstract”. Neither do we require a different @type attribute, i.e. @type=”other” when a <desc> is not an abstract. ```
We could add the requirement of a @type=”other”
We could add an error if @xml:id=”abstract-en”

**Comment by wlpotter** [comment]
@davidamichelson @wsalesky I think I misunderstood what made this issue seem difficult. It looks like it is tricky to have the schema test for this, but the actual change needed isn't that complicated.

For places, at least, no record has more than one tei:desc that has an `@xml:id` attribute whose value matches the regex "abstract-en-\d+", so I think I can do this with a simple find-and-replace regex. I will give it a go and report back if I run into problems.

@dlschwartz have we implemented a schema rule that checks for how the abstract's xml:id value is formatted?

**Comment by dlschwartz** [comment]
@wlpotter See this constraintSpec: https://github.com/srophe/draft-data/blob/master/data/schemaPlaceDraftData/syriacaPlacesTEI.odd#L1899. It lays out the rules for the xml:id on the abstract. Let me know if you have any questions or if something isn't working correctly.

**Comment by wlpotter** [comment]
@dlschwartz the schema is working correctly here. This issue should be fixed.
