### ISSUE TITLE
TEI:note

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#772]
If no @xml:lang on place/note add @xml:lang=“en”.

**Comment by wlpotter** [comment]
Xpath: `/TEI/text/body/listPlace/place/note[not(@xml:lang)]`

Find regex: `<note`
Replace regex: `<note xml:lang="en"`

**Comment by wlpotter** [comment]
re-opening to run on all data, not just places

**Comment by wlpotter** [comment]
Need to re-run this with the right xpath

**Comment by wlpotter** [comment]
This is now, finally, fixed.
