### ISSUE TITLE
Move contents of srophe/util repo to srophe/xqueries repo and delete srophe/util repo

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#779]
@wsalesky @nathangibson 

Does any one know where the script for merging and deprecating records ended up? :)
See https://github.com/srophe/srophe-app-data/issues/107

We would like to adapt and use it for place records in the BQ Gazetteer.

Thanks,

**Comment by davidamichelson** [comment]
Looks like it is this: https://github.com/srophe/util

**Comment by davidamichelson** [comment]
Or here: https://github.com/srophe/srophe-xQueries

**Comment by davidamichelson** [comment]
@wlpotter Can you copy https://github.com/srophe/util into https://github.com/srophe/srophe-xQueries and delete https://github.com/srophe/util

**Comment by nathangibson** [comment]
Sorry was out of the office. The script is here https://github.com/srophe/srophe-xQueries/blob/master/merge-persons.xql.

**Comment by nathangibson** [comment]
Deprecating persons is here https://github.com/srophe/srophe-xQueries/blob/master/deprecate-person.xql. (This includes a redirect to a new URI, if relevant. But the merge script I think also includes this functionality.)

**Comment by wlpotter** [comment]
Contents of srophe/util repo have been moved to https://github.com/srophe/srophe-xQueries/tree/master/from-srophe-util

srophe/util repo has been deleted
