### ISSUE TITLE
mis-matching 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#78]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1409 this Pethion is not the same Pethion in the Ahahid cycle -- please take work 292 off of his bibliography

**Comment by jsaintlauren** [comment]
And we need a new record in q for the Pethion in the anahid cycle -- he is an ascetic cures Anahid and leads to the girl's conversion

**Comment by wlpotter** [comment]
I believe this has been fixed. Cf. #133
