### ISSUE TITLE
Change Schema and Manual for how to add non-Syriaca.org/non-app Bibl URIS

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#781]
Example see issue #778

**Comment by davidamichelson** [comment]
@dlschwartz will make a choice in the Bibl to require either a Syriaca.org TEI:ptr or a non-Syriaca.org TEI:ref

**Comment by dlschwartz** [comment]
![placeSchemaEdits](https://user-images.githubusercontent.com/4984270/68140425-67967d80-fef1-11e9-98d3-d2f274c95014.JPG)

**Comment by wlpotter** [comment]
@davidamichelson I was looking to send a few examples from the BQ Gazetteer that have both Syriaca and external bibl references for this issue, but it looks like somehow the new method for non-Syriaca references has disappeared.

Here are some example records: 
https://bqgazetteer.bethmardutho.org/place/5539
https://bqgazetteer.bethmardutho.org/place/5006

Both types of references have a tei:ptr with `@target` attribute. I thought we had decided to use a tei:ref with `@target` attribute for non-Syriaca bibls?

**Comment by wlpotter** [comment]
@dlschwartz here are examples for this issue.

Compare the first and second bibl elements here: https://github.com/srophe/bethqatraye-data/blob/master/data/places/tei/5006.xml#L95-L105

Note that the former, a source with a syriaca.org bibl, has a tei:ptr element while the latter, a non-syriaca source, has a tei:ref element.

For another example, see https://github.com/srophe/bethqatraye-data/blob/master/data/places/tei/5539.xml#L97-L99

Please leave this issue open after the schema has been updated until the documentation wiki has also been changed.

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson I don't remember a discussion on this issue. Are we sure we want to use two different elements to point? 

See https://github.com/srophe/draft-data/blob/master/data/schemaPlaceDraftData/syriacaPlacesTEI.odd#L2119. What I've done there is tested for a syriaca.org URI but made the schematron rule a warning. In oXygen that means that you don't get a red box when there is something other than a syriaca.org URI, you get a yellow box. The warning message (the text node of `<sch:assert>`) expresses that we usually expect syriaca.org URIs but that other URIs are allowed. This also allows later editors to check and make sure that the non-syriaca URI is correct. 

I can change this but want to make sure we get what we want.

![ptrTarget](https://user-images.githubusercontent.com/4984270/81600127-bd5f4d00-938e-11ea-953b-2f86f3fb5501.png)

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson One more thing, I suppose that if non-Syriaca.org URIs will be relatively rare, then what I have done is probably good. If it will be relatively common I suppose we should make the change.

**Comment by wlpotter** [comment]
Decision: Syriaca and non-Syriaca bibl URIs will, for the Beth Qatraye Gazetteer, be encoded in both cases as `tei:ptr/@target` attribute values. The schematron rule will remain in place to remind encoders that, in most cases, the attribute value _should_ be a Syriaca.org URI, but the schema will not at this time require one.

@dlschwartz @davidamichelson please add to this if I have left anything out. Otherwise, I believe this issue can be closed.

**Comment by dlschwartz** [comment]
This is a good summary of what we decided.
