### ISSUE TITLE
Script to add text to relation factoids

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#783]
@wsalesky This issue relates to https://github.com/srophe/srophe-eXist-app/issues/1166. I've opened this here because it's a data issue and not an app issue.

Can you please write a script that will take relation factoids (div subtype="relation") and add a human readable version of the information in the relation element? The app is already generating such a sentence but we would like it to be hard coded into the data. It should appear in a desc element.

Column H (not column I!) of [this spreadsheet](https://docs.google.com/spreadsheets/d/1aDICk8lrQ7cospr2yVlMYLXavMbaTDxbgr1GDrqfWDw/edit?pli=1#gid=0) contains the text for each type of relationship (n.b. I made a couple of small changes: deleted one relationship not in use in the data [grandchildOf], and tweaked H40 and H46 ). The script should look up the person URI in SBD and return the persName that has @syriaca-tags="#syriaca-headword" wrapped in a persName element with a @ref attribute pointing to the URI for that person. 

Note that @mutual attribute on a relation element always takes multiple space-separated values and that @active/@passive can (but don't usually) have multiple space-separated values. Whenever multiple values are present their persName elements should appear separated by commas with an "and" before the final value.

I suppose we should do this in a branch of dev. Then I can check to make sure it has worked properly and we can merge that branch into dev. At that time, we'll want to stop generating an English sentence and instead use the one in the desc element. 

Example:
```
<div type="factoid" subtype="relation" xml:id="factoid-4" resp="#ktorabi #dschwartz">
    <idno type="URI">http://syriaca.org/spear/3004-4</idno>
    <listRelation>
        <relation ref="syriaca:SenderOfLetterTo" active="http://syriaca.org/person/2513" 
            passive="http://syriaca.org/person/51">
            <desc>
                <persName ref="http://syriaca.org/person/2513">Constantine</persname> sent a letter to <persName ref="http://syriaca.org/person/51">Severus of Antioch</persName>.
            </desc>
    </listRelation>
    <bibl type="primary"><ptr target="http://syriaca.org/bibl/668"/>
        <citedRange unit="part">1.01</citedRange>
        <citedRange unit="pp">3</citedRange>
    </bibl>
</div>
```

**Comment by wsalesky** [comment]
@dlschwartz How does this look: https://github.com/srophe/srophe-app-data/tree/spearRelations
(Not some names did not resolve, there seems to be no person records for them?). Also now that I think of it, I assumed all relations would involve persNames, if there are any placeNames I would need to do a little rewrite, no big deal, but let me know.

**Comment by dlschwartz** [comment]
@wsalesky we're looking pretty good. The people without records is a constant problem. This has been pretty frustrating actually. I have a solution in mind. Let's not worry about this in the script though. The other problems I've found are data problems (comma-separated attribute values!). When we use the script, they people should be in SBD. Also, I don't need anything to happen with placeName element, so let's not worry about that. 

Some things to tweak:

- Can we add "and" instead of ", " between two names? And can we replace the final ", " with ", and " when we have three or more names? I suppose the script should look for two or more values in either @mutual, @active, or @passive.
- "DescendantOf" seems to have gotten a bit garbled. Also, somehow the spreadsheet had "snap:descendantOf" instead of "snap:DescendantOf". I've corrected the spreadsheet, perhaps this was the source of the problem with descendant?

Those are the only issues I see with the script. Thanks Winona!

**Comment by wsalesky** [comment]
@dlschwartz the script is supposed to list the names with an and if there are only two. Can you send me an example so I can use it for testing?

**Comment by dlschwartz** [comment]
@wsalesky I'm afraid it's the norm actually. When I do a search in Oxygen for " and " restricted to the path //listRelation/relation/desc the only returns I get are the desc elements I hand coded for relationships between event factoids.

Here's an example of one that has two persName elements separated by a comma and not " and "
https://github.com/srophe/srophe-app-data/blob/spearRelations/data/spear/tei/806.xml#L135

**Comment by wsalesky** [comment]
@dlschwartz Thanks, I will fix it.

**Comment by wsalesky** [comment]
How does it look now?

**Comment by dlschwartz** [comment]
@wsalesky We're not getting ", and " between the penultimate and ultimate persName elements when there are three or more. 

Here's an example: https://github.com/srophe/srophe-app-data/blob/spearRelations/data/spear/tei/3052.xml#L130. 

The following searches get me to the desc elements with the problem: \s.+\s restricted to //listRelation/relation/@mutual, //listRelation/relation/@active, and //listRelation/relation/@passive. There are about 40 instances.

I'm working on the grammar changes and I'll post again soon.

**Comment by dlschwartz** [comment]
@wsalesky I made the changes in the [spreadsheet](https://docs.google.com/spreadsheets/d/1aDICk8lrQ7cospr2yVlMYLXavMbaTDxbgr1GDrqfWDw/edit?pli=1#gid=0). Where possible I produced a sentence that would work regardless of the numbers of people, those are marked in yellow. Those marked in blue would change depending upon whether the @active or @passive has one or multiple values. Thanks Winona.

**Comment by wsalesky** [comment]
@dlschwartz See updates.

**Comment by dlschwartz** [comment]
@wsalesky This is looking pretty good. I only found one issue. With "syriaca:EpistolaryReferenceTo" it looks like the @active values are applied both before and after the text and the @passive values don't appear. Once that's sorted I think we're in good shape and we can push these to dev. Thanks Winona!

**Comment by dlschwartz** [comment]
@wsalesky This is looking pretty good. I only found one issue. With "syriaca:EpistolaryReferenceTo" it looks like the @active values are applied both before and after the text and the @passive values don't appear. Once that's sorted I think we're in good shape and we can push these to dev. Thanks Winona!

**Comment by dlschwartz** [comment]
@wsalesky did we ever fix this? I suppose we should before we push this data to the dev branch. Also, could you run this same script on a branch of draft data? It would be the files in [this folder](https://github.com/srophe/draft-data/tree/master/data/spear/SPEARDocsToEdit) and the two folder contained here as well. Thanks Winona!

**Comment by wsalesky** [comment]
@dlschwartz Yes we fixed this. Can I push this to dev today?

**Comment by wsalesky** [comment]
Also I have updated the data in draft data (on a new branch called spearRelations)

**Comment by wsalesky** [comment]
@dlschwartz I updated the data and the code. It looks like there still needs to be some cleanup. For example: http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/factoid.html?id=http://syriaca.org/spear/8559-554

I think this one had a tei:desc already, so the script just added an additional description, and left the existing. I can have it check for existing tei:desc and replace them, or we can do it by hand, I'm not sure how many of these there are. 

Let me know how you want to deal with it.

**Comment by dlschwartz** [comment]
@wsalesky this is fine. I had planned to do the events by hand so I had already done those. There aren't that many of them and they're all in one file. I've fixed this manually. Are the webhooks running? If not, can you refresh this. I think we can close this issue. Thanks Winona.

**Comment by dlschwartz** [comment]
@wsalesky I've merged the spearRelations into master on draft data as well. Thanks!

**Comment by wsalesky** [comment]
Webhooks are running. Do you not see your changes?

**Comment by dlschwartz** [comment]
@wsalesky Things are looking good. Thank you. I'll close this issue.
