### ISSUE TITLE
Index of person and place URIs

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#788]
@wsalesky can you please write an xQuery to create an xml file with all person URIs and another with all place URIs. Thanks.

**Comment by wsalesky** [comment]
@dlschwartz can you remind me where the XSLT you created lives? I want to make sure I get the write data output.

**Comment by dlschwartz** [comment]
@wsalesky the xslt and xml output are the taxonomyIndex files here: https://github.com/srophe/srophe-app-data/tree/dev/data/subjects. The output for what I have in mind would even be simpler. An xml file with a root listPerson element containing a person element for each person in SBD with @ref attributes containing the URIs. That ought to do it. (I tried to do basically the same thing I've done with the taxonomy but I'm getting an error I don't have time to figure out right now.) Thank you!

**Comment by wsalesky** [comment]
Hi Dan, 
Here you go:

Persons: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/documentation/indexes/persons.xml

Places: 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/documentation/indexes/places.xml

To run it you would need to run this script (with admin login): 
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/modules/build-index.xql?action=create&content=persons

**Comment by dlschwartz** [comment]
@wsalesky thanks so much. This will be very helpful.

**Comment by wsalesky** [comment]
Great!

**Comment by dlschwartz** [comment]
@wsalesky are these files available on GitHub? I can't seem to find them. I might be able to have a schema validate against these pages but I'm not sure about that. Also, it wouldn't work if the server went down. Normally I validate against a raw GitHub page. Thanks.

**Comment by wsalesky** [comment]
I will add them.

**Comment by dlschwartz** [comment]
Great thanks!

**Comment by dlschwartz** [comment]
@wsalesky I forgot to ask about this in the meeting. It turns out that I cannot link to these in HTML. My link has to be to a raw GitHub file. Are these available on GitHub? Can you point me to them? Thanks.

**Comment by wsalesky** [comment]
Yes, sorry I still have to add them.
Will do that right after I feed my starving kids. ;)
-Winona

**Comment by wsalesky** [comment]
They are here: https://github.com/srophe/srophe-eXist-app/tree/master/documentation/indexes

**Comment by dlschwartz** [comment]
Thank you.
