### ISSUE TITLE
Change "http://syriaca.org/editors.xml#..." to "http://syriaca.org/documentation/editors.xml#..."

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#793]
In many places we have @ref="http://syriaca.org/editors.xml#..." where we should have @ref="http://syriaca.org/documentation/editors.xml#..."

**Comment by wlpotter** [comment]
Xpath: /*

Find regex: `ref="http://syriaca.org/editors.xml#`
Replace regex: ` ref="http://syriaca.org/documentation/editors.xml#`

**Comment by davidamichelson** [comment]
Not in data. Was already corrected in an unknown commit.
