### ISSUE TITLE
deprecate <principal> throughout all Syriaca.org data

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#794]
```<principal>``` is no longer used

**Comment by wlpotter** [comment]
Xpath: /TEI/teiHeader/fileDesc/titleStmt

Find regex: " <principal>.+?</principal>"
Replace regex: ""

**Comment by wlpotter** [comment]
Fixed

**Comment by wlpotter** [comment]
re-open to run on all data
