### ISSUE TITLE
allow @subtype="representative" on tei:location elements

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#795]
See https://github.com/srophe/bethqatraye-data/issues/74

this change may already have been made, but opening an issue just to confirm. Close if this is the case.

Cf. [this commit](https://github.com/srophe/draft-data/commit/aa2b9658551f5a152c02d1cbddb3480d726ee6b3), which likely included this change.

**Comment by dlschwartz** [comment]
@wlpotter this should work properly. Is this still an issue?

**Comment by wlpotter** [comment]
This is working, thanks!
