### ISSUE TITLE
allow values "contributing" and "technical" for the @role attribute on tei:editor elements

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#797]
See https://github.com/srophe/bethqatraye-data/issues/79

I believe we are making this a syriaca-wide schema update, but we should discuss to make sure that is how we want to handle these attribute values.

**Comment by dlschwartz** [comment]
@wlpotter I agree, let's confirm. Syriaca-wide sounds right to me but @davidamichelson should confirm.

**Comment by dlschwartz** [comment]
@davidamichelson @wlpotter we have three instances of `<editor role="contributor">`. Do you want to change those to "contributing" and use that from here on out or do you just want to use the current "contributor"?

**Comment by dlschwartz** [comment]
FYI, see our discussion [here](http://syriaca.org/documentation/author-editor-roles.xml) regarding the use of "contributor." It looks like it comes from dct:contributor.

**Comment by dlschwartz** [comment]
Add `<editor role="contributor">`, `<editor role="technical">`, and `<editor role="associate">`

**Comment by davidamichelson** [comment]
- [ ] @dlschwartz please update the Srophe all ODD schema to permit `<editor role="contributor">` in the TEIHeader  (The use of `<editor role="contributing">` will be in NHSL body only and is a specific case different from here).

- [ ] @davidamichelson will update the documentation to make clear the definition.

**Comment by davidamichelson** [comment]
@dlschwartz actually wait this is a mess, we shoudl talk in person :)

**Comment by davidamichelson** [comment]
Okay this is done!
