### ISSUE TITLE
allow a tei:choice element within a tei:quote element

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#798]
See https://github.com/srophe/bethqatraye-data/issues/80

**Comment by dlschwartz** [comment]
This commit (https://github.com/srophe/draft-data/commit/5c1cc9043e73475366a168398de275d85472214b) adds choice, abbr, sic, corr, reg, orig, and expand to the place schema. Please test and if it is working correctly close this issue and https://github.com/srophe/bethqatraye-data/issues/80.

**Comment by wlpotter** [comment]
This works, thanks! I've closed https://github.com/srophe/bethqatraye-data/issues/80 as well.
