### ISSUE TITLE
allow values "valley" and "cemetery" for @type attribute on tei:place elements

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#799]
See https://github.com/srophe/bethqatraye-data/issues/82

Cf. https://github.com/srophe/bethqatraye-data/issues/26 on adding these place types to http://syriaca.org/documentation/place-types.xml

**Comment by dlschwartz** [comment]
https://github.com/srophe/draft-data/commit/00483b292794126e736387e622c170fc8eac71f5
