### ISSUE TITLE
Work titles have extraneous syriaca-tag values

### ISSUE THREAD

**Issue by nathangibson** [srophe/srophe-app-data#8]
Syriac titles (title @xml:lang="syr") have the following attribute:
syriaca-tags="#syriaca-headword #syriaca-anglicized"

which should be only  
syriaca-tags="#syriaca-headword"

The English titles (title @xml:lang="en") also have both of these attribute values, but this may be correct. @davidamichelson ?

This is the case for all of them that I've looked at so far, but for an example, see https://github.com/srophe/srophe-app-data/blob/dev/data/works/tei/270.xml

**Comment by wsalesky** [comment]
@davidamichelson Should the #syriaca-anglicized be retained for the English headwords?
