### ISSUE TITLE
relation elements in places use internal XML ID refs, they should be changed to Syriaca.org URIs

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#807]
Related to #773 

Should be an easy regex.

Current data uses pointer to place @xml:id
<relation mutual="#place-91”>
Change to full place URI for that place

example:
Current:
```
<relation name="share-a-name" mutual="#place-882 http://syriaca.org/place/2276"/>
```
New:
```
<relation name="share-a-name" mutual="http://syriaca.org/place/882 http://syriaca.org/place/2276"/>
```
Does the Schema expect this?

**Comment by davidamichelson** [comment]
@wlpotter Please investigate if this applies to persons, works, etc.

**Comment by wlpotter** [comment]
This is the case, at least in persons. Works are using the current practice (i.e., the values of `@active`, `@passive`, and `@mutual` are all full URIs).

**Comment by wlpotter** [comment]
Persons issue split out into #809. This has been fixed for place data

**Comment by wlpotter** [comment]
Sorry, shouldn't have closed this without confirming that the schema and documentation have been updated...

**Comment by dlschwartz** [comment]
The schema should require a Syriaca.org URI. Please let me know if that is not the case.

**Comment by wlpotter** [comment]
It doesn't seem like the schema is catching if a tei:relation contains "#place-\d+", referencing the `tei:place/@xml:id` rather than "http://syriaca.org/place/\d+", i.e. the doc URI.

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson see this comment on issue https://github.com/srophe/srophe-app-data/issues/811#issuecomment-630339777. 

Maybe that solves the issue. If not, can you give me a link to the line of the TEI on GitHub that validates when it shouldn't. That would help me troubleshoot the issue. Thanks.

**Comment by wlpotter** [comment]
Thanks, again for the clarification on the two schemas...I tested this issue with the place schema as well and it still lets the error through. 

Here is the line in the XML: https://github.com/srophe/srophe-app-data/blob/2019-May-Batch-Changes/data/places/tei/10.xml#L177
Note that for testing purposes I changed the mutual value to 
`"#place-10 http://syriaca.org/place/995"`

**Comment by dlschwartz** [comment]
@wlpotter that file has the syriaca-tei-main schema associated with it. When I switched schemas I got the following errors and messages.

With `#place-10`
![relation01](https://user-images.githubusercontent.com/4984270/82246124-be055f80-9909-11ea-8f66-32ad7c8d866b.png)

With `#place-995` just to compare error messages
![relation02](https://user-images.githubusercontent.com/4984270/82246139-c198e680-9909-11ea-9e3a-19d545c8a029.png)

Please let me know if I'm missing something. I actually have a note to myself in the ODD that something isn't working quite right with some of the schematron rules on the relation element. The note isn't very clear though so I'll be glad if you find an error.

**Comment by wlpotter** [comment]
Ah! I figured out what I was doing wrong....I didn't include the schematron rules. I was only associating the file as a `type="application/relax-ng-syntax"` but left out the `type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"` processing instruction...

The schema is functioning correctly; leaving this open and assigning to @davidamichelson to update the documentation.

**Comment by dlschwartz** [comment]
@wlpotter very good. I hadn't thought of that problem.
