### ISSUE TITLE
Illegal state exception on persons, places, and works

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#810]
I am getting an `illegal state exception -- cannot validate without schema` error on person, place, and work records.

here is the current processing-instruction:
```
<?xml-model href="http://syriaca.org/documentation/syriaca-tei-main.rnc" type="application/relax-ng-compact-syntax"?>
```

Note that bibl records don't have a processing-instruction associating a schema (which may be a separate issue), so they do not throw this error. 

Do we need to update the processing instruction for these records as part of batch changes and schema updates?

**Comment by dlschwartz** [comment]
@wlpotter there's no file at that location. I'm not sure how that association came about. I'd be interested to check out when that association appeared in the change log. Try this: https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/syriaca-tei-main.rnc.

**Comment by wlpotter** [comment]
Note to self: this is also a change that should be made in manuscript records

**Comment by wlpotter** [comment]
Updated in persons, places, and works. Leaving this open to remind myself to make this change in mss.

**Comment by wlpotter** [comment]
Note that schema association changes fir places is now #826
