### ISSUE TITLE
schema requiring @ref attribute on tei:relation

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#811]
The schema is requiring a `@ref` attribute on tei:relation elements that have a `@name` attribute.

But [this line](https://github.com/srophe/srophe-eXist-app/blob/master/documentation/syriaca-tei-main.rnc#L5572-L5575) in the schema seems like it would allow this situation where a tei:relation has a `@name` but not a `@ref` attribute. 

Perhaps there is something I'm missing?

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson This works when associating place records with the customized place schema: https://github.com/srophe/draft-data/blob/master/data/schemaPlaceDraftData/out/syriacaPlacesTEI.rng. 

It does not work on the syriaca-tei-main schema: https://github.com/srophe/srophe-eXist-app/blob/master/documentation/syriaca-tei-main.rnc. 

No work has been done on the latter schema in over two years. The plan was to start with places and then move on to the other modules. Any batch changes to place data should use the place schema linked above. The only other schema we have for validating Syriaca.org data is the minimally customized syriaca-tei-main. Once we make the places batch changes and troubleshoot any problems with that we will need to move on to the other modules. 

If making batch changes to persons, etc. just be prepared for the schema not to recognize some of those changes as legitimate. Also, be prepared for errors to emerge as that appropriate schema comes together. Many of the batch changes you are making to places came about through the process of writing the customization. It highlighted inconsistencies and refined the data model quite a bit. The same will be true for the other modules.

**Comment by wlpotter** [comment]
Apologies for my confusion; I see the distinction now. Validating with the customized place schema does not throw this error.

**Comment by dlschwartz** [comment]
Excellent!
