### ISSUE TITLE
Empty line before editors in header

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#815]
@wlpotter Looks like the script that deleted principle for issue https://github.com/srophe/srophe-app-data/issues/794 left a blank line: https://github.com/srophe/srophe-app-data/blame/4b5765cf2b2dbd90ceeb868adc5b2264f72b62db/data/places/tei/78.xml#L12

Can you please find and delete?

**Comment by wlpotter** [comment]
This find and replace regex should work: `\n\s*\n` -> `\n`

**Comment by wlpotter** [comment]
This has been fixed in places. @davidamichelson should I go ahead and make sure empty lines are deleted in persons, works, bibls, etc.?

**Comment by davidamichelson** [comment]
Yes please check all

**Comment by wlpotter** [comment]
Empty lines were removed from all data
