### ISSUE TITLE
Should we deprecate the value srophe:tags="#syriaca-simplified-script"                    

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#817]
Example:
```
<placeName xml:id="name1003-1" xml:lang="en" srophe:tags="#syriaca-headword" source="#bib1003-1">Beth ʿAynatha</placeName>
                    <placeName xml:id="name1003-2" xml:lang="en" source="#bib1003-2">Beṯ ʿAïnāṯā</placeName>
                    <placeName resp="http://syriaca.org" xml:id="name1003-3" xml:lang="en-x-srp1" srophe:tags="#syriaca-simplified-script">Beth Aynatha</placeName>
                    <placeName resp="http://syriaca.org" xml:id="name1003-4" xml:lang="en-x-srp1" srophe:tags="#syriaca-simplified-script">Beth ‘Aynatha</placeName>
                    <placeName resp="http://syriaca.org" xml:id="name1003-5" xml:lang="en-x-srp1" srophe:tags="#syriaca-simplified-script">Beṯ Aïnāṯā</placeName>
                    <placeName resp="http://syriaca.org" xml:id="name1003-6" xml:lang="en-x-srp1" srophe:tags="#syriaca-simplified-script">Beṯ ‘Aïnāṯā</placeName>
                    
                    
```
This attribute value was added whenever we created machine generated names as a process of machine Romanization. The namse 3 through 6 here were generated by script based on names 1 and 2. These names DO NOT appear in the HTML view of the record and are generated merely for making it possible for searching by these names which have the diacritics removed or in a different style. The srophe:tags="#syriaca-simplified-script" marks them as being excluded from the HTML.

I think we may need to keep them but also worry that srophe:tags="#syriaca-simplified-script" is redundant since resp="http://syriaca.org" and xml:lang="en-x-srp1" also indicate this (sort of).

Let's discuss.

**Comment by davidamichelson** [comment]
Or maybe we change it to "#syriaca-computed-name" or @srophe:tags="#srophe-computed-name" I think it is the word script that is out of place.

Using @srophe:tags="#srophe-computed-name" would then be comparable to @srophe:tags="#syriaca-headword"

**Comment by davidamichelson** [comment]
@wlpotter Please replace  
``` 
xml:lang="en-x-srp1" srophe:tags="#syriaca-simplified-script"
```
with
```
with xml:lang="en-x-srp1"
```

**Comment by davidamichelson** [comment]
- [ ] @dlschwartz please update the ODD to give an error if srophe:tags="#syriaca-simplified-script" That value is now deprecated.

- [ ] @davidamichelson will update the documentation

**Comment by dlschwartz** [comment]
This commit fixes the validation problem on srophe:tags: https://github.com/srophe/srophe-eXist-app/commit/24612b570cc4236d2f7712fdc524fc8d6d211d20

**Comment by wlpotter** [comment]
Data has been updated.

**Comment by davidamichelson** [comment]
We need to check in the HTML that this did not backfire :) There may be an issue here for Winona

**Comment by davidamichelson** [comment]
We need to make sure these names stay hidden if they have xml:lang="en-x-srp1"
