### ISSUE TITLE
update or remove places schematron ptr/@target warning

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#818]
One of the places schematron rules warns "This `@target` attribute must end with a number."

However, since we've begun to use the alphanumeric Zotero ID string, this warning may no longer be necessary.

In the Syriac World places, for example, we have this:
 `<ptr target="http://syriaca.org/bibl/QK9W3LED"/>`.

There is another schematron warning related to this one that may also need to be updated:
>Under most circumstances, the `@target` attribute on a `<ptr>` element should be a properly formatted Syriaca.org bibliography URI (`'http://syriaca.org/bibl/{\d+}'` - where {\d+} is a number).            However, when the `<ptr>` element indicates an external web address (i.e. `http://pleiades.stoa.org/places/922698`), the `@target` should indicate the correct URL for that resource.

Maybe we just want to update the "{\d+} - where {\d+} is a number" to reflect the use of alphanumeric Zotero IDs?

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson if we have alphanumeric endings I can make this change. I will probably just write rule that indicate that the value must start with `http://syriaca.org/bibl/` and leave it at that. That means that anything could follow. If we develop an index for bibl URIs like we use for the taxonomy in SPEAR and like we are bringing online for persons and places, we could simply require the value to exist in our data.

In the short run, I think we should probably just drop the {\d+} ending. Once we get bibl data in a more solid position, we can think about creating an index. 

Let me know if that's what you want.

**Comment by wlpotter** [comment]
@davidamichelson forgot to bring this one up this morning. I think this would be a good change to the rule in the short term. Thoughts?

**Comment by davidamichelson** [comment]
Agree, @dlschwartz please update.

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson the commit above requires the value of bibl/ptr/@target to start with "http://syriaca.org/bibl/" and therefore allows anything to appear after that. I have kept the warning message since on occasion we have a source like pleiades. Please test and close if things are working correctly.

**Comment by wlpotter** [comment]
This is working correctly. Thanks!
