### ISSUE TITLE
at least one tei:bibl element required as child of tei:place

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#820]
There are 19 place records that do not have at least one bibl element. The schema requires each place record to have an associated citation recorded in the bibl element, which seems to me how we want things to work. However, the following URIs would in that case need to be updated with a bibl element:

- [x] http://syriaca.org/place/2570
- [x] http://syriaca.org/place/2576
- [x] http://syriaca.org/place/2577
- [x] http://syriaca.org/place/2586
- [x] http://syriaca.org/place/2587
- [x] http://syriaca.org/place/2593
- [x] http://syriaca.org/place/2666
- [x] http://syriaca.org/place/2755
- [x] http://syriaca.org/place/2775
- [x] http://syriaca.org/place/2818
- [x] http://syriaca.org/place/2855
- [x] http://syriaca.org/place/700
- [x] http://syriaca.org/place/702
- [x] http://syriaca.org/place/840
- [x] http://syriaca.org/place/842

**Comment by davidamichelson** [comment]
Will need research and adding bibls.

**Comment by davidamichelson** [comment]
I can add some.

**Comment by davidamichelson** [comment]
@wlpotter if you run out of things to do, you could go through these and figureout which ones were created by Dan and ask him to provide bibls. You can also see if any of the others have clear references in GEDSH and cite that.

**Comment by davidamichelson** [comment]
Merged into Master
