### ISSUE TITLE
expand allowed value list for tei:citedRange unit attribute in places

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#821]
In place data we have both "col" and "ff" as values for `tei:citedRange/@unit` attributes. 

We currently allow "column", so perhaps we should update attributes with "col" to "column"? My only hesitation is that we allow "vol", so perhaps should change "column" to "col" for consistency.

"ff" refers to follia, e.g. in [place 104](https://github.com/srophe/srophe-app-data/blob/2019-May-Batch-Changes/data/places/tei/104.xml#L191)

**Comment by dlschwartz** [comment]
@davidamichelson I'me rather agnostic on this. Do you want to weigh in?

**Comment by wlpotter** [comment]
In the place records we have: "entry", "line", "map", "part", "pp", "section", "vol", "col", and "ff".

We currently allow all of the above except for "col" and "ff". In addition, we allow "column" but do not have instances in place data.

**Comment by davidamichelson** [comment]
Let's discuss.

**Comment by wlpotter** [comment]
DECISION: use singular abbreviations in all cases.

**Comment by dlschwartz** [comment]
@wlpotter please test the schema changes linked above and close if things are working as expected. Thanks.

**Comment by wlpotter** [comment]
@dlschwartz I don't see the link to the schema changes?

**Comment by dlschwartz** [comment]
@wlpotter there it is, I saved locally but forgot to push it. Thanks

**Comment by wlpotter** [comment]
@dlschwartz I see it now, thanks. The change looks to be working. I will unassign you but leave open for the data changes I need to make.

**Comment by wlpotter** [comment]
- [ ] @davidamichelson will update the documentation
- [ ] @wlpotter will change the data in places and create an issue for persons, works, bibls, etc.

**Comment by dlschwartz** [comment]
FYI, the list of values is here: https://github.com/srophe/srophe-eXist-app/blob/master/documentation/schemas/syriacaPlacesTEI.odd#L1627

**Comment by wlpotter** [comment]
FYI I have opened a separate issue (#840) for making these same changes in the other syriaca publications. As such, I will just make the data change here.

**Comment by wlpotter** [comment]
Place data updated. Leaving open for documentation update.

**Comment by dlschwartz** [comment]
@wlpotter these will end up in the SyriacaAll ODD, but please leave that issue open and we'll close it when we implement that ODD.

**Comment by davidamichelson** [comment]
Just to amend, Dan and I decided to use "fol" instead of "f" for clarity. @wlpotter Could you find and replace unit="f" to unit="fol" in all the data.

**Comment by wlpotter** [comment]
Woops! leaving this open for the documentation update.
