### ISSUE TITLE
allow sequenced xml:ids to have gaps in enumeration

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#822]
Currently a schematron error is thrown in cases where we have sequentially numbered xml:ids (e.g., in tei:placeName elements) that have a gap in their sequence.

For example, in [place 88's placeNames](https://github.com/srophe/srophe-app-data/blob/2019-May-Batch-Changes/data/places/tei/88.xml#L107-L119) we have:

```
<placeName xml:id="name88-1" xml:lang="en" srophe:tags="#syriaca-headword" source="#bib88-1">Gazarta</placeName>
<placeName xml:id="name88-2" xml:lang="en" source="#bib88-1">Gozarto</placeName>
<placeName xml:id="name88-3" xml:lang="en" source="#bib88-1">Cizre</placeName>
<placeName xml:id="name88-4" xml:lang="en" source="#bib88-1">Gzarta</placeName>
<placeName xml:id="name88-5" xml:lang="en" source="#bib88-1">Jazīra</placeName>
<placeName resp="http://syriaca.org" xml:id="name88-6" xml:lang="syr" srophe:tags="#syriaca-headword">ܓܙܪܬܐ ܕܒܪ ܥܘܡܪ</placeName>
<placeName xml:id="name88-7" xml:lang="syr-Syrj" source="#bib88-2">ܓܳܙܰܪܬܐ ܕܒܰܪ ܥܘܡܪ</placeName>
<placeName xml:id="name88-8" xml:lang="ar" source="#bib88-3 #bib88-7">جزيرة ابن عمر</placeName>
<placeName xml:id="name88-9" xml:lang="en" source="#bib88-4">Jazirat Ibn ʿUmar</placeName>
<placeName xml:id="name88-10" xml:lang="en" source="#bib88-5">Gāzartā</placeName>
<placeName xml:id="name88-11" xml:lang="syr" source="#bib88-6">ܓܙܪܬܐ ܙܒܕܝܬܐ</placeName>
<placeName resp="http://syriaca.org" xml:id="name88-13" xml:lang="en-x-srp1" srophe:tags="#syriaca-simplified-script">Jazirat Ibn Umar</placeName>
<placeName resp="http://syriaca.org" xml:id="name88-14" xml:lang="en-x-srp1" srophe:tags="#syriaca-simplified-script">Jazirat Ibn ‘Umar</placeName>
```

Note the gap between "name88-11" and "name88-13". We do not have a "name88-12", likely due to a decision to merge and/or deprecate a name at some point in the record's existence. 

While we still want to catch instances where we've duplicated xml:id values, we do not need to enforce unbroken sequencing in sequential xml:ids. This applies to:

- `tei:placeName`s in place records
- `tei:bibl`s in place, person, and work records (in work records these appear as children of tei:note elements)
- `tei:persName`s in person records
- `tei:desc[@type="abstract"]`s in place records
- `tei:note[@type="abstract"]`s in person records (though we need to update how these are formatted, which is a TBD issue).
- `tei:event[@type="attestation"]`s in person and place records
- `tei:state[@type="confession"]`s in place records

(I may have left something off, so please update as needed).

**Comment by dlschwartz** [comment]
@davidamichelson can you weigh in on this one? I agree that they should not need to be sequential. I suppose it's fine to allow a free for all as long as each ID is unique. Do you find that sufficient as well?

**Comment by dlschwartz** [comment]
And by the way, is there something I don't understand about the `@xml:id` in TEI? Why is it that you can assign the same ID to multiple instances of the same element, even siblings? It's always seemed odd to me.

**Comment by davidamichelson** [comment]
@dlschwartz Yes, we only need them to be unique and we do NOT want to require sequential because if we delete one we would have to renumber everything. Please make this change to the schema. 

p.s. I don't know an answer to the second comment about same ID to multiple instances that seems counter intuitive

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson the commit above removes the requirement that xml:id attributes be sequential. I explicitly removed it from the following contexts:
`//tei:place/tei:bibl`
`//tei:place/tei:event[@type='attestation']`
`//tei:place/tei:placeName`
`//tei:place/tei:desc[@type='abstract']`

The following contexts listed above didn't have any rules requiring sequential value so maybe we should check these again to make sure we aren't getting error messages we don't want:
`//tei:text//tei:state[@type='confession']`
`//tei:text//tei:event[@type='attestation']`

We'll need to deal with the person and work rules when we get a chance to work on those schemas.

Please test and close issue if things are working as expected.

**Comment by wlpotter** [comment]
@dlschwartz The contexts you changed are all working correctly. I will open a separate issue (#837) for the persons and works changes.
