### ISSUE TITLE
regularize case place-type values

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#825]
Here are the values which currently exist as attribute values for `tei:place/@type`:

settlement
mountain
river
open-water
region
monastery
province
quarter
parish
state
unknown
island
church
diocese
fortification
building
temple
**Building**
**Church**
**Quarter**
**Designated-space**
**Synagogue**
**Diocese**
natural-feature
synagogue
mosque
designated-space

It looks like the main issue is inconsistencies when it comes to case. I have bolded the ones which are upper-case as these should be changed to conform with the [place-type list](http://syriaca.org/documentation/place-types.html).

@davidamichelson please double check to make sure I'm not missing anything on this issue.

**Comment by wlpotter** [comment]
Note: I have a script ready which replaces the place type value with its all-lower-case value

**Comment by davidamichelson** [comment]
yes please change.

**Comment by wlpotter** [comment]
This is fixed.
