### ISSUE TITLE
update schema association in place records

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#826]
Opening this as a reminder that we need to change the schema association for place records to the place-specific schema.

Current association is:
```
<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/syriaca-tei-main.rnc" type="application/relax-ng-compact-syntax"?>
```
New association would be (at least):
```
<?xml-model href="https://raw.githubusercontent.com/srophe/draft-data/master/data/schemaPlaceDraftData/out/syriacaPlacesTEI.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://raw.githubusercontent.com/srophe/draft-data/master/data/schemaPlaceDraftData/out/syriacaPlacesTEI.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron""?>
```

See [this comment](https://github.com/srophe/srophe-app-data/issues/816#issuecomment-632332927) for a potential third schema link we might need to include.

@davidamichelson @dlschwartz we should discuss when we want to make this change. It would be helpful for proofing the validation errors to have make the change now (on the [batch changes branch](https://github.com/srophe/srophe-app-data/tree/2019-May-Batch-Changes/)) so that the correct errors are highlighted when reviewing files. However, if we associate the files now, we would have to use the one that is in [draft-data](https://github.com/srophe/draft-data/blob/master/data/schemaPlaceDraftData/out/syriacaPlacesTEI.rng). That would require us to update the schema association again once we've finalized and moved the schema(s).

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson I think we should go ahead and make the new association. What's the plan for doing this. I've used find all and replace on the @href before. It works reasonably well but you can get tripped up by unexpected line breaks. An xslt is an option as well. I've got one for this purpose somewhere. I just asked the oXygen folks if there is a way to change the xml model lines in a group of files the same way that the red pushpin works for single files. They said no but also said that they would look into it. Interestingly they have not had a request for this before. They seem to prefer a validation scenario or a document type association. Let me know if you want to look into this and I can send the links they gave me. I like having the schema linked in the xml model. It allows anyone using the TEI button on the site to immediately link to the customized schema if they want to see it.

I can move the current place schema from draft data to https://github.com/srophe/srophe-eXist-app/tree/master/documentation. I might want to add a "schemas" folder as well. If I do that, I can give you the links and an example of the three xml model lines that we would want on each file. Just let me know.

**Comment by wlpotter** [comment]
@dlschwartz updating it shouldn't be too difficult. A find-and-replace could work, but you can also select and update processing-instructions with xquery (I've done this before for the manuscript project and it's rather straightforward).

If you give me examples of what the final processing-instructions should look like, I can put them in the script to make the change.

**Comment by dlschwartz** [comment]
@wlpotter great! I've moved the current draft place schema to srophe-exist-app. I've also moved the stand-alone schematron to that location. There should now be three xml model lines: 

`<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaPlacesTEI.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>`
`<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaPlacesTEI.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>`
`<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/uniqueLangHW.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>`

**Comment by wlpotter** [comment]
I tested the script on place 78 to see how it worked. You can see the output [here](https://github.com/srophe/srophe-app-data/blob/2019-May-Batch-Changes/data/places/tei/78.xml#L1-L3).

I am getting this error in Oxygen, though: 

>System ID: https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaPlacesTEI.rng
Main validation file: C:\Users\anoni\Documents\GitHub\srophe\srophe-app-data\data\places\tei\78.xml
Engine name: ISO Schematron
Severity: fatal
Description: wwwb.library.vanderbilt.edu:80 failed to respond (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/documentation/indexes/places.xml)
Start location: 6213:4

Is there maybe a reference to the dev server in one of the schematron files that is causing http issues? Maybe [here](https://github.com/srophe/srophe-eXist-app/blob/master/documentation/schemas/out/syriacaPlacesTEI.rng#L4860) or [here](https://github.com/srophe/srophe-eXist-app/blob/master/documentation/schemas/out/syriacaPlacesTEI.rng#L4845).

**Comment by dlschwartz** [comment]
Yes, that must be it. I tested it though and it worked for me. Winona is supposed to move these files to GitHub so the schema can validate against the raw GitHub file. I'll just comment this out until she gets a copy posted to GitHub.

**Comment by davidamichelson** [comment]
Approved

**Comment by wlpotter** [comment]
This is fixed for places records (currently on [this branch](https://github.com/srophe/srophe-app-data/tree/2019-May-Batch-Changes/))
