### ISSUE TITLE
remove unused namespace declarations in place records

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#827]
See the comment [here](https://github.com/srophe/srophe-app-data/issues/765#issuecomment-632178103).

@davidamichelson would you like to keep the following namespace declarations on the root element of place records?

- xmlns:xi="http://www.w3.org/2001/XInclude"
- xmlns:svg="http://www.w3.org/2000/svg"
- xmlns:math="http://www.w3.org/1998/Math/MathML"

If so, will this require schema and documentation updates?

**Comment by wlpotter** [comment]
Related to #765

**Comment by davidamichelson** [comment]
Delete:
    xmlns:xi="http://www.w3.org/2001/XInclude"
    xmlns:math="http://www.w3.org/1998/Math/MathML"

Keep:
    xmlns:svg="http://www.w3.org/2000/svg"

**Comment by wlpotter** [comment]
I found the following additional namespaces in use:

xmlns:skos="http://www.w3.org/2004/02/skos/core#"
xmlns:xs="http://www.w3.org/2001/XMLSchema"

There may be others, which I will be testing for now. I am wondering if it might be better to make a list of what declarations we want to include in place records and simply use find-and-replace (or an Xquery) to update all records to have these, and only these, declarations?

**Comment by wlpotter** [comment]
This is the list of currently in-use prefixes for xml namespaces in place records:

syriaca
xs
svg
xi
srophe
xml
skos

**Comment by davidamichelson** [comment]
Okay let's discuss with Dan and Winona

**Comment by wlpotter** [comment]
DECISION: The following can be deleted: "xs", "svg", "xi", "skos" from place records.

**Comment by wlpotter** [comment]
Note to self:

The updated tei:TEI element should look like this:

```
<TEI xmlns="http://www.tei-c.org/ns/1.0" xmlns:srophe="https://srophe.app" xmlns:syriaca="http://syriaca.org" xmlns:svg="http://www.w3.org/2000/svg" xml:lang="en">
```

**Comment by wlpotter** [comment]
@davidamichelson I believe this needs to be updated in the documentation? See the example at https://github.com/srophe/srophe-app-data/wiki/TEI-Encoding-Manual-for-The-Syriac-Gazetteer#namespace-declaration-of-sroph%C3%A9-app-attributes

**Comment by davidamichelson** [comment]
I updated this. @dlschwartz Can you confirm that this is correct:

The namespace declaration also include xmlns:syriaca="http://syriaca.org" and xmlns:svg="http://www.w3.org/2000/svg. These have been declared in anticipation of their future use in The Syriac Gazetteer but these tag sets are not used at present.

We don't use these two at present right?

**Comment by dlschwartz** [comment]
@davidamichelson we are not using these. We replace syriaca with srophe: xmlns:srophe="http://srophe.app".

**Comment by wlpotter** [comment]
@dlschwartz @davidamichelson We have both xmlns:srophe="http://srophe.app" and xmlns:syriaca="http://syriaca.org" currently declared. I believe we replaced attributes that used the syriaca namespace with the srophe namespace (e.g. syiaca:tags -> srophe:tags).

If I remember correctly, we did not retain any instances of a syriaca namespaced element or attribute. However, #852, although a temporary change, does require us to declare the syriaca namespace. 

I'm wondering if, like with xmlns:svg, we might want to keep xmlns:syriaca in case we use it in future? It seems we would want it for a similar reason as we want multiple scopes for the schema. That is, there may be a situation where we want a syriaca-specific attribute or element (rather than srophe-specific) that makes use of the namespace.

**Comment by davidamichelson** [comment]
We are keeping them both for future development.

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson remember that as an attribute value "syriaca:manuscript" is just a string. There isn't a need for a ns declaration in this case. We would only need it if we had a namespaced element or attribute. There's no harm in keep the declaration, we're just not currently using it.
