### ISSUE TITLE
split out bib refs 

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#83]
For this John, the healer ..http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1801 only the first three bibs are correct.. the last ones are for john the evangelist pers 1826 or 1807 (alas a duplicate himself!) .  I have deleted the extra bibs from 1801 and moved them here: for easy cutting and pasting when we figure out where they belong. 

```
                <event type="attestation" xml:id="attestation1801-4" source="#bib1801-1">
                    <p xml:lang="en">Yōḥanān is commemorated in <title ref="http://syriaca.org/work/712">John, the Evangelist (text)</title>.</p>
                </event>
                <event type="attestation" xml:id="attestation1801-5" source="#bib1801-1">
                    <p xml:lang="en">Yōḥanān is commemorated in <title ref="http://syriaca.org/work/888">John the Evangelist (text)</title>.</p>
                </event>
                <event type="attestation" xml:id="attestation1801-6" source="#bib1801-1">
                    <p xml:lang="en">Yōḥanān is commemorated in <title ref="http://syriaca.org/work/949">John the Evangelist (text)</title>.</p>
                </event>
                <event type="attestation" xml:id="attestation1801-7" source="#bib1801-1">
                    <p xml:lang="en">Yōḥanān is commemorated in <title ref="http://syriaca.org/work/1160">John the Evangelist (text)</title>.</p>
                </event>
                <event type="attestation" xml:id="attestation1801-8" source="#bib1801-1">
                    <p xml:lang="en">Yōḥanān is commemorated in <title ref="http://syriaca.org/work/1917">John the Evangelist (text)</title>.</p>
                </event>
                <event type="attestation" xml:id="attestation1801-9" source="#bib1801-1">
                    <p xml:lang="en">Yōḥanān is commemorated in <title ref="http://syriaca.org/work/1959">John the Evangelist (text)</title>.</p>
                </event>
                <event type="attestation" xml:id="attestation1801-10" source="#bib1801-1">
                    <p xml:lang="en">Yōḥanān is commemorated in <title ref="http://syriaca.org/work/1455">John the Evangelist (text)</title>.</p>
                </event>
```

**Comment by wlpotter** [comment]
Add the attestations to https://syriaca.org/person/1826

**Comment by wlpotter** [comment]
@jsaintlauren quick question on this one. In the attestations pasted above from 1801 that should be moved to 1826 we have the `@source` as the BHS bibl in that record.

>Ugo Zanetti and Claude Detienne, Bibliotheca Hagiographica Syriaca, entry: 326, 1173, 1717, 497, 682, 752, 999, 1879, 1926, 1333.

When we move them to https://syriaca.org/person/1826 do we want to keep the source as the BHS bibl for John the Evangelist? Are these the right BHS numbers (how do we check?):

>Ugo Zanetti and Claude Detienne, Bibliotheca Hagiographica Syriaca, entry: 852, 683, 1753.Link to Syriaca.org Bibliographic Record.

(I may just be confused as to the BHS data provenance given the Syriaca adopted the project)
