### ISSUE TITLE
Some place names from Wilmshurst have quotation marks in the name

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#832]
See http://syriaca.org/place/1781.html

We should delete these.

**Comment by wlpotter** [comment]
Here is a full list (with the caveat that there could be a place name that begins with 'ayin and ends with aleph, which the script that generated this list would interpret as being in quotes):

http://syriaca.org/place/1138
http://syriaca.org/place/1781
http://syriaca.org/place/1807
http://syriaca.org/place/1831
http://syriaca.org/place/2486
http://syriaca.org/place/2504
http://syriaca.org/place/2510
http://syriaca.org/place/744
http://syriaca.org/place/747
http://syriaca.org/place/750
http://syriaca.org/place/759
http://syriaca.org/place/778
http://syriaca.org/place/781
http://syriaca.org/place/888

**Comment by wlpotter** [comment]
I've changed all but http://syriaca.org/place/888. I can't tell if this is truly in quotes or if there is an 'ayin at the beginning of the place name (i.e., 'Aksni or Aksni)

**Comment by davidamichelson** [comment]
Yes, it should be changed as well.  http://syriaca.org/place/888.
