### ISSUE TITLE
all place records should have at least one tei:respStmt in the tei:titleStmt

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#833]
Add a respStmt similar to the following:
```
<respStmt>
               <resp>URI minted and initial data collected by</resp>
               <name ref="http://syriaca.org/documentation/editors.xml#$$$">Creator Name</name>
            </respStmt>
```

**Comment by davidamichelson** [comment]
@dlschwartz  Do we want to require that all records have at least one `<respStmt>`? I think so and at present all but a few records do.

Both the editors and other parties who are responsible for the creation of this TEI place record are then identified individually in `<respStmt>` elements (`<resp>` stands for "responsibility"). The schema requires the record have at least one `<respStmt>` which would describe the contribution of the `<editor role="creator">`. Most records will have multiple `<respStmt>` elements, especially in cases where there were contributions made by persons who do not fall into the available @role values.

**Comment by dlschwartz** [comment]
@davidamichelson the schema should be requiring at least one `<respStmt>`. See https://github.com/srophe/srophe-eXist-app/blob/master/documentation/schemas/syriacaPlacesTEI.odd#L345. 

Can you clarify the question for me? Thanks.

**Comment by davidamichelson** [comment]
You answered the question, which was should all records have a resp. @wlpotter  will update those that are missing resps.

**Comment by wlpotter** [comment]
Fixed.
