### ISSUE TITLE
include @resp="http://syriaca.org" attributes on tei:state[@type="existences"] elements which do not have sources

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#836]
From #819 

@wlpotter Could you do this please?

@dlschwartz could the schema require this similar to #801?

**Comment by wlpotter** [comment]
Data has been updated

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson This should already be working. Have you tested? https://github.com/srophe/srophe-eXist-app/blob/master/documentation/schemas/syriacaPlacesTEI.odd#L1863

**Comment by wlpotter** [comment]
@dlschwartz yes, this is working for placeNames. But we want the same constraints (must have at least one but not both of `@resp="http://syriaca.org"` or `@source` attributes) on the `tei:state[@type="existence"]` element (full xpath: `/TEI/text/body/listPlace/place/state[@type="existence]`

**Comment by dlschwartz** [comment]
@wlpotter sorry, I missed the different context. I'll update.

**Comment by dlschwartz** [comment]
The commit above should require `@source` or `@resp` on `<state type="existence">`. Please test and close the issue if everything is working correctly.

**Comment by wlpotter** [comment]
Yes, this is working correctly. Thanks!
