### ISSUE TITLE
https://syriaca.org/person/1786 Problem file

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#84]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/1786 
This file is labeled as "Yōḥanān maʿmdānā" - but it is linked to texts on the Holy Innocents.

**Comment by wlpotter** [comment]
I believe this has been fixed as the title for https://syriaca.org/person/1786 is "Holy Innocents - ܝܠܘ̈ܕܐ ܕܐܬܩܛܠܘ ܡܢ ܐܝܪܘܕܝܣ ܒܒܝܬ ܠܚܡ "
