### ISSUE TITLE
@resp on tei:location

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#847]
Is this allowed? There is only one instance: https://github.com/srophe/srophe-app-data/blob/2019-May-Batch-Changes/data/places/tei/2882.xml#L128.

If it is allowed, I think we need documentation in the wiki about what this would mean. I'm guessing that we (or, more likely, some proxy) collected gps coordinates ourselves. Maybe, but we should document.

**Comment by dlschwartz** [comment]
What I've got by way of documentation at the moment: 
`<desc>
                In most cases the <gi>location</gi> element will have a <att>source</att> attribute pointing to the <gi>bibl</gi> element that is the 
                source of that location information. In instances were the location information has been collected by a Syriaca.org contributor but is
                not attested in print, a  <att>resp</att> is used with a value of 'http://syriaca.org'.
              </desc>`

**Comment by davidamichelson** [comment]
Great it is updated in the wiki:

```
@resp

As a rule, data in Syriaca.org records should be derived from a prior source and cited using a pointed in @source connected to a <bibl> element (see above). In some cases, however, data may be added to the records without any other source than the interpretation of the Syriaca.org editors and contributors. These additions are marked with @resp.

For example, it sometimes happens that a place name was generated by Syriaca.org for consistency of transcription, without having been derived from a print resource. In that case alone, no @source attribute may be given. Instead, a @resp attribute should be included with the value "http://syriaca.org". For example, the English headword of http://syriaca.org/place/518 is "Mount Qāsiyūn", which was not found in any of the reference sources so far consulted. This place name is therefore marked up as follows:

<placeName xml:id="name518-1" xml:lang="en" resp="http://syriaca.org">
		Mount Qāsiyūn
</placeName>

Similarly, the @reps attribute can be used with <location> in instances were the location information has been collected by a Syriaca.org contributor but is not attested in print.

```

**Comment by davidamichelson** [comment]
@dlschwartz This is ready if you have made a change in the schema please close the issue.

**Comment by wlpotter** [comment]
Reopening this because I found 11 more records that do not have a resp or source. I will add resp attributes to these records.
