### ISSUE TITLE
re-associate place records with chained ODD

### ISSUE THREAD

**Issue by wlpotter** [srophe/srophe-app-data#849]
@dlschwartz what is the location for the chained ODD file that I should associate the place records with?

**Comment by dlschwartz** [comment]
@wlpotter Here you go: https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaPlaces.compiled.rng 

When I did it on [this branch](https://github.com/srophe/srophe-app-data/tree/2019-May-Batch-Chained-ODD/data/places/tei), I just did find all "syriacaPlacesTEI.rng" and replace with "syriacaPlaces.compiled.rng"

Thanks Will

**Comment by wlpotter** [comment]
@dlschwartz one more quick question, just to confirm. We will have the following three processing instructions as the result of this update:

```
<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaPlaces.compiled.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaPlaces.compiled.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/uniqueLangHW.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?> 
```

In other words, only the first two links need to change. Is that right?

**Comment by wlpotter** [comment]
Nevermind, I checked the examples in the branch you created and answered my own question. I will make this change.
