### ISSUE TITLE
Temporary Update to Schema allowing bibl/@type="syriaca:Manuscript"

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#852]
@dlschwartz At present the works NHSL module (especially BHSE) has tei:bibl elements which do not have tei:ptr elements with Syriaca.org uris. This is because these bibl elements point at manuscripts.

This usage has bled over into the Gazetteer where we have 26 cases of bibl without ptr all of which are mss.

We will follow the NHSL module in allowing bibl/@type="syriaca:Manuscript" to not have a ptr child element.

Can you please edit the Syriaca.org general schema to allow bibl/@type="syriaca:Manuscript" to not have a ptr child element (but only that @type, otherwise it must be required).

When we get to NHSL we will solve the MSS ptr issue but shoudl let sleeping dogs lie for now.

**Comment by davidamichelson** [comment]
- [ ] @dlschwartz please change schema

- [ ] @wlpotter please change data

- [ ] @davidamichelson please update documentation

**Comment by wlpotter** [comment]
The data has been updated for this issue.

**Comment by davidamichelson** [comment]
documentation has been updated

**Comment by dlschwartz** [comment]
@davidamichelson I'm going to put this in the syriacaPlaces ODD. I'm pretty sure that `<bibl>` in NHSL can contain more than just `<author>`, `<title>`, `<editor>`, `<citedRange>`, and `<ptr>` which is what we currently have in the syriacaPlaces ODD. We can tweak for NHSL later.

**Comment by dlschwartz** [comment]
@wlpotter @davidamichelson let me know what you think of this solution. I think it works especially well for a temporary fix.

**Comment by dlschwartz** [comment]
@davidamichelson @wlpotter and by the way, I put this into the syriacaAll ODD.

**Comment by davidamichelson** [comment]
This is perfect, can we close this @dlschwartz ?

**Comment by dlschwartz** [comment]
Thanks.
