### ISSUE TITLE
Schematron Error on Check on URI/File Name

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#854]
@dlschwartz the error message that checks that the file name and the URI match seems to be appending "20" to the number that it checks.

See this error for place 1449:
```
The number portion of the <idno> element must be the same as the URI number in the file name: 201449
```

**Comment by dlschwartz** [comment]
@davidamichelson I don't get this error. Can't fix it if isn't not firing for me. Hmmm.

**Comment by davidamichelson** [comment]
Weird, let's see if @wlpotter is getting it?
<img width="1015" alt="Screen Shot 2020-06-16 at 5 58 02 PM" src="https://user-images.githubusercontent.com/3083773/84836243-f7a9b300-affa-11ea-8d53-18a2fcbcf27c.png">

**Comment by dlschwartz** [comment]
@davidamichelson show me the full file path on your machine. I had to do something funny in the RegEx and I have an idea what might be wrong.

**Comment by davidamichelson** [comment]
/Users/michelda/GitHub Repositories/srophe/srophe-app-data/data/places/tei/1449.xml

**Comment by davidamichelson** [comment]
but maybe I don't have the latest ODD?
```
<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaPlaces.compiled.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaPlaces.compiled.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/uniqueLangHW.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
```

**Comment by dlschwartz** [comment]
@davidamichelson interesting. That's the latest schema. 

I use this XPath function to strip everything but the number from the document-uri: replace(document-uri(/), '[\D]', '')

Somehow you've gotten an extra "20" somewhere in the document-uri that I don't have.

**Comment by dlschwartz** [comment]
@davidamichelson with that file open in oXygen, use the XPath box and run "document-uri(/)" and tell me what you get.

**Comment by dlschwartz** [comment]
I get: "file:/C:/Users/daniel.schwartz/Documents/GitHub/srophe-app-data/data/places/tei/1449.xml"

**Comment by dlschwartz** [comment]
I should probably write a different function that grabs everything after "tei/" and everything before ".xml" (but I thought I had a reason, a year ago, for doing what I did?). If someone kept their files in a folder with a number in the name that number wouldn't get stripped out. I'll take a look at that tomorrow.

**Comment by davidamichelson** [comment]
Okay so I tested this on my laptop and it does not have the same issue. There must be something weird going on in my path on my desktop machine. Probably not worth fixing?

**Comment by davidamichelson** [comment]
Lol, I figured it out, the path: 

System ID: /Users/ID/GitHub Repositories/srophe/srophe-app-data/data/places/tei/1449.xml

has a whitespace in it, which gets rendered as

Description: file:/Users/ID/GitHub%20Repositories/srophe/srophe-app-data/data/places/tei/1449.xml

That is where our "20" is probably coming from.

I will rename my directory with a safer name with no whitespace!

**Comment by dlschwartz** [comment]
@davidamichelson that's it. So, I've been tinkering with the Schematron and not coming up with a clear solution. Maybe I'll put this on the back burner and come back to it later.

**Comment by dlschwartz** [comment]
@davidamichelson well, I fixed the bug for when there is a space in a folder name. Here's the commit: https://github.com/srophe/srophe-eXist-app/commit/ed4fe6e679b823d49437b53a165e174396c76c17. 

If someone uses a number in a file name and then sticks the file into that folder it will still throw an error. I might have to ask Winona for some help. For the time being, however, this should be fine. I'm going to keep this issue open. Thanks.

**Comment by dlschwartz** [comment]
The commit above allows the idno in the header, which validates against the number in the file name, to validate regardless of the path where the file is located. Previously a space in a folder name or a folder name that was or contained a string of numbers would throw an error message.
