### ISSUE TITLE
Need to restore XML declaration and processing instructions in some non-place records

### ISSUE THREAD

**Issue by davidamichelson** [srophe/srophe-app-data#856]
@dlschwartz Please send us a model for the processing instructions for non-place records to use as a placeholder

**Comment by dlschwartz** [comment]
@davidamichelson @wlpotter 

Places:
`<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaPlaces.compiled.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>`
`<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaPlaces.compiled.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>`
`<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/uniqueLangHW.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>`

Persons:
`<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaAll.compiled.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>`
`<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaAll.compiled.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>`
`<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/uniqueLangHW.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>`

Works and Bibl:
`<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaAll.compiled.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>`
`<?xml-model href="https://raw.githubusercontent.com/srophe/srophe-eXist-app/master/documentation/schemas/out/syriacaAll.compiled.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>`

**Comment by wlpotter** [comment]
Woops! I forgot to link [this commit](https://github.com/srophe/srophe-app-data/commit/a5502869baf978e8115c2a28eefa1e3614811a7f) to this issue.

**Comment by wlpotter** [comment]
Note also that place schemas were updated here: https://github.com/srophe/srophe-app-data/commit/7498a93d26df81d5ec5b39a0a59451299e6250a8

**Comment by wlpotter** [comment]
Restoring the xml declaration is issue #829

**Comment by wlpotter** [comment]
This has been fixed in all data.
