### ISSUE TITLE
Needs to be split https://syriaca.org/person/2169

### ISSUE THREAD

**Issue by jsaintlauren** [srophe/srophe-app-data#87]
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/person/2169

**Comment by jedwardwalters** [comment]
@davidamichelson @jsaintlauren 
I think this one is done already.

**Comment by wlpotter** [comment]
https://syriaca.org/person/2169 is only Juventus. The other two commemorated in https://syriaca.org/work/734 (Longinus, and Maximus) have their own URIs.
