### ISSUE TITLE
anonymi in SBD

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#880]
We currently use `person/trait/label` with a text node "anonymous" for anonymi. The answer to this question depends a bit on how we see sub-modules of SBD going forward. But, I'm wondering whether instead we shouldn't be using `@ana="anonymous"` like we do for authors and saints.

**Comment by wlpotter** [comment]
Ah, I seem to have opened a duplicate issue...#928. Discussion follows there, so I will go ahead and close this one.
