### ISSUE TITLE
Missing Persons Report

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#882]
This is mostly a note to myself but if anyone has insights on this problem I'd be happy to have them. 

It looks like we are missing person records that I thought were created some time ago. They are persons 3182-3271. 

Also, it looks like URIs in the 3500s were used by E-Ktobe while also being used by the [web forms](https://github.com/srophe/draft-data/tree/master/data/fromWebforms). Most of these are anonymous persons and I will simply mint new URIs.

Encoders have used these URIs in SPEAR, but there is no data:
person/3503
person/3504
person/3528
person/3534

Encoders have used these URIs in SPEAR, but we have E-Ktobe records for other people:
person/3506
person/3526
person/3535
person/3539
person/3542
person/3545
person/3546

The [web form](https://github.com/srophe/draft-data/tree/master/data/fromWebforms) output on draft-data contains the following:

URIs used by E-Ktobe and in Webform data
3531, 3532, 3535, 3536, 3538-3540, 3547-3552, 3554, 3556-3571, 3573, 3574, 3576-3579, 3581-3583

URIs used in Webform data but not in Master
3521, 3522, 3523, 3534, 3553, 3555, 3572, 3575, 3580

Compare the URIs created via the forms to the 3500s URIs actually used in SPEAR data and it appears that encoders minted URIs through the web forms that they did not then use in encoding SPEAR records. The only overlap is person/3534. However, the person indicated by http://syriaca.org/person/3534 in the webform data is not the same person as the person cited in spear/824 (in draft-data) with that URI.

**Comment by dlschwartz** [comment]
@wsalesky @davidamichelson I'm not sure how to investigate whether we've lost records. Perhaps there's some functionality on GitHub I'm not aware of that can help. I thought that we had person records in the 3182-3271 range. Any chance one of you could offer some quick help. Thanks.

**Comment by wsalesky** [comment]
Hi Dan,
I ran a few of these to check for deleted files in the app-data repo but
did not find anything:
https://stackoverflow.com/questions/7203515/how-to-find-a-deleted-file-in-the-project-commit-history

Could they have been in draft data, not app data?
-Winona

**Comment by dlschwartz** [comment]
@wsalesky thanks! And thanks for the link too. I've checked in draft data. It looks like I never created them. I should be able to produce the spreadsheet quickly enough. Thanks for the help.

**Comment by dlschwartz** [comment]
All SPEAR data has been checked against person and place URIs. All person URIs needed have been entered into the person spreadsheet for transform using xQuery.
