### ISSUE TITLE
Missing idno elements in new person records

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-app-data#91]
See: 
http://syriaca.org/person/2786
https://github.com/srophe/srophe-app-data/blob/dev/data/persons/tei/2786.xml

Search result here:
http://wwwb.library.vanderbilt.edu/exist/apps/srophe/persons/search.html?q=Atticus+of+Constantinople

The record is in the db but has no idno in the person element, which is the hook used by most of the XQueries. I can add it back in programmatically, but the xslt that generates them will need to be updated.

**Comment by nathangibson** [comment]
Yes, of course! Can’t believe I forgot to include that!
