### ISSUE TITLE
remove tei: namespace from element names

### ISSUE THREAD

**Issue by dlschwartz** [srophe/srophe-app-data#910]
We have an incorrect namespace declaration on `<label>` elements. It may appear elsewhere. Here is an example: https://github.com/srophe/srophe-app-data/blob/master/data/persons/tei/3589.xml#L163

**Comment by wlpotter** [comment]
@dlschwartz this should be fixed; I removed both the `tei:` prefixes and any occurences of `xmlns:tei="..."` from our data
