### ISSUE TITLE
Move bibl record notes (@lang=fr) to Work records

### ISSUE THREAD

**Issue by wsalesky** [srophe/srophe-app-data#95]
For any bibl records with a note/@lang=fr please move the note to be a child of the same bibl id element in any work records with that same bibl id and delete it from the bibl record.

@davidamichelson - I moved this from the eXist-app. I'm not sure if it has been done, perhaps we can check at our next meeting?

**Comment by davidamichelson** [comment]
Okay this was done. We can close.
